### ISSUE TITLE
Update for Ruby 3.3.1

### ISSUE THREAD

**Issue by kstevens715** [whitequark/parser#1009]
Ruby 3.3.1 was released yesterday: https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-3-1-released/.

Is it possible to do a 3.3.1.0 release for `parser`?

I like to keep the following in my `Gemfile` so that `parser` tracks the version of Ruby I'm using. But this is currently failing when trying Ruby 3.3.1 because there's not yet an equivalent version of Parser:

```ruby
gem 'parser', "~> #{@ruby_version.gem_version}"
```

I made this change to my Gemfile because the last few times I updated Ruby I would subsequently realize I was getting warnings and would manually update `parser`. Using this syntax in the Gemfile ensures I do not forget to update `parser.

**Comment by iliabylich** [comment]
`3.3.1` is special, there is a grammar change that needs to be implemented first - https://github.com/whitequark/parser/issues/963#issuecomment-2072900550.

**Comment by iliabylich** [comment]
Yes, this is pretty annoying. I'm so used to backporting changes after Christmas in a single huge batch and I completely forgot about this :)

I'll take a look today, need to refresh my knowledge of  `parser`'s internals.

**Comment by dgollahon** [comment]
FWIW I'm not sure if you're trying to preserve parity with the difference between 3.3.0 and 3.3.1 in `parser`, but since the 3.3.0 behavior was a _bug_ I think you could fix forward and not preserve any of that (if you were trying to do that). `prism`, for instance, never had this behavior.

**Comment by iliabylich** [comment]
Each parser class simply follows `X.Y.<LATEST>`, this is why parser warnings about incompatible syntax exist. Once it's backported `Parser::Ruby33` will be `3.3.1` compatible (and `3.3.0` incompatible in terms of rejecting invalid syntax that is no longer rejected on `3.3.1`). I hope it doesn't sound very confusing.

**Comment by iliabylich** [comment]
[parser `3.3.1.0`](https://rubygems.org/gems/parser/versions/3.3.1.0) has been released.

**Comment by dgollahon** [comment]
> [parser `3.3.1.0`](https://rubygems.org/gems/parser/versions/3.3.1.0) has been released.

Thank you for the quick turnaround!
