### ISSUE TITLE
New 3.2.6 Release

### ISSUE THREAD

**Issue by dgollahon** [whitequark/parser#1043]
I noticed that [3.2.6](https://www.ruby-lang.org/en/news/2024/10/30/ruby-3-2-6-released/) is out. Can we get a release to suppress the typical incompatible version warning that I expect would arise?

As a note, would it be possible to make the warning less sensitive to patch releases?

**Comment by iliabylich** [comment]
> As a note, would it be possible to make the warning less sensitive to patch releases?

I think it makes sense, MRI had backward-incompatible grammar changes in patch releases in the past, so we have to "respect" it.

**Comment by dgollahon** [comment]
> I think it makes sense, MRI had backward-incompatible grammar changes in patch releases in the past, so we have to "respect" it.

I would also be happy with an opt-in "ignore_patch_warnings" option or something like that. I know it can occur but it's rare and I would like to silence it instead of waiting on a `parser` release (or having to do some by-hand) filtering.

Not a huge deal though and thanks for the quick release @koic!
