### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by YorickPeterse** [whitequark/parser#130]
Creating an issue after discussing this on IRC for a bit with @whitequark. The idea is for the parser Git repository to provide various benchmarks that can be used to assert that certain changes made performance better/worse. There are however some things we need to think about before we implement these benchmarks such as:

* Do we want to benchmark things over a range of Git commits?
* Do we want to store (and maybe plot) results somewhere?
* Do we want just the (average) runtime for parsing a certain file, or more (standard deviation, min, max, etc, etc)?
* Do we want to use something like https://github.com/evanphx/benchmark-ips to see how many parsing iterations we can cram in a certain time period?

Personally I think it would be cool if we could benchmark things over time using different Ruby implementations. This would give a more accurate idea on how parser is doing performance wise over time. The annoying part is that implementing this is pretty tricky.

Ideally the output format of the benchmarks is something that can be parsed by machines as this would ease the process of setting up an automated runner. One idea is to display some basic timings per file, dump these in a JSON file and then display them in a basic Javascript chart. This doesn't require webscale technology and should be fairly easy to run periodically.

cc @mbj as you're probably interested in this too.

**Comment by whitequark** [comment]
Does anyone even care?

**Comment by YorickPeterse** [comment]
@whitequark This isn't really important for me at the moment, so I'm fine with closing this one.

**Comment by whitequark** [comment]
Closed until someone cares.
