### ISSUE TITLE
Upgrade from slop v3 to slop v4

### ISSUE THREAD

**Issue by borski** [whitequark/parser#179]
I'd like to use slop v4.0.0 in a project I'm also using parser in, but parser relies on slop < 4.0.0. Can it get migrated to a newer version?

**Comment by whitequark** [comment]
Closed in #181 (sort of).

**Comment by bbatsov** [comment]
@whitequark Guess you should cut 2.2.0.2.

**Comment by whitequark** [comment]
Done
