### ISSUE TITLE
Comment.associate 

### ISSUE THREAD

**Issue by kubicle** [whitequark/parser#185]
Code like below is not associating the comment:
```
def foo
  p "hello" # decoration comment on last line 
end
```

**Comment by kubicle** [comment]
Similarly, but less frequent, comments at the end of a file are not associated. 
I am planning to fork the repo and propose an "associator" that can make the difference between "decoration" comments (attached at the end of a line) and other comments. 
If I am the only one with this need, feel free to close my PR.

**Comment by JoshCheek** [comment]
I hit the end of file comments, too. I deal with it by checking the tokens https://github.com/JoshCheek/seeing_is_believing/blob/267b9e8f5a8cdff268658376bb10670de102c58f/lib/seeing_is_believing/code.rb#L123-130

**Comment by whitequark** [comment]
This is really a parser bug :/
