### ISSUE TITLE
Warning on Ruby 2.1.6

### ISSUE THREAD

**Issue by pusewicz** [whitequark/parser#189]
Running `parser` on Ruby 2.1.6 yields this:

```
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.5-compliant syntax, but you are running 2.1.6.
```

**Comment by pusewicz** [comment]
Thanks!

**Comment by phlegx** [comment]
```
warning: parser/current is loading parser/ruby21, which recognizes  2.1.5-compliant syntax, but you are running 2.1.6
```

with parser version 2.2.0.3 and rubocop 0.30.0

**Comment by whitequark** [comment]
You need at least parser 2.2.0.4 for Ruby 2.1.6.

**Comment by mlcooper** [comment]
Getting the error
```
$ rubocop <filename>.rb
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.5.
```
with rubocop 0.32.0 and parser 2.2.2.5

**Comment by whitequark** [comment]
@mlcooper  You should run ruby 2.1.6.

**Comment by printercu** [comment]
@whitequark Hi! I'm getting
```
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.1.
```
wdyt about not showing warnings when only patch version is different?

**Comment by whitequark** [comment]
because Ruby changes syntax in patch versions.

**Comment by printercu** [comment]
didn't know it. thanks!

**Comment by mbj** [comment]
@whitequark To reduce the support overhead for this issue class, what about adding a link to the warning message to https://github.com/whitequark/parser#compatibility-with-ruby-mri that explains the reason for those warnings well?

**Comment by bbatsov** [comment]
Sounds like a good idea. So many people are reporting this problem... it's annoying for me, it has to be annoying for @whitequark as well...

**Comment by whitequark** [comment]
Yeah, this is a good idea. I'll get to it later today

**Comment by whitequark** [comment]
https://github.com/whitequark/parser/commit/ad19c475a58b8f7a99bf57a02cd0136e0ed5390a

**Comment by calfzhou** [comment]
I'm meeting the same issue with @mlcooper 
```
$ rubocop <filename>.rb
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.5.
```

Besides upgrade to ruby 2.1.6, is there any other thing i can do to avoid this warning? We have a dozen of projects running in 2.1.5, and not ready to upgrade it.

**Comment by mbj** [comment]
> Besides upgrade to ruby 2.1.6, is there any other thing i can do to avoid this warning?

Use an older version of parser.

**Comment by jakeonrails** [comment]
For older projects is there a list of ruby -> parser -> rubocop versions that work well together?

**Comment by fatemehm** [comment]
Hey! I am getting these errors :( how can I figure out this?
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.5-compliant syntax, but you are running 2.3.0.

**Comment by whitequark** [comment]
@fatemehm Update your Ruby to 2.3.5.
