### ISSUE TITLE
Update changelog for 2.2.2.0

### ISSUE THREAD

**Issue by saizai** [whitequark/parser#191]
Current changelog only goes to 2.2.0.4; doesn't explain diff to 2.2.2.0.

**Comment by whitequark** [comment]
2.2.2.0 does not have any difference from 2.2.0.4, it's just that the first three numbers should have been equal to latest released Ruby MRI and I sort of missed the 2.2.2 release.

**Comment by saizai** [comment]
I'd suggest just saying that in the changelog, then.

It's good to have the versions there for when people (like me) go to see
what changed on a bundle update.

**Comment by whitequark** [comment]
The changelog is autogenerated from `git log` by a script I wrote a few years ago. I'm inclined to think it was a mistake, today...

**Comment by saizai** [comment]
Not entirely a bad idea, but it seems like it just doesn't handle the base
case where there's no logs between releases.

**Comment by mvz** [comment]
> it's just that the first three numbers should have been equal to latest released Ruby MRI

Would you mind updating CONTRIBUTING.md, which now states parser uses semantic versioning?

**Comment by whitequark** [comment]
Done

**Comment by mvz** [comment]
Thanks!
