### ISSUE TITLE
Refuses to parse valid regexp %r(\))

### ISSUE THREAD

**Issue by mvz** [whitequark/parser#192]
The following is valid Ruby since, it seems, at least 1.8.7:
```ruby
%r(\))
```

However, this generates an error with at least parser 2.2.2.1 and 2.2.0.4, but not with 2.2.0.2:
```ruby
require 'parser/current'
Parser::CurrentRuby.parse '%r(\))'
```

**Comment by whitequark** [comment]
For fuck's sake. Trying to support this language properly is unbearable.

I'll fix this later today...

**Comment by bbatsov** [comment]
Is it valid in newer Rubies as well?

**Comment by bbatsov** [comment]
Likely, but still - I had to ask.

**Comment by whitequark** [comment]
Yeah.

**Comment by whitequark** [comment]
What the actual fuck
```
[1] pry(main)> /\//.source
=> "/"
[2] pry(main)> %r(\)).source
=> "\\)"
```

**Comment by whitequark** [comment]
Ok, I reverse-engineered it. The regexp is initialized verbatim as it appears in the source, including any backslashes, *except* when the backslash escapes a %-string delimiter which is *not* a regexp metacharacter.
```
[27] pry(main)> /./.source
=> "."
[28] pry(main)> /\./.source
=> "\\."
[29] pry(main)> %r.\...source
=> "\\."
[30] pry(main)> /'/.source
=> "'"
[31] pry(main)> /\'/.source
=> "\\'"
[32] pry(main)> %r'\''.source
=> "'"
[33] pry(main)> (0x00..0x7f).map { |x| x=x.chr; begin eval("%r#{x}\\#{x}#{x}").source; rescue SyntaxError; "no#{x}" end }.select { |x| x[0] == "\\" }
(eval):1: warning: encountered \r in middle of line, treated as a mere space
=> ["\\$", "\\)", "\\*", "\\+", "\\.", "\\>", "\\?", "\\]", "\\^", "\\|", "\\}"]
```

**Comment by whitequark** [comment]
This was actually introduced as a broken fix for #125.

**Comment by mvz** [comment]
Thanks!

**Comment by mbj** [comment]
> This was actually introduced as a broken fix for #125 cc @mbj

Mhh. I reported #125 back, and I had a test for `%r(\))` in unparser specs for a long time, it worked upto the latest releases of parser. I think that this regression was introduced very recently.

Too me it looks like the bug was introduced between 2.2.0.3 and 2.2.0.4:

```
% bundle exec ruby-parse --version
ruby-parse based on parser version 2.2.0.3
% bundle exec ruby-parse -e '%r(\))'
(regexp
  (str ")")
  (regopt))
% bundle exec ruby-parse --version
ruby-parse based on parser version 2.2.0.4
% bundle exec ruby-parse -e '%r(\))'
(fragment:0):1:1: error: unmatched close parenthesis: /)/
%r(\))
^^^^^^
```

**Comment by whitequark** [comment]
Oh, it certainly did not /error/ out on 2.2.0.3 and earlier, because before 2.2.0.4 syntax of regular expressions was not validated.

**Comment by mbj** [comment]
> Oh, it certainly did not /error/ out on 2.2.0.3 and earlier, because before 2.2.0.4 syntax of regular expressions was not validated.

Ahh. Thx for clearing that up for me.
