### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by mbj** [whitequark/parser#193]
It would be nice to get https://github.com/whitequark/parser/commit/341f5555f56f698862e62e809c250a223d5034bc as part of a release.

I'd like to release unparser compatible with the `2.2.2.x` branch, the fix in the commit above prevents unparsers specs (that round trip a `%r(\))` instance) from passing.

Parsing `%r(\))` seems to be broken since `2.2.0.4`, I did not do an unparser release since parser `2.2.0.1` so I did not notice earlier.

**Comment by whitequark** [comment]
Done

**Comment by mbj** [comment]
Thx.
