### ISSUE TITLE
Improve trailing comment association.

### ISSUE THREAD

**Issue by RGBD** [whitequark/parser#194]
### Reasoning

Consider this code:

``` ruby
class C
  def foo # def C#foo
    puts 'foo' # puts 'foo'
  end # def C#foo end

  def bar # def C#bar
    puts 'bar' # puts 'bar'
  end # def C#bar end
  
  #totally unrelated comment
end
```

It associates comments in the following way:

```
(class
  (const nil :C) nil
  (begin
    (def :foo
      (args)
      (send nil :puts
        (str "foo")))
    (def :bar
      (args)
      (send nil :puts
        (str "bar")))))
>>> 1: 0:# class C before
(def :foo
  (args)
  (send nil :puts
    (str "foo")))
>>> 3:10:# def C#foo
(str "foo")
>>> 4:15:# puts 'foo'
(def :bar
  (args)
  (send nil :puts
    (str "bar")))
>>> 5: 6:# def C#foo end
>>> 7:10:# def C#bar
(str "bar")
>>> 8:15:# puts 'bar'
(begin
  (def :foo
    (args)
    (send nil :puts
      (str "foo")))
  (def :bar
    (args)
    (send nil :puts
      (str "bar"))))
>>> 9: 6:# def C#bar end
>>>11: 2:#totally unrelated comment
```

See bigger example: [source](https://gist.github.com/RGBD/0fc6e0377fdefbbf721b#file-test-rb) and [output](https://gist.github.com/RGBD/0fc6e0377fdefbbf721b#file-default-log).
Also, it partly hides bug in [rubocop](https://github.com/bbatsov/rubocop).

### My opinion

I think, this is a bit counter-intuitive. Also now
Parser::Source::Comment::Associator#accociate contains a workaround for
trailing (akasparse in tests) comments, which might, or might not be associated
with enclosing or preceding block (see gist).

### What can be done

I propose another principle of comment association.

#### Features

- It is unambiguous
- It is scalable, association for the whole tree is exactly the same as
  united association for every node (on sparse comments later)
- It has the same behaviour for preceding comments, so that any documentation
  generator using this gem will keep working (correct me if I'm wrong).
- It is configurable, you can deside, whether you need these or that kind of
  comments

#### Definitions

Suppose previous node has been processed.

- Comment is **preceding**, if it starts before the beginning of current node.
  **preceding** comments are supposed to be documenting.
- Comment is **sparse**, if it is inside the body of current node, and after
  the last child node. **sparse** comments' purpose is ambiguous, they could be
  ignored.
- Comment is **decorating**, if it starts at the current node ending line.
	**decorating** comments comment expression before them, or block endings.

### Summary

I hope you will consider my proposal and check out my implementation in (#195)

**Comment by whitequark** [comment]
This looks really, really good on a first glance. I will give it a bit more thought in the following days.

**Comment by RGBD** [comment]
Good, I'd be happy if @bbatsov checks this out, as it would affect his repo.

**Comment by whitequark** [comment]
Looks good to me. Your test cases in the gist are really exhaustive, could you also add some tests to accompany code changes? After that it should be mergeable.

**Comment by bbatsov** [comment]
The suggested changes look good to me.

**Comment by mbj** [comment]
Also looks good from my side, unparser will produce better results.

**Comment by RGBD** [comment]
@whitequark, I've added tests.
