### ISSUE TITLE
Parse issue with regexp backreferences and one-characters string (eg. ?#)

### ISSUE THREAD

**Issue by blutorange** [whitequark/parser#198]
- parser-2.2.2.5
- tried it with ruby 2.2.1, 2.2.0, 2.0.0, 1.9.3, jruby-1.7.19

Came across this incidentally. Try the following code with *parser*:

    require 'parser/current'
    code = <<eos
    /()\\1/
    ?#
    eos
    p Parser::CurrentRuby.parse(code)

This outputs:

    (begin
      (regexp
        (str "()\\1")
        (regopt))
      (str "\u0001"))

The *str* should not be `"\u0001"`, but `(str "#"))`. If I remove the backreference `\1` in the regexp or use a normal string (`"#"` or `'#'`) instead of `?#`, it works as expected and parses it as `(str "#"))`.

Also, ruby 1.9.3 and jruby returns `(str "\x01"))` instead, which is still a 0x01 byte and not `#`.

**Comment by whitequark** [comment]
Impressive.

This holds the record for the most obscure parser's own bug so far.
