### ISSUE TITLE
Add support for &.

### ISSUE THREAD

**Issue by whitequark** [whitequark/parser#209]
Upstream commit https://github.com/ruby/ruby/commit/a356fe1c3550892902103f66928426ac8279e072

**Comment by whitequark** [comment]
Also https://github.com/ruby/ruby/commit/0b7d473734d0dec8520afe7a36540aa1f40d2532

**Comment by whitequark** [comment]
Node name ideas? Regular `s.x` is `(call (lvar :s) :x)`, what would this be? `(qcall)`?

**Comment by whitequark** [comment]
cc @mbj @bbatsov @YorickPeterse

**Comment by mbj** [comment]
> Regular s.x is (call (lvar :s) :x), what would this be? (qcall)?

Regular is AFAIK `(send ...)`.


Maybe `csend` for "conditional send". As this syntax is effectively a shorthand for a conditional on nil receiver.

What is the `q` prefix in `qcall` referring to?

**Comment by bbatsov** [comment]
> What is the q prefix in qcall referring to?

Question mark I guess. I think `csend` is a better idea than `qsend`. Another good option would `ssend` (safe send), but I guess it would be easier to mistype it.

**Comment by backus** [comment]
https://bugs.ruby-lang.org/issues/11537 refers to this as the "safe navigation operator" which does seem to be the term across several different languages (C#, Groovy).  What about `(safenav)`?

**Comment by troessner** [comment]
+1 for (safenav), "conditional send" would be highly confusing IMHO.

**Comment by bbatsov** [comment]
I believe the node name should have `send` in it for consistency with the regular call sites. For many people even the name `send` is confusing. :-)

**Comment by troessner** [comment]
Then I'd go with "safesend" ;)

**Comment by YorickPeterse** [comment]
Either `safesend` or `ssend` should do.

**Comment by mbj** [comment]
IMO not sending something to a `nil` receiver is not inherently "safe" at all. This operator is a branching abstraction, and the name should IMO focus on that aspect.

**Comment by troessner** [comment]
>> IMO not sending something to a nil receiver is not inherently "safe" at all. This operator is a branching abstraction, and the name should IMO focus on that aspect.

Good point. Then we're back to "csend" I guess :laughing:

**Comment by whitequark** [comment]
`csend` it is.

**Comment by bbatsov** [comment]
:+1:

**Comment by JoshCheek** [comment]
Or `send?` :P

**Comment by whitequark** [comment]
@JoshCheek Hmmm, actually not a bad idea

**Comment by mbj** [comment]
I'd that AST node types should stay pure alphabetic + underscore. I realize `defined?` is violating this right now and will not be changed.

**Comment by whitequark** [comment]
I don't really think that's important. There's no reason to avoid valid symbols.

**Comment by mbj** [comment]
I've a selfish reason:

Node types can be processed into predicates on node types in a unique manner right now. `define_method("#{node_type}?") ...` 

With one special case for `defined?`, it just becomes `defined?`, as there is no ambiguity with a node `defined` that would also nap to `defined?`.

If we have `send` and `send?` this mapping to predicate names is no unique anymore.

**Comment by whitequark** [comment]
ahhh. Good point actually.

**Comment by whitequark** [comment]
Also https://github.com/ruby/ruby/commit/dbf73f6fc2a4b0414110eea64a9f98d33c2cf930

**Comment by whitequark** [comment]
(where does the madness end?!)

**Comment by mbj** [comment]
> (where does the madness end?!)

Its called feature creep and does not have an end.

**Comment by whitequark** [comment]
lolwhat https://github.com/ruby/ruby/commit/a3ee54f8a653f2e7c8ea88ef5ee9f3a49a248447

**Comment by YorickPeterse** [comment]
@whitequark https://bugs.ruby-lang.org/issues/11618#note-1

**Comment by whitequark** [comment]
jesus https://github.com/ruby/ruby/commit/837babd56459aafc1232a12fbfa783025d619b98

**Comment by bbatsov** [comment]
This is getting totally ridiculous...

On 6 November 2015 at 08:18, whitequark <notifications@github.com> wrote:

> jesus ruby/ruby@837babd
> <https://github.com/ruby/ruby/commit/837babd56459aafc1232a12fbfa783025d619b98>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whitequark/parser/issues/209#issuecomment-154317470>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by YorickPeterse** [comment]
Welcome to Ruby.

**Comment by whitequark** [comment]
anyway, how do we even call it now? `:acall`?

**Comment by YorickPeterse** [comment]
I think `csend` still makes sense.

**Comment by mbj** [comment]
Its still a conditional syntax. So lets stay with `csend`.

**Comment by bbatsov** [comment]
+1 for `csend`.

On 6 November 2015 at 11:53, Markus Schirp <notifications@github.com> wrote:

> Its still a conditional syntax. So lets stay with csend.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whitequark/parser/issues/209#issuecomment-154366723>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by whitequark** [comment]
Also https://github.com/ruby/ruby/commit/a01b6453eb9d9e396f76f7bc73439f6669d0f5fb.

**Comment by bbatsov** [comment]
Makes sense.

On 10 November 2015 at 12:13, whitequark <notifications@github.com> wrote:

> Also ruby/ruby@a01b645
> <https://github.com/ruby/ruby/commit/a01b6453eb9d9e396f76f7bc73439f6669d0f5fb>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whitequark/parser/issues/209#issuecomment-155377376>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by whitequark** [comment]
AAAAAAAA WHY https://github.com/ruby/ruby/commit/68e16ddd7961b86e5013e62ae2954e88638de058

**Comment by mbj** [comment]
> AAAAAAAA WHY ruby/ruby@68e16dd

Because Ruby!

**Comment by whitequark** [comment]
Amazing; turns out we never had any tests for the 'fluent interface'.

**Comment by whitequark** [comment]
This went surprisingly painless.
