### ISSUE TITLE
Deceiving performance claims

### ISSUE THREAD

**Issue by alexdowad** [whitequark/parser#210]
This is a great library and I am looking forward to using it. However, the performance claims on your home page are rather deceiving, to say the least:

```
[12] pry(main)> Benchmark.measure { Parser::Ruby22.parse(src) }
=> #<Benchmark::Tms:0x0055c475a90f58
 @cstime=0.0,
 @cutime=0.0,
 @label="",
 @real=1.7308918950147927,
 @stime=0.0,
 @total=1.7300000000000004,
 @utime=1.7300000000000004>
[13] pry(main)> Benchmark.measure { Ripper.sexp(src) }
=> #<Benchmark::Tms:0x0055c47640a228
 @cstime=0.0,
 @cutime=0.0,
 @label="",
 @real=0.08611725084483624,
 @stime=0.0,
 @total=0.08000000000000007,
 @utime=0.08000000000000007>
```

A page with actual benchmark results would be very helpful to people assessing the library for the first time.

**Comment by bbatsov** [comment]
You're comparing apples to oranges here. Try working with the output of `Ripper.sexp` and you'll see what I mean... Parsing speed doesn't mean much if you end up with an AST format which is extremely hard to work with (and ripper's nested arrays are exactly this).

**Comment by alexdowad** [comment]
Absolutely. I have worked with the output of `Ripper.sexp`. That's how I found myself here.

That still doesn't change that the documentation makes a claim which is completely false:

"It performs on par or better than Ripper, Melbourne, JRubyParser or ruby_parser."

**Comment by whitequark** [comment]
I never meant "execution time" under "performs" in that phrase; rather, it was referring to the coverage of Ruby's features. In fact, at least Ripper, Melbourne and JRubyParser are and will for foreseeable future be non-negligibly faster than Parser, with the possible exception of Parser on JRuby at some future moment. I of course always knew this; it would be absurd to make that claim.

However, none of those parsers are able to correctly recognize the syntax of all Ruby versions since 1.8 while running on all Ruby versions since 1.9 with a unified AST format, and in fact many of those have blatant omissions (particularly ruby_parser, but Melbourne is abandoned now and I'm reasonably certain JRubyParser lagged at times).

**Comment by alexdowad** [comment]
In the context of computer programming, the word "performance" (in its various forms) almost always refers to the elapsed time required to carry out an operation, or the number of operations which can be completed in a unit of time (i.e. throughput). That's not what you meant, but it is how most readers will interpret your words.

**Comment by whitequark** [comment]
It is quite curious then that in the course of ~2.5 years of Parser's existence and ~4M downloads you were the only one who found that confusing enough to open an issue.

Not that I don't necessarily think it shouldn't be reworded, it's just that this argument doesn't hold water.

**Comment by alexdowad** [comment]
I can't speak for all the others who have downloaded this gem. I can only say that for myself, the documentation sends a clear message, which is at variance from what was intended.

**Comment by bbatsov** [comment]
@whitequark somewhat amusingly `parser` has around 4M downloads and RuboCop around 3.7M. Does this make us a premium client or something? :-)

**Comment by whitequark** [comment]
@bbatsov Kinda. It is true that most of those are driven by Rubocop being installed on CI :) according to GitHub's rudimentary analytics there is only ~1200 or so monthly unique views of the README.

Anyway, any ideas for a better wording?

**Comment by alexdowad** [comment]
I really wanted to come up with something, but I'm having writer's block. I know you won't want something wordy and awkward. Punchy, to the point, but accurate. Maybe I'll think of something tomorrow.

**Comment by mbj** [comment]
"Most performant, cross Ruby version, cross Ruby implementation pure Ruby parser"

**Comment by whitequark** [comment]
You could even say "Most performant Ruby parser in its feature class" :p

**Comment by mbj** [comment]
The size of the set of parsers that qualifies for all the features I listed above is: 1.
