### ISSUE TITLE
Feature request: Method to test for valid literal method name.

### ISSUE THREAD

**Issue by mbj** [whitequark/parser#213]
For a feature in mutant I need to be able to determine if a given string is a valid literal method name.

While I could simply generate source and attempt to parse it, like:

`Parser::CurrentRuby.parse("def #{candidate_method_name}; end")`

It would be a horrible use of ad-hoc code generation + parsing:

Input candidate method names like: `'valid_method; end # invalid_crap'` would easily bypass the check, as only the prefix of the candidate is checked for validity. Lots of other edge cases like this could be constructed. Its true the resulting AST could be checked for additional nodes, comments being parsed but still: Ugly.

I realize that this feature request could be out of scope of this project. The source of truth for "valid literal method names" is already present in the lexer + parser components, so it might be exposable for the general public, without huge complexity increase.

Or it might even be present in a semi-public API where I'd be happy to use it. Calling into the lexer with a pre set-up state?

**Comment by whitequark** [comment]
Well, actually there is no simpler method to do it that I see. You have the lexer component and the parser component; the lexer has a good bunch of tokens it can emit from `expr_fname`, and not all of them are valid method names:
![1435](https://cloud.githubusercontent.com/assets/54771/11015577/cb69fc42-8574-11e5-98b5-555a45783960.png)

whereas the parser has several dozen branches dedicated to making sense of that:
![1434](https://cloud.githubusercontent.com/assets/54771/11015561/8a6433d4-8574-11e5-9370-e70868f08d20.png)

Worse, they all change with Ruby versions.

So what I suggest is doing this, which is actually pretty concise and 100% reliable:

```
def check_name(name)
  buffer = Parser::Source::Buffer.new('<input>')
  buffer.source = "def #{name}; end"

  Parser::CurrentRuby.new.parse(buffer) == 
    Parser::AST::Node.new(:def, [name.to_sym, 
      Parser::AST::Node.new(:args), nil])
rescue Parser::SyntaxError
  false
end
```

**Comment by mbj** [comment]
@whitequark Thx. Just to be sure we are on the same page: Will this account for the fact when part of the name to check is interpreted as a comment?

**Comment by whitequark** [comment]
Sure, it checks that the name that the parser returned is the same as the input.

**Comment by mbj** [comment]
k, thx. Closing this.
