### ISSUE TITLE
Difference between attribute or function

### ISSUE THREAD

**Issue by Peekmo** [whitequark/parser#214]
Hello,

First of all, thank you for this great lib ! Really easy to use, and good !
I would like to know if there's a way to know if a node is a function call (without params) or an attribute call.

Exemple with ```AST::Node``` ```type``` and ```to_s``` I have something like this : 

```
  (send
    (lvar :node) :type)
  (send
    (lvar :node) :to_s))
```

I know that it's need a lot of logic, and so, I guess that it's not possible. However, I prefer to wait for your answer before starting to cry ^^

Best regards,
Peekmo

**Comment by whitequark** [comment]
There is no difference between attributes and functions in Ruby. `attr_reader :x` is, observably, exactly equivalent to `def x; @x; end`.

**Comment by Peekmo** [comment]
Ok thank you, I thank that there was a difference.

Regards,
Peekmo
