### ISSUE TITLE
failed to run in ruby-2.3.0-preview1

### ISSUE THREAD

**Issue by flyerhzm** [whitequark/parser#226]
I installed ruby 2.3.0-preview1 and latest parser 2.3.0.pre.3, but when I run in irb, I got an error

```
> RUBY_VERSION
 => "2.3.0"
> Parser::VERSION
 => "2.3.0.pre.3"
> require 'parser/current'
LoadError: cannot load such file -- parser/ruby23
```

**Comment by whitequark** [comment]
Whoops, forgot to add `ruby23.rb` to gemspec. Should work now with `pre.4`!

**Comment by flyerhzm** [comment]
`pre.4` works well, thanks!
