### ISSUE TITLE
<<~SQUIGGLY_HEREDOC in Ruby MRI 2.3.x

### ISSUE THREAD

**Issue by whitequark** [whitequark/parser#228]
See upstream commit https://github.com/ruby/ruby/commit/9a28a29b870b5f45d370bc8f16c431b435f0bbb3 and Ruby bug https://bugs.ruby-lang.org/issues/9098

**Comment by mbj** [comment]
Will this also include:

`<<~'SQUIGGLY_HEREDOC'` that disables interpolation?

**Comment by mbj** [comment]
Why, I'm asking. I do not see that one covered by the upstream tests, but it could work by "accident" (and may be buggy).

**Comment by whitequark** [comment]
lol `x<<~FOO` is already valid syntax actually. https://bugs.ruby-lang.org/issues/9098#note-24

This is such a clusterfuck.

**Comment by whitequark** [comment]
@mbj Yes, `<<~'X'` would be supported.

**Comment by whitequark** [comment]
I'm withholding implementation of this in case it gets reverted in MRI.

**Comment by chastell** [comment]
(FWIW, squiggly heredoc was kept in the recently-released Ruby 2.3.0.)

**Comment by bbatsov** [comment]
Hmm, I didn't see it in the release notes. Are you sure?

**Comment by backus** [comment]
@bbatsov https://github.com/ruby/ruby/blob/v2_3_0/NEWS#L53-L57

**Comment by whitequark** [comment]
Ugh.

**Comment by bbatsov** [comment]
Hmm, I wonder why they omitted such a big change here - https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/

Anyways, good to know!

**Comment by troessner** [comment]
>> Hmm, I wonder why they omitted such a big change here - https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/

Human error?

**Comment by bbatsov** [comment]
Likely so.

**Comment by bbatsov** [comment]
@whitequark is the this the final thing that has to be added before 2.3 final is released?

**Comment by whitequark** [comment]
Yes.

**Comment by whitequark** [comment]
*sob*

@mbj, here's the answer to your question: https://github.com/ruby/ruby/commit/b1796737cf097ff7dc68b12ebb6d86a9528c95be.
This is going to be a compatibility nightmare, wouldn't it?

**Comment by lucascaton** [comment]
Hi there. When will 2.3 final be released? Thanks! :smile:

**Comment by whitequark** [comment]
When it's done. If it's not done, it's because I haven't had time to implement it yet.

**Comment by lucascaton** [comment]
No problem, I didn't mean to be pushy. Thanks!

**Comment by whitequark** [comment]
No offence taken, I am merely stating how the development process works. Anyway, this is one of the less annoying changes far as Ruby goes, I should be able to do it soon.

**Comment by whitequark** [comment]
Yay, I found a bug in Ruby's implementation (of course).

**Comment by bbatsov** [comment]
That sucks. Might I suggest releasing something that will cover the majority of cases and do so refinements afterwards. AFAIK there are a ton of edge cases that are making adding the support for this so painful.

**Comment by whitequark** [comment]
Well, my (fairly naive) implementation should have the same bugs as MRI, which is ... well ... good .... I guess?

**Comment by bbatsov** [comment]
Yep, that'd be good enough.

**Comment by whitequark** [comment]
The bug in question: https://bugs.ruby-lang.org/issues/11989

**Comment by whitequark** [comment]
HAhahahahah. I found a SECOND bug.

**Comment by whitequark** [comment]
The second bug in question: https://bugs.ruby-lang.org/issues/11990

**Comment by whitequark** [comment]
That was a disturbing experience.

**Comment by chastell** [comment]
Speaking with my Reek hat on: I fully understand the frustrations and _so_ much appreciate this! Thanks!

**Comment by whitequark** [comment]
I think the most ironic part is https://github.com/whitequark/parser/issues/228#issuecomment-169841030.

**Comment by chastell** [comment]
…also that part where your Redmine reports look off because non-`<code>`-wrapped adjacent whitespace in HTML is collapsed on render.

![screenshot from 2016-01-14 20 30 05](https://cloud.githubusercontent.com/assets/56633/12335081/a4183212-bafd-11e5-8b5f-812dc64bf106.png)

**Comment by whitequark** [comment]
It *is* `<code>`-wrapped, or at least, <code>`</code>-wrapped.

**Comment by whitequark** [comment]
Yep, Redmine swallows any tags I try to put through it but <code>\`</code> results in a `<code>`.

**Comment by chastell** [comment]
Oooh, TIL browsers also collapse `<code>` whitespace on render. I lived almost twenty years in a lie. `&nbsp;` (or ` `) is your only hope then.

**Comment by whitequark** [comment]
@chastell nope, neither works.

**Comment by whitequark** [comment]
All Ruby bugs have been fixed and I have also committed that to Parser master.

**Comment by chastell** [comment]
Awesome, most appreciated!

**Comment by nijikon** [comment]
@whitequark new release after this commit 01cafc9716af7d9fd8228d548d8dd0360586a156?

**Comment by whitequark** [comment]
Ruby wasn't released though
