### ISSUE TITLE
Global way to disable syntax deviation warnings

### ISSUE THREAD

**Issue by eapache** [whitequark/parser#229]
The message printed by `warn_syntax_deviation` tends to confuse automated tools that depend on parser or depend on something that depends on parser, etc.

In my particular case, I have an automated tool set up to run rubocop (which uses parser). A change in my ruby version means that now rubocop (by loading parser) prints the syntax deviation warning, which confuses the tool that is expecting rubocop output, not parser output.

I'd greatly appreciate a way to disable the syntax warning, since my tool really shouldn't have to care about the output format of the *dependencies* of the tool it's running.

(I would actually argue that a library shouldn't be printing anything directly to standard output in the first place, at least not without explicitly being requested by the caller, but that's a much stronger claim).

**Comment by mbj** [comment]
OT: Shouldnt you use the rubocop output directly from the rubocop API? Not parsing it?

**Comment by eapache** [comment]
The automated tool is not written in Ruby.

**Comment by mbj** [comment]
OT: Doesnt rubocop have machine readable output? JSON or such?

**Comment by eapache** [comment]
It does, that's the point. The syntax warning printed by `parser` makes the output invalid JSON.

**Comment by mbj** [comment]
Doesnt rubocop write this to a file? And AFAIK parsers warning goes to stderr, rubocop (if it does not write the JSON to the file) puts the output to stdout. So capture only one of them.

**Comment by whitequark** [comment]
It's printed to stderr. Even if your automatic tool captures the output of another, it shouldn't parse stderr and stdout together.

**Comment by bbatsov** [comment]
Btw, for the protocol, I also think having an option to disable the warning won't hurt. And I'm pretty sure it's RuboCop's job to provide the ability to suppress this.

**Comment by whitequark** [comment]
There is already an option: `ruby -W0 -S rubocop`.

**Comment by bbatsov** [comment]
I really think that this is not the answer, but fine... I'm too busy to argue.
