### ISSUE TITLE
Bug lexing "a?=b"

### ISSUE THREAD

**Issue by SilverPhoenix99** [whitequark/parser#255]
Hi, all.

I'm in version `2.3.0.1` with ruby `2.2.3`.

This is tokenizing incorrectly (`test_lex` is a wrapper around `Parser::Lexer`):

```test_lex 'a?=b'```

It's returning:

```
=> [[:tFID, ["a?", #<Parser::Source::Range (string) 0...2>, {:line_begin=>:expr_arg}]],
 [:tEQL, ["=", #<Parser::Source::Range (string) 2...3>, {:expr_arg=>:expr_beg}]],
 [:tIDENTIFIER, ["b", #<Parser::Source::Range (string) 3...4>, {:expr_beg=>:expr_arg}]],
 [false, ["$eof", #<Parser::Source::Range (string) 5...5>, {:expr_arg=>:expr_arg}]]]
```

Using Ripper:

```Ripper.lex 'a?=b'```

it returns:

```
=> [[[1, 0], :on_ident, "a"], [[1, 1], :on_CHAR, "?="], [[1, 3], :on_ident, "b"]]
```

Note the difference:

```
Parser            Ripper
---------------------------------
a? (tFID)        a  (tIDENTIFIER)
=  (tEQL)        ?= (tCHAR)
```

According to `parse_ident` in MRI, it never accepts an `'='` after a `'?'`:

```
if ((c == '!' || c == '?') && !peek('=')) {
```

@alexdowad, I know that you have been working on cleaning the string states in https://github.com/whitequark/parser/pull/249, so I thought that this could be checked with the PR.

**Comment by alexdowad** [comment]
@SilverPhoenix99 Can you come up with a case where `parser` comes up with an AST which is not compatible with the one produced by Ruby's built-in parser?

**Comment by whitequark** [comment]
Not a bug but trivial to fix.

**Comment by whitequark** [comment]
To elaborate, this is not a bug because we do not provide any particular guarantees on token streams that do not produce a valid parse tree. On the other hand token streams are a public interface, so might as well clean them up, especially if it is trivial.

**Comment by SilverPhoenix99** [comment]
Hi.

Sorry, but I don't recall how I got to that rule, but this one is valid and parseable, assuming that `a` is a method:

`Ripper.sexp "a?='b'"`

This is equivalent to `a("=" "b")`.

I'll be more careful to add a parseable rule. Thanks for fixing this.
