### ISSUE TITLE
Cool Range#line down

### ISSUE THREAD

**Issue by alexdowad** [whitequark/parser#260]
`Range#line` is a very significant hotspot for RuboCop (about 10% of runtime when inspecting code).

Probably the best way to cool it down would be for the lexer to track line numbers and pass a line number to `Range.new` when initializing ranges. Since the lexer already treats newlines specially in most cases, code could be added to increment a line number count.

Another option would be to cache `Range#line`. The problem here is that ranges are frozen after initialization.

Thoughts?

**Comment by whitequark** [comment]
Hm, either will work... caching line numbers can be done inside (mutable) `Source::Buffer`. On the other hand that's still one calculation more than is necessary.

**Comment by alexdowad** [comment]
When I have a bit of time I'll try coding something up and you can review.

**Comment by alexdowad** [comment]
Regarding solution 1, it turns out the tricky part is dealing with heredocs, like:

```ruby
puts <<END + 'string'
blah blah
END
```

...We need to remember which line number we were on when lexing the opening `<<END`, restore it after the heredoc is lexed (so that `+` and `'string'` have the right line number), then bump the line number up again when jumping past the concluding `END`.

Or is there some other solution I haven't thought of?

**Comment by whitequark** [comment]
Given how annoyingly tricky and hard to test this is, I think we should go with caching of pos→line mapping inside `Source::Buffer`.

**Comment by alexdowad** [comment]
OK. But I almost have solution 1 working. I think I'll get *both* solutions working, then compare them for performance and readability. You can review both.
