### ISSUE TITLE
Large file: fatal: unterminated string meets end of file

### ISSUE THREAD

**Issue by mvidner** [whitequark/parser#266]
Thank you for Parser, it has been very useful!

A large input file, which is not too deep, fails to be parsed with this error message
```
fatal: unterminated string meets end of file
```
The file is about 1 megabyte in size, so instead of quoting it I made a generator for it: https://gist.github.com/mvidner/d1c803083dd6b156fb7b

 (BTW here is the [actual file](https://github.com/yast/yast-ycp-ui-bindings/blob/178884cba76ce4237e1ad716811b9ec2ace1fc00/examples/Tree-recursive-large.rb) I first found the problem on).

**Comment by whitequark** [comment]
Does it still happen if you get it under 1MB? If yes I know what broke, the UTF-32 hack... it uses a threshold of 1MB.

**Comment by whitequark** [comment]
BTW @alexdowad I was telling you these files exist in real life.

**Comment by mvidner** [comment]
If I decrease SIZE to 14000 it passes. Admittedly the real file is just a test for stressing our widget library so it's not a big deal.

**Comment by whitequark** [comment]
Nah it's a bug. Should be easy enough to bisect though if we reduce the threshold to like 1K.

**Comment by alexdowad** [comment]
@whitequark My latest PR fixes a known bug with the UTF-32 optimization. Perhaps we can clear that one first and see if @mvidner still has a problem or not?

**Comment by mvidner** [comment]
Ah, when I check out #265 and run `rake generate` it does indeed help!

**Comment by whitequark** [comment]
#265 was merged so closing. Tell me if you would like a release soon.

**Comment by alexdowad** [comment]
> Tell me if you would like a release soon.

In the words of Oliver Twist:

"Please, sir, may I have a point release?"

**Comment by whitequark** [comment]
`2.3.0.3`
