### ISSUE TITLE
Patch version specific parser files

### ISSUE THREAD

**Issue by jredville** [whitequark/parser#267]
The problems descirbed in #189 hit me pretty often, and often, even asking for a patch version update is a non-trivial request, especially when for many people parser is part of rubocop and is not a production requirement. Instead of just pointing people to the warning that MRI changes syntax in patch versions, would it be possible to start keeping the patch version parsers and loading the patch version specific parser?

**Comment by whitequark** [comment]
I'm not sure I understand. Are you suggesting I step up from maintaining eight parser forks (and countless hacks to avoid forking the lexer) and maintain, in amortized terms, ~3-4 times more of them?

**Comment by jredville** [comment]
First, after researching a little, I need to revise this discussion. I should have said `teeny` versions, not `patch` versions, as in `MAJOR.MINOR.TEENY`. `PATCH` appears to refer to the number of commits since the `TEENY` release. 

I guess I was under the impression that it would simply mean freezing the parser files when a new `TEENY` version is released. Does MRI also change the parser inside of `PATCH` version releases?

**Comment by whitequark** [comment]
Yes. Moreover, the worst changes are not to the parser but to the lexer, which we do not copy as it has various other dependencies such as the code used to parse literals, the changes that have to be made in sync with AST builder, the parsers themselves, etc. What you are asking for would create a combinatorial explosion in complexity and make testing and fixing bugs much more complicated, if tractable under my time constraints at all.

Instead, how about using older Parser versions on older MRI versions? I am specifically tying its version to the MRI version for this occasion, even if @bbatsov disapproves.

**Comment by jredville** [comment]
That seems reasonable. Would it make sense to include that in the documentation?

**Comment by whitequark** [comment]
Most of this is already described in https://github.com/whitequark/parser#compatibility-with-ruby-mri, what do you suggest to add?

**Comment by whitequark** [comment]
Please reopen if you have any specific suggestions about documentation.
