### ISSUE TITLE
Parser is extremely slow for files containing *any* unicode

### ISSUE THREAD

**Issue by nelhage** [whitequark/parser#268]
I ran into a bit of a nasty performance bug with the parser gem while trying to understand why `rubocop` was so slow on some of my source files. I'm genuinely unsure if there's a good solution, but I wanted to document it in an issue in case you had any thoughts.

`parser` relies heavily on taking slices of the source buffer at character offsets, most notably in `Parser::Lexer#tok` and `Parser::Source::Range#source`. However, if an input file contains *any* non-ASCII characters, Ruby implements character slices by walking the string codepoint-at-a-time, since it has to treat multibyte utf-8 sequences as a single character.

One one 1500-line source file, `ruby-parse FILE > /dev/null` takes 2.5s; If I remove the two lines containing unicode characters, it immediately speeds up to 700ms.

If I look at the performance using Linux's `perf` tool, we can see that about 75% of the time (on the unicode version) is spent on simple string operations:
```
 48.33%  ruby-parse  libruby.so.2.1.0    [.] str_strlen
 27.20%  ruby-parse  libruby.so.2.1.0    [.] str_utf8_nth
```

In addition to being slow in absolute terms, this behavior makes parser quadratic in file length, since it will be repeatedly seeking to location `n` in the file, for ranges of `n` ranging from 0 to `len(file)`, as it parses.

**Comment by whitequark** [comment]
Yes, yes, I know. There's a heuristic that transcodes the entire file into UTF-32 if it's larger than 1MB. The problem is, on relatively small mostly-ASCII files this makes it quite a bit slower. I have no idea what a good solution would look like.

**Comment by whitequark** [comment]
Is fast indexing for ASCII-only strings a silent optimization, i.e. is the encoding still UTF-8? We could try detecting that and transcoding if there's any non-ASCII but that might be costly already... I'm not sure.

**Comment by alexdowad** [comment]
We already have an array of codepoints in the lexer (`@source_pts`). Indexing into that is fast. If only there was a fast way to pull a subsequence of codepoints out and smash it together into a UTF-8 string...

**Comment by nelhage** [comment]
I believe that fast indexing for ASCII-strings is silent as you describe: MRI determines that a utf-8-encoded string is "actually" ASCII and does the optimization:

```
[nelhage@pragmatique:~]$ cat /tmp/strings.rb
# coding: utf-8
require 'benchmark'

N = 1000

s1 = ("x" * 1_000_000).force_encoding(Encoding::UTF_8)
s2 = ("x" * 1_000_000).force_encoding(Encoding::ASCII)
s3 = "\u2665" + ("x" * 1_000_000).encode(Encoding::UTF_8)

Benchmark.bm(20) do |b|
  b.report("utf-8, no high bits:") { N.times { s1[999_990...999_999] } }
  b.report("ascii") { N.times { s2[999_990...999_999] } }
  b.report("utf-8 with heart") { N.times { s3[999_990...999_999] } }
end
[nelhage@pragmatique:~]$ ruby /tmp/strings.rb
                           user     system      total        real
utf-8, no high bits:   0.000000   0.000000   0.000000 (  0.000334)
ascii                  0.000000   0.000000   0.000000 (  0.000191)
utf-8 with heart       0.340000   0.000000   0.340000 (  0.344256)
```

**Comment by alexdowad** [comment]
@nelhage Yep. See `single_byte_optimizable` in `string.c`.

**Comment by whitequark** [comment]
I guess we might as well detect if the input has any non-ASCII characters in it and always explode it into UTF-32 if it does.

**Comment by alexdowad** [comment]
> I guess we might as well detect if the input has any non-ASCII characters in it and always explode it into UTF-32 if it does.

Scan the codepoints array for anything which doesn't fit in 7 bits?

**Comment by alexdowad** [comment]
Internally, Ruby "knows" exactly which strings have multibyte characters and which don't... unfortunately, it doesn't seem to expose this information.

**Comment by nelhage** [comment]
I tried to test if forcing to UTF-32 would help my test case, but I'm getting exceptions from inside the lexer:

``` diff
diff --git a/lib/parser/lexer.rl b/lib/parser/lexer.rl
index 9d5869c..ae0428c 100644
--- a/lib/parser/lexer.rl
+++ b/lib/parser/lexer.rl
@@ -198,8 +198,9 @@ class Parser::Lexer
       end

       if @has_encode &&
-        (@source_pts.size > 1_000_000 || @force_utf32) &&
+        # (@source_pts.size > 1_000_000 || @force_utf32) &&
         @encoding != Encoding::UTF_32LE
+        $stderr.puts("forcing utf-32")
         # A heuristic: if the buffer is larger than 1M, then
         # store it in UTF-32 and convert the tokens as they're
         # going out. If it's smaller, the conversion overhead
```

```shell
[nelhage@pragmatique:~/stripe/parser]$ bundle exec bin/ruby-parse ~/stripe/pay-server/test/functional/api/token_creation.rb >/dev/null
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.8-compliant syntax, but you are running 2.1.5.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
forcing utf-32
Failed on: /Users/nelhage/stripe/pay-server/test/functional/api/token_creation.rb
/Users/nelhage/stripe/parser/lib/parser/lexer/literal.rb:190:in `extend_string': incompatible character encodings: UTF-8 and UTF-32LE (Encoding::CompatibilityError)
        from /Users/nelhage/stripe/parser/lib/parser/lexer.rb:16813:in `advance'
        from /Users/nelhage/stripe/parser/lib/parser/base.rb:219:in `next_token'
        from /Users/nelhage/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/racc-1.4.14/lib/racc/parser.rb:271:in `_racc_do_parse_c'
        from /Users/nelhage/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/racc-1.4.14/lib/racc/parser.rb:271:in `do_parse'
        from /Users/nelhage/stripe/parser/lib/parser/base.rb:162:in `parse'
        from /Users/nelhage/stripe/parser/lib/parser/runner/ruby_parse.rb:132:in `process'
        from /Users/nelhage/stripe/parser/lib/parser/runner.rb:202:in `process_buffer'
        from /Users/nelhage/stripe/parser/lib/parser/runner.rb:195:in `block in process_files'
        from /Users/nelhage/stripe/parser/lib/parser/runner.rb:181:in `each'
        from /Users/nelhage/stripe/parser/lib/parser/runner.rb:181:in `process_files'
        from /Users/nelhage/stripe/parser/lib/parser/runner.rb:159:in `block in process_all_input'
        from /Users/nelhage/.rbenv/versions/2.1.5/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
        from /Users/nelhage/stripe/parser/lib/parser/runner.rb:157:in `process_all_input'
        from /Users/nelhage/stripe/parser/lib/parser/runner/ruby_parse.rb:128:in `process_all_input'
        from /Users/nelhage/stripe/parser/lib/parser/runner.rb:33:in `execute'
        from /Users/nelhage/stripe/parser/lib/parser/runner.rb:11:in `go'
        from bin/ruby-parse:6:in `<main>'
```

**Comment by alexdowad** [comment]
@nelhage Are you using the new release which @whitequark cut earlier today?

There is a bugfix in that release which could be related.

**Comment by alex** [comment]
Does `String#ascii_only?` do what you want?

On Sat, Feb 6, 2016 at 1:32 PM, Alex Dowad <notifications@github.com> wrote:

> Internally, Ruby "knows" exactly which strings have multibyte characters
> and which don't... unfortunately, it doesn't seem to expose this
> information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whitequark/parser/issues/268#issuecomment-180830565>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by nelhage** [comment]
Ah, I was on `master` from yesterday. Updating to today, it works and my test case parses in ~900ms, which is a huge improvement vs the utf-8 version.

**Comment by whitequark** [comment]
See those 200ms? This is why UTF-32 is not always enabled.

**Comment by alexdowad** [comment]
> it works and my test case parses in ~900ms

*With* the patch which forces conversion to UTF-32, presumably.

**Comment by nelhage** [comment]
@alexdowad correct

**Comment by alexdowad** [comment]
> Does `String#ascii_only?` do what you want?

Hmm. Looking at the implementation, I can see it will return `false` in some cases where Ruby still does those silent optimizations.

**Comment by nelhage** [comment]
With this patch,

```
diff --git a/lib/parser/lexer.rl b/lib/parser/lexer.rl
index 5eaabe6..aaa7082 100644
--- a/lib/parser/lexer.rl
+++ b/lib/parser/lexer.rl
@@ -198,7 +198,7 @@ class Parser::Lexer
       end

       if @has_encode &&
-        (@source_pts.size > 1_000_000 || @force_utf32) &&
+        (!@source.ascii_only? || @force_utf32) &&
         @encoding != Encoding::UTF_32LE
         # A heuristic: if the buffer is larger than 1M, then
         # store it in UTF-32 and convert the tokens as they're
```

I get the speedup on the unicode test case, and retain performance on the ASCII one. Per above conversation it's not clear if that's exactly the right test, and it's possible there should still be a min-length check below which the conversion is never worth it.

**Comment by alexdowad** [comment]
Internally, Ruby has an encoding for each string, but it also has "code range" flags. The flags are: "unknown", "7-bit", "valid", and "broken".

`String#ascii_only?` just checks if the "7-bit" flag is on.

When checking whether it should use those silent optimizations or not, Ruby first checks if the "7-bit" flag is on, and if not, checks the encoding to see if it is an encoding which can *only* ever have 1-byte chars.

Say, for example, a string is in ASCII-8BIT. ASCII-8BIT strings always have 1 byte per char. So although it may contain chars which don't fit in 7 bits, those optimizations are still safe.

In our case, the source going into the lexer is always UTF-8. So `String#ascii_only?` is good enough. If we also handled ASCII-8BIT, we could test for it separately to avoid needlessly converting to UTF-32LE.

Thanks @alex!!

**Comment by alexdowad** [comment]
@nelhage Do you want to open a PR?
