### ISSUE TITLE
2.3.0.3 regression: Parser::CurrentRuby.parse("a @b do |c|;end")

### ISSUE THREAD

**Issue by rubys** [whitequark/parser#272]
I have some code that parses with 2.3.0.2, but fails with 2.3.0.3.  The workaround is easy and not a problem for me, but I thought I would report it.  You can see the previous code here and the change that works here:

https://github.com/apache/whimsy/commit/02b4fea409de0da36dd7f5260562263c60d029f5

**Comment by whitequark** [comment]
This is a very important bug. Thank you for reporting it.

**Comment by alexdowad** [comment]
The lexer is emitting `kDO` instead of `kDO_BLOCK`.

**Comment by alexdowad** [comment]
The culprit is the commit where I replaced `stack_pop` with Ragel's `fret`.

**Comment by whitequark** [comment]
Sigh. I was going to call that out as an invalid transformation, but completely forgot.

**Comment by alexdowad** [comment]
I thought I had checked and seen that the generated code was equivalent... ?? Just checking again.

**Comment by alexdowad** [comment]
Oh... I just noticed that `fret` inserts a `next` into the generated code.

**Comment by alexdowad** [comment]
Thanks for the fix, @whitequark.
