### ISSUE TITLE
Using Parser for a project

### ISSUE THREAD

**Issue by JoshCheek** [whitequark/parser#275]
Thought it'd be nice to share a use case. I teach, so made a game for students to analyze syntax, independently of analyzing code. It obviously needs some love, but it's playable and has lots of examples :) Currently, it works by entering a key or series of keys that correspond to the correct syntactic element within the code. They're ranked on how many they complete, how many they get incorrect, and how long it takes to complete one.

http://synseer.herokuapp.com

**Comment by whitequark** [comment]
Frankly I dislike like the approach. It seems to place huge focus on irrelevant syntactic trivia, as if Ruby wasn't bad enough by introducing all those heaps of syntactic junk. It feels much like a mechanized version of that reviled process where the interviewer asks you for things of no importance. This is like the complete opposite of the more academic approach that I prefer, which emphasizes abstract syntax and its mapping to semantics, and treats concrete syntax as an afterthought, which it really is...

Anyway, I don't have time or desire to police people on this. It's good that Parser worked for you, I guess? I figure your students can decide for themselves.

**Comment by JoshCheek** [comment]
:) I emphasize abstract syntax, as well. Not in an AST format, b/c they're only on their third week. We actually started with identifying various structures across languages, based on their properties (named values "hash", ordered values "array", text "string", etc) and then they [made up their own syntaxes](https://gist.github.com/JoshCheek/cee1930938310e865146) for these structures (my fav is the last one, b/c it represents most of the structures using syntax which typically means one of the other structures). 

Nonetheless, I think there is a lot of value to simply being able to categorize Ruby's syntax, because:

1. If they look at it and haven't seen it before, they historically are unable to even think about what it could mean.
2. I show them a lot of code and it's very valuable to be able to flash a screen of code at them, and say "see this thing here?" and they do see it. Otherwise it's like I have to give them several minutes to process what they're seeing before they are able to consider the one or two things I wanted to show them.
3. If they don't understand syntax, then they make things much more complex, creating extra magic in their heads. Require, private, attr_accessor all become magic keywords rather than methods operating on structures they can reason about. Operators become some beyond-message-passing capability that doesn't actually exist, which turns things like arrays (due to bracket access) into something the language provides that they can't create, etc. So by requiring them to categorize `1+1` as a method call, it strips the magic of `+`.
4. When they get a syntax error, they need to know how to fix it, and when the syntax says something other than what they mean, they need to be able to reason about why.

**Comment by whitequark** [comment]
Ack. I might just be biased since I've learned programming so long ago.

**Comment by troessner** [comment]
@JoshCheek I think it's cool!
