### ISSUE TITLE
Editing invalid files

### ISSUE THREAD

**Issue by JoshCheek** [whitequark/parser#281]
In older Parser (2.2.2.6), I could mess with its guts to get it to tell me where comments probably were, and then edit/delete them ([example](https://github.com/JoshCheek/seeing_is_believing/blob/00d0651b4ae2adce9e15c832aa503c69ef74f75a/lib/seeing_is_believing/code.rb#L93-L121)). In new Parser, it doesn't expect this (I haven't done much digging into how/why) and so this code explodes:

```
  1) SeeingIsBelieving::Code#root returns a null root for invalid code
     Failure/Error: _, all_comments, tokens = parser.tokenize(@buffer)

     TypeError:
       can't dup NilClass
     # ./bundle/ruby/2.3.0/bundler/gems/parser-08ad73329ae6/lib/parser/lexer/literal.rb:233:in `dup'
     # ./bundle/ruby/2.3.0/bundler/gems/parser-08ad73329ae6/lib/parser/lexer/literal.rb:233:in `coerce_encoding'
     # ./bundle/ruby/2.3.0/bundler/gems/parser-08ad73329ae6/lib/parser/lexer/literal.rb:124:in `nest_and_try_closing'
     # ./bundle/ruby/2.3.0/bundler/gems/parser-08ad73329ae6/lib/parser/lexer.rb:11320:in `advance'
     # ./bundle/ruby/2.3.0/bundler/gems/parser-08ad73329ae6/lib/parser/base.rb:219:in `next_token'
     # ./bundle/ruby/2.3.0/bundler/gems/parser-08ad73329ae6/lib/parser/base.rb:162:in `parse'
     # ./bundle/ruby/2.3.0/bundler/gems/parser-08ad73329ae6/lib/parser/base.rb:180:in `parse_with_comments'
     # ./bundle/ruby/2.3.0/bundler/gems/parser-08ad73329ae6/lib/parser/base.rb:201:in `tokenize'
     # ./lib/seeing_is_believing/code.rb:119:in `comments_and_tokens'
     # ./lib/seeing_is_believing/code.rb:30:in `initialize'
     # ./spec/code_spec.rb:7:in `new'
     # ./spec/code_spec.rb:7:in `code_for'
     # ./spec/code_spec.rb:38:in `block (3 levels) in <top (required)>'
```

I really liked the ability to do this, because it allowed me to add comments to the file, and then later, while editing, realize the comments were annoying, and have them removed, even though I was partway through the edit, thus the code was invalid ([example](https://github.com/JoshCheek/seeing_is_believing/blob/00d0651b4ae2adce9e15c832aa503c69ef74f75a/features/flags.feature#L224-L228)). I need to either remove this feature, or find a way around it, in order to fix https://github.com/JoshCheek/seeing_is_believing/issues/69

**Comment by whitequark** [comment]
Ah hm, this doesn't look right. Could you add the missing nil check (that probably should return nil) and also a test?

**Comment by whitequark** [comment]
Ah yes. I see your problem. The problem is that you're overriding `Diagnostic::Engine#process` to not raise on fatal errors. However, Parser, or rather, its small-p parser and lexer, _cannot_ recover from fatal errors. That's why they are fatal in the first place!

Fortunately, tokens can be returned even in case of unrecoverable errors.

**Comment by JoshCheek** [comment]
Got this working, ty.
