### ISSUE TITLE
Fails to parse method definition with `raise` arg

### ISSUE THREAD

**Issue by kayhide** [whitequark/parser#285]
Hi, I found somethings wrong when parsing ActiveRecord codes.

It fails to parse a code of method definition which:
- takes an arg with the name of `raise`
- raises a module-named error like `A::B`
- and raises with string message

ex)

```ruby
# raise.rb
def foo raise
  raise A::B, ''
end
```

It was working fine at the point of version 2.3.0.4.

```ruby
[1] pry(main)> Parser::VERSION
=> "2.3.0.4"
[2] pry(main)> Parser::CurrentRuby.parse_file('raise.rb')
=> s(:def, :foo,
  s(:args,
    s(:arg, :raise)),
  s(:send, nil, :raise,
    s(:const,
      s(:const, nil, :A), :B),
    s(:str, "")))
```

Now it fails with version 2.3.0.7.

```ruby
[1] pry(main)> Parser::VERSION
=> "2.3.0.7"
[2] pry(main)> Parser::CurrentRuby.parse_file('raise.rb')
raise.rb:3:17: error: unexpected token tNL
raise.rb:3:   raise A::B, ''
raise.rb:3:                 ^
Parser::SyntaxError: unexpected token tNL
from /Users/mikagami/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/parser-2.3.0.7/lib/parser/diagnostic/engine.rb:71:in `process'
```

This case is found here.
https://github.com/rails/rails/blob/v4.2.6/activerecord/lib/active_record/associations/collection_association.rb#L484

RUBY_VERSION is `2.2.4`.
Thanks.

**Comment by whitequark** [comment]
Dear lord. You know, I implemented all those obscure corners for completeness, not because I actually expected anyone to write code like that...

Anyway, I'll fix it once I find a minute.

**Comment by kayhide** [comment]
Thanks for your response.

Yes, I myself never put that kind of sensitive name for variables, and don't expect anyone do so, but some people do.
Actually I recently met a guy who wrote a code naming `throw` as a method name.
(That code was a simulation of throwing balls to strike some targets.)

Anything that can go wrong will go wrong...

**Comment by kayhide** [comment]
@whitequark 
I tried the new parser (2.3.1.0), and confirmed it parses as I expected.
Thanks!
