### ISSUE TITLE
Option to not dump warnings to stderr

### ISSUE THREAD

**Issue by chrismwendt** [whitequark/parser#286]
In many cases, the warnings about version-compliant syntax can be safely ignored, but parser doesn't seem to support disabling or handling them in any other way than to redirect stderr when `require`ing the gem. This has led me to an ugly workaround:

https://github.com/chrismwendt/autoargs/commit/474546cf29ba0e31a15bb641a0e5ecd83f7254f4

Here are a couple options:

- Add a parameter to `parse` which disables warnings
- Return a hash containing both the parse result and any warnings that were emitted

**Comment by whitequark** [comment]
> In many cases, the warnings about version-compliant syntax can be safely ignored, but parser doesn't seem to support disabling or handling them in any other way than to redirect stderr when requireing the gem.

Yes. This is deliberate and caused by Ruby's lack of a sane versioning policy with regards to syntax changes. The current behavior of Parser will not go anywhere until the upstream stops breaking syntax in minor and patch versions. It is annoying because it is designed to be so.
