### ISSUE TITLE
Can't parse metacharacters

### ISSUE THREAD

**Issue by iliabylich** [whitequark/parser#290]
Here's is the file I'm using for testing:
``` ruby
p ?\C-z
p ?\M-z
p ?\M-\C-z
```

Parser can parse only the first control character

// accidently clicked submit

**Comment by mbj** [comment]
Can you be more specific?

**Comment by iliabylich** [comment]
@mbj It seems that lexer should parse it according to [this](https://github.com/whitequark/parser/blob/1663bf85b9e08c4775c2d737c3a435199306e42e/lib/parser/lexer.rl#L739-L756) code, but for some reason it fails with `literal contains escape sequences incompatible with UTF-8`

**Comment by whitequark** [comment]
This is by design: https://github.com/whitequark/parser#invalid-characters-inside-comments-and-literals

**Comment by whitequark** [comment]
You can override the [string_value](https://github.com/whitequark/parser/blob/master/lib/parser/builders/default.rb#L1539-L1549) builder method to prevent this error, at your own risk.
