### ISSUE TITLE
Parser::AST::Processor modifies sexp

### ISSUE THREAD

**Issue by iliabylich** [whitequark/parser#298]
``` ruby
require 'ast'
require 'parser/ruby23'

sexp = Parser::Ruby23.parse("def m(a); end")
p sexp

processed = Parser::AST::Processor.new.process(sexp)
p processed
```
Output:
``` ruby
s(:def, :m,
  s(:args,
    s(:arg, :a)), nil)
s(:def, :m,
  s(:args,
    s(:arg, :a, nil)), nil)
```

`Processor` adds an extra `nil` to the end of any required argument. Should it be fixed? Wondering because it requires some breaking changes in `processor`

**Comment by whitequark** [comment]
That's a bug in `Processor`.

**Comment by iliabylich** [comment]
As far as I understand, `Processor` contains some legacy support, should I leave `on_argument` deprecated in favor of `on_required_argument/on_optional_argument`?

**Comment by whitequark** [comment]
```
@private
def on_argument(node)
  on_required_argument(node)
end
```

**Comment by iliabylich** [comment]
`:op_asgn`, `:and_asgn` and `:or_asgn` nodes have the same issue:
``` ruby
require 'ast'
require 'parser/ruby23'

sexp = Parser::Ruby23.parse("a &&= 1")
p sexp

processed = Parser::AST::Processor.new.process(sexp)
p processed
```
Output:
``` ruby
s(:and_asgn,
  s(:lvasgn, :a),
  s(:int, 1))
s(:and_asgn,
  s(:lvasgn, :a, nil),
  s(:int, 1))
```

I'll add a fix for these cases to https://github.com/whitequark/parser/pull/299
