### ISSUE TITLE
`else` in method / block, is omitted from AST, unless there is also a `rescue`

### ISSUE THREAD

**Issue by JoshCheek** [whitequark/parser#304]
Just hit this while exploring it to see if I could remove a flag in the method body to simplify the definition. Looked around and found the warning that Ruby would emit ([here](
https://github.com/whitequark/parser/blob/1e8b1f92eb6640e5f873bafcca31a2fc4054687b/lib/parser/messages.rb#L60)), which looks like it is identified ([here](
https://github.com/whitequark/parser/blob/1e8b1f92eb6640e5f873bafcca31a2fc4054687b/lib/parser/ruby18.y#L58)), and tested ([here](https://github.com/whitequark/parser/blob/1e8b1f92eb6640e5f873bafcca31a2fc4054687b/test/test_parser.rb#L4720-L4725)), but I don't see anything implying the AST omission is intentional.

```
$ ruby-parse   -e 'def a; else "b"; end'    -e 'def a; rescue; else "b"; end'
Using Parser::Ruby23 to parse 2 files.
(def :a
  (args) nil)
(def :a
  (args)
  (rescue nil
    (resbody nil nil nil)
    (str "b")))
```

**Comment by whitequark** [comment]
... hm. hah. I remember writing that in 2013; I was pretty convinced that "is useless" meant "never executes" rather than "always executes".
