### ISSUE TITLE
JRuby `Unhandled Java exception: org.jruby.RubyContinuation$Continuation`

### ISSUE THREAD

**Issue by JoshCheek** [whitequark/parser#305]
Debugged this down from my lib into Parser (possibly a Racc or JRuby issue?) at this point I'm a bit out of my depth. Figure I'll report it here since this is how far I got while working on https://github.com/JoshCheek/seeing_is_believing/issues/31

## Consider this code

```ruby
require 'parser/current'
p ruby: %x(ruby -v), parser: Parser::VERSION
buffer        = Parser::Source::Buffer.new('(string)')
buffer.source = "?\\M-a\n"
parser        = Parser::CurrentRuby.new
parser.diagnostics.all_errors_are_fatal = true # <-- comment this line
p parser.parse(buffer)
```

## With the line commented

JRuby raises "Unhandled Java exception: org.jruby.RubyContinuation$Continuation"

Note that this exception is especially painful, it pretty much just kills the program right there, no backtrace or anything.

```
$ ruby f2.rb
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.1-compliant syntax, but you are running 2.3.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Error opening script file: 9.1.2 (No such file or directory)
{:ruby=>"jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.71-b15 on 1.8.0_71-b15 +jit [darwin-x86_64]\n", :parser=>"2.3.1.2"}
Unhandled Java exception: org.jruby.RubyContinuation$Continuation
```

MRI returns `nil`.

```
$ ruby f2.rb
{:ruby=>"ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]\n", :parser=>"2.3.1.2"}
nil
```

## Without it commented

JRuby raises `Parser::SyntaxError`:

```
$ ruby f2.rb
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.1-compliant syntax, but you are running 2.3.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Error opening script file: 9.1.2 (No such file or directory)
{:ruby=>"jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.71-b15 on 1.8.0_71-b15 +jit [darwin-x86_64]\n", :parser=>"2.3.1.2"}
Parser::SyntaxError: literal contains escape sequences incompatible with UTF-8
           process at /Users/josh/.gem/jruby/2.3.0/gems/parser-2.3.1.2/lib/parser/diagnostic/engine.rb:71
        diagnostic at /Users/josh/.gem/jruby/2.3.0/gems/parser-2.3.1.2/lib/parser/builders/default.rb:1557
      string_value at /Users/josh/.gem/jruby/2.3.0/gems/parser-2.3.1.2/lib/parser/builders/default.rb:1542
         character at /Users/josh/.gem/jruby/2.3.0/gems/parser-2.3.1.2/lib/parser/builders/default.rb:147
       _reduce_435 at /Users/josh/.gem/jruby/2.3.0/gems/parser-2.3.1.2/lib/parser/ruby23.rb:5694
  _racc_do_parse_c at com/headius/racc/Cparse.java:709
          do_parse at /Users/josh/.rubies/jruby-9.1.2.0/lib/ruby/stdlib/racc/parser.rb:271
             parse at /Users/josh/.gem/jruby/2.3.0/gems/parser-2.3.1.2/lib/parser/base.rb:162
             <top> at f2.rb:7
```

MRI raises `Parser::SyntaxError`

```
ruby f2.rb
{:ruby=>"ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]\n", :parser=>"2.3.1.2"}
/Users/josh/.gem/ruby/2.3.1/gems/parser-2.3.1.2/lib/parser/diagnostic/engine.rb:71:in `process': literal contains escape sequences incompatible with UTF-8 (Parser::SyntaxError)
	from /Users/josh/.gem/ruby/2.3.1/gems/parser-2.3.1.2/lib/parser/builders/default.rb:1557:in `diagnostic'
	from /Users/josh/.gem/ruby/2.3.1/gems/parser-2.3.1.2/lib/parser/builders/default.rb:1542:in `string_value'
	from /Users/josh/.gem/ruby/2.3.1/gems/parser-2.3.1.2/lib/parser/builders/default.rb:147:in `character'
	from /Users/josh/.gem/ruby/2.3.1/gems/parser-2.3.1.2/lib/parser/ruby23.rb:5694:in `_reduce_435'
	from /Users/josh/.rubies/ruby-2.3.1/lib/ruby/2.3.0/racc/parser.rb:259:in `_racc_do_parse_c'
	from /Users/josh/.rubies/ruby-2.3.1/lib/ruby/2.3.0/racc/parser.rb:259:in `do_parse'
	from /Users/josh/.gem/ruby/2.3.1/gems/parser-2.3.1.2/lib/parser/base.rb:162:in `parse'
	from f2.rb:7:in `<main>'
```

**Comment by whitequark** [comment]
This used to be a known racc bug. all_errors_are_fatal was forcibly activated on non-MRI until 04829125a and de0510ea3. It seems that you've somehow found another instance of it...

cc @headius. is this a JRuby bug? a Racc bug? I'm not completely certain how the Java Racc works.

**Comment by alexdowad** [comment]
Works on JRuby 1.7.9. Installing 9.1.2.0 so I can have a look.

**Comment by whitequark** [comment]
Thanks, @alexdowad !

**Comment by alexdowad** [comment]
The error is happening in Racc's `parser.rb`, inside `yyerror`, at this line:

```ruby
throw :racc_jump, 1
```

Investigating a bit further...

**Comment by alexdowad** [comment]
There is a matching `catch` block in `parser.rb`, but the `throw` is not happening inside the matching `catch`. This should raise an `UncaughtThrowError`, but it doesn't.

**Comment by alexdowad** [comment]
OK, the throw is not happening inside the `catch` block in `parser.rb` for this reason: it's not using the pure-Ruby Racc engine, it's using `cparse-jruby.jar`.

**Comment by alexdowad** [comment]
Incidentally, when the pure-Ruby engine is used, this test case infinite-loops. Looks like @headius doesn't have my bugfix from racc@8e7b4de in JRuby's stdlib.

**Comment by alexdowad** [comment]
BTW -- although the Java Racc engine is being used, the pure-Ruby `#yyerror` from `parser.rb` is still being called. Perhaps it should be overridden with an appropriate Java implementation...?

**Comment by alexdowad** [comment]
I was wrong -- there's nothing to indicate that @headius is using Racc 1.4.14. Probably it's an older version.

**Comment by whitequark** [comment]
So why do I hit this? Parser explicitly requires a Racc 1.4.14 or newer, and Racc includes its own Java code.

**Comment by alexdowad** [comment]
The Racc runtime (just one particular file) is part of Ruby's stdlib and is bundled with Ruby. Parser requires the Racc gem, and its parser files are compiled using Racc 1.4.14. Those parser files still rely on the Racc runtime, though, and the Racc runtime which is bundled with JRuby is still being used.

**Comment by whitequark** [comment]
Triaged to https://github.com/jruby/jruby/issues/4071.
