### ISSUE TITLE
control flow and boolean operators produce the same AST

### ISSUE THREAD

**Issue by sumangurung** [whitequark/parser#316]
These produce the same AST:
1. && and `and`
2. || and `or`

```
irb(main):015:0> Parser::CurrentRuby.parse('foo and bar')
=> s(:and,
  s(:send, nil, :foo),
  s(:send, nil, :bar))
irb(main):016:0> Parser::CurrentRuby.parse('foo && bar')
=> s(:and,
  s(:send, nil, :foo),
  s(:send, nil, :bar))
irb(main):017:0> Parser::CurrentRuby.parse('foo or bar')
=> s(:or,
  s(:send, nil, :foo),
  s(:send, nil, :bar))
irb(main):018:0> Parser::CurrentRuby.parse('foo || bar')
=> s(:or,
  s(:send, nil, :foo),
  s(:send, nil, :bar))
```

There are differences in these pair of operators with regards to precedence and should produce different ASTs.

**Comment by whitequark** [comment]
> There are differences in these pair of operators with regards to precedence

Yes.

> and should produce different ASTs.

Why do you think so?

**Comment by sumangurung** [comment]
Converting it back to the source using unparser gem gives `and` and `or` instead of `&&`. Will this not be an issue if you have tool which modifies the AST and converts it back to ruby?

**Comment by whitequark** [comment]
As an exercise, try parsing `x or y and z` and then converting it back using unparser.

**Comment by sumangurung** [comment]
Hmmm.. This is what it gives back:
```
irb(main):046:0> Unparser.unparse(Parser::CurrentRuby.parse('x or y and z'))
=> "(x || y) && z"
```

But the light bulb in my head didn't light up. Could you please explain? 

I guess it is not an issue because it seems to do the right thing in this example:
```
irb(main):044:0> Unparser.unparse(Parser::CurrentRuby.parse('foo = bar  && baz'))
=> "foo = (bar && baz)"
irb(main):045:0> Unparser.unparse(Parser::CurrentRuby.parse('foo = bar and  baz'))
=> "(foo = bar) && baz"
```

In any case, feel free to tell me if this is not an issue. I haven't played around with the Ruby AST much, so I could be totally off.

**Comment by whitequark** [comment]
Basically, the ASTs Parser produces are semantic. They deliberately shed (almost) all syntactic information, since they are designed for analysis. `x || y && z` is parsed as `(or x (and y z))` whereas `x or y and z` is parsed as `(and (or x y) z)`, in both cases reflecting the precedence in the structure of the AST. Any tool that unparses the ASTs is obliged to produce something that would roundtrip; it could use `||`, `or`, or even a combination of both, it doesn't matter as long as it corresponds to the same AST.

**Comment by sumangurung** [comment]
Makes sense. Thanks for explanation.

**Comment by sumangurung** [comment]
By the way, do you know of any open source projects using the parser and unparser gems? I would love to know what they are using it and how they are using it?

**Comment by whitequark** [comment]
Here's the list of all gems using parser: https://rubygems.org/api/v1/gems/parser/reverse_dependencies.json

Some notable ones are rubocop and mutant.

**Comment by sumangurung** [comment]
Sweet, thanks. Did not know there was rubygems API for that.

**Comment by whitequark** [comment]
It's very carefully hidden.

**Comment by mbj** [comment]
@sumangurung Unparser is intentionally not producing the original source, its producing semantically equivalent source. Its mainly used for tools that need to generate ruby source code from AST, and is not optimized for human consumption, only for correctness. 

Generating a language like ruby that has many specialized nodes in a way its appealing for humans would be way more work.

**Comment by alexdowad** [comment]
@sumangurung Note also that `parser` does provide "source maps", which can be used to find the source text which any AST node was derived from. If you care about the difference between `||` and `or` (for example), you can extract the relevant bit of source text and do string equality/regex checks on it.

**Comment by sumangurung** [comment]
@mbj Makes sense. Thanks for taking the time to comment.

@alexdowad That is an interesting bit of info for me. Thanks, I will explore that path.
