### ISSUE TITLE
Ragel 7 drops support for Ruby

### ISSUE THREAD

**Issue by bbatsov** [whitequark/parser#317]
More info here - http://colm.net/news/2016/07/31/ragel-target-langs.html

Not sure what this means for parser - guess it can continue to use ragel 6.x for the foreseeable future. Still, that's one unfortunate development...

**Comment by whitequark** [comment]
Yes. That or we make a hostile fork of Ragel.

**Comment by rmosolgo** [comment]
I'm also heavily invested in Ragel's Ruby backend. Turns out that 7.0.0.9 _does_ include Ruby output and its performance is better (https://github.com/rmosolgo/graphql-ruby/pull/737).

Just thought I'd mention it here so that, if there is a fork, I can stay in the loop! I don't understand Ragel's finer points (yet?) but I love string processing, so I'm interested in keeping up with the project if it happens.

**Comment by whitequark** [comment]
@rmosolgo @bbatsov @YorickPeterse time for a fork of Ragel based on 7.0.0.9? I for one would be in favor of that.

**Comment by bbatsov** [comment]
I'm in favour of the idea, but lately my work have eaten up my time for OSS work and I can't really offer much help with that.

**Comment by rmosolgo** [comment]
I'm afraid I'm in the same boat: I want to make sure our dependency doesn't ruin us, but I don't really _need_ to fork it yet and I don't think I can make enough time to learn how it works well enough to contribute in a valuable way :S

**Comment by whitequark** [comment]
Right--I personally have basically ceased work on Parser beyond reviewing PRs as well... I might have to use Ragel with Rust at work at some point though so then I may revisit the idea.

**Comment by YorickPeterse** [comment]
@whitequark For my Rust work I opted to just write any lexers by hand. It's not exactly pleasant at times, but it solves the problem of Ragel only focusing on C/C++ starting with version 7.0. I did recently see the Ragel author tweet about thinking of re-adding other backends through some sort of plugin system, but it's not clear if this is actually planned or merely an idea.

**Comment by YorickPeterse** [comment]
It's also worth mentioning that some versions of the 7.0 branch have some bugs. The GitHub repositories are gone once again so I can't link to them, but IIRC they involved `fnext` or `fcall` (one of the two) not working when defining certain machines.

**Comment by bbatsov** [comment]
> Right--I personally have basically ceased work on Parser beyond reviewing PRs as well... I might have to use Ragel with Rust at work at some point though so then I may revisit the idea.

@whitequark I think it might be a good idea to mention this in the README and add a note there that the project is looking for more maintainers.

**Comment by bbatsov** [comment]
A problem that solves itself http://www.colm.net/news/2018/05/18/new-target-langs.html

**Comment by junaruga** [comment]
I faced following error using ragel 7.0.0.12 for `puma/puma` project. Do you have any idea to fix this? The detail is https://github.com/puma/puma/issues/2207 . Thank you.

```
$ ragel ext/puma_http11/http11_parser.rl -R -G2 -I ext/puma_http11 -o ext/puma_http11/http11_parser.c
ragel: -R is an invalid argument
```

**Comment by whitequark** [comment]
The workaround is to use Ragel version 7.0.0.9.

**Comment by junaruga** [comment]
Sure. Thank you for your response.
