### ISSUE TITLE
Proper way to use assign_properties on Node?

### ISSUE THREAD

**Issue by mckaz** [whitequark/parser#324]
I'm trying to work out how to use assign_properties for a Node in the ast. It looks like Parser::AST::Node defines its own assign_properties method which only sets the node location.

I've tried to override this method with a definition that assigns an instance variable for each entry in the properties hash, i.e., exactly what is done in the AST::Node class: https://github.com/whitequark/ast/blob/master/lib/ast/node.rb

However, when I try to use this method, I get a runtime error that I can't modify a frozen Node.

So, how can we reconcile immutable nodes with the attempt of assign_properties to define instance variables? What is the proper way to use assign_properties?

**Comment by whitequark** [comment]
But Parser doesn't pass any properties except `location`.

Anyway, can you show your code?

**Comment by mckaz** [comment]
I'd like to tag each expression in a generated AST with the class to which the expression belongs. As a simple example, given the sexp:
`s(:send, s(:int, 2), :+, s(:int, 2))`

I want to tag each `s(:int, 2)` with the class `Fixnum`, and the entire expression with the class `Fixnum`. So I'd like to be able to say something like `sexp.assign_poperties(klass: Fixnum)`.

Is there a straightforward way to tag nodes in an AST with properties like this? Or is doing so simply not allowed since the nodes are frozen?

**Comment by whitequark** [comment]
> Is there a straightforward way to tag nodes in an AST with properties like this? Or is doing so simply not allowed since the nodes are frozen?

Depending on what exactly you're doing, one of the following will make sense:
  * `node.update(nil, nil, {klass: Fixnum})`;
  * `node_classes[node] = Fixnum` (since two `s(:int, 1)` nodes always compare and hash equal, even if they have different source location);
  * transform Parser nodes into your own nodes that have some additional context using an `AST::Processor`.

**Comment by mckaz** [comment]
Thank you! I'll look into using one of these approaches.
