### ISSUE TITLE
Ruby 2.3.2 release

### ISSUE THREAD

**Issue by matthewrudy** [whitequark/parser#326]
This is not super urgent.

But with the latest parser release we get warnings when using ruby 2.3.2

```
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.1-compliant syntax, but you are running 2.3.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

I think a 2.3.2 compatible release could easily be done.

But I think in reality a patch release shouldn't affect syntax, si actually the warning shouldn't be there.

**Comment by whitequark** [comment]
> But I think in reality a patch release shouldn't affect syntax, si actually the warning shouldn't be there.

You would *think* this is true, but no, in fact Ruby often alters syntax in patch versions: https://github.com/whitequark/parser#compatibility-with-ruby-mri.

Such a release is blocked on #307 and #319. I will fix this soon.

**Comment by matthewrudy** [comment]
@whitequark thanks for the rapid response.

**Comment by whitequark** [comment]
The release isn't actually blocked by those issues, since they weren't backported to 2.3.2. I've released 2.3.2.0.

**Comment by matthewrudy** [comment]
thanks @whitequark

**Comment by igorkasyanchuk** [comment]
Whi wants to disable warning: 

nano /usr/local/rvm/gems/ruby-2.6.1/gems/parser-2.6.0.0/lib/parser/current.rb
comment lines: https://github.com/whitequark/parser/blob/11e9e345446f3c77aefaf142b97f7f09fab33a39/lib/parser/current.rb#L6-L8
