### ISSUE TITLE
ruby/ruby@80045bc + ruby/ruby@7e8b910

### ISSUE THREAD

**Issue by whitequark** [whitequark/parser#330]
See https://github.com/ruby/ruby/commit/80045bc2a9e12012d6d16517ea5cb037e67eb2c1.

**Comment by JoshCheek** [comment]
Would this one fall under https://github.com/whitequark/parser/issues/328#issuecomment-264353903

If so, can you describe what it would take to close the issue, or link me to a similar one I can use as a reference?

My guess: add a test showing that it parses the spacing on 2.4 (maybe nearby [this](https://github.com/whitequark/parser/blob/ecbdf65442abe8c1d24dfa28e472189a1156a155/test/test_parser.rb#L5143-L5149) test, or maybe add it to lexer tests), but not older Rubies. Then fix it to allow the spacing on 2.4, somewhere around [here](https://github.com/whitequark/parser/blob/ecbdf65442abe8c1d24dfa28e472189a1156a155/lib/parser/lexer.rl#L733-L743).

**Comment by whitequark** [comment]
@JoshCheek Actually, yes!

> add a test showing that it parses the spacing on 2.4 (maybe nearby this test, or maybe add it to lexer tests

This is just a lexer feature, so yes. I usually copy the MRI tests nearly verbatim, with minimal necessary adjustment to the Parser testsuite.

> Then fix it to allow the spacing on 2.4, somewhere around here.

Yup.

This particular case is a bit odd because we cannot easily branch on Ruby version in the lexer rules. So, I think an easy (although somewhat dirty) way to fix it is as follows: add a copy of the Unicode lexing rules under the existing ones; change them to accept multiple whitespace characters in a row; and add a fatal diagnostic like the one that's already there. In this way, old-style literals will trigger the old rules, and new-style literals will trigger the new rules, which will error out on old Ruby targets.

**Comment by whitequark** [comment]
Also ruby/ruby@7e8b910.

**Comment by iliabylich** [comment]
Looks like an issue with zero codepoints is not fixed. The test was removed in https://github.com/ruby/ruby/commit/7e8b910, but it still passes:
``` sh
$ ./ruby -v test.rb

```

**Comment by whitequark** [comment]
Depressing.

**Comment by iliabylich** [comment]
Fixed in upstream in https://github.com/ruby/ruby/commit/50702d16ab5862413351520b65da820194dbf8d7 but not ported yet to 2.4 / 2.5 branches
