### ISSUE TITLE
ruby24.rb loops forever upon initial load

### ISSUE THREAD

**Issue by flajann2** [whitequark/parser#335]
Ruby 2.3.3 or Ruby 2.2.6, Ubuntu 16.10, 8-core AMD, 32GB RAM using rbenv to manage rubies.

Code snippet from parser where the "infinite" looping occurs https://gist.github.com/flajann2/9ad496a7965cc07a97352c10b2978da5

In RubyNEAT https://github.com/flajann2/rubyneat/tree/v1.0.0

Trace code located in https://github.com/flajann2/rubyneat/blob/v1.0.0/lib/rubyneat.rb

To reproduce:
   clone rubyneat,
   git checkout v1.0.0
   bundle install
   rake install
   neat

With and without the trace code, I've let it run for several minutes and it never appears to get out of this loop.

Any helpful hints would be greatly appreciated. A fix would even be more appreciated. Your code is critical to my being able to generate ASTs of the neural nets so that they can be, in theory, "compiled" in any language and run at scale.

I am working on this code during a short break in between "real" jobs, so the sooner you can give me input, the better. I greatly appreciate what you've done here. May thanks.

**Comment by whitequark** [comment]
It would help if your repository wasn't *dozens of megabytes* in size. I have like 8Mbps of downlink here.

**Comment by whitequark** [comment]
This is not a bug in Parser. You have some gem that reloads your code in a loop. To see what I mean, try this: 
  * run `bundle exec ./bin/neat`
  * without stopping the command, add `print(1)` to `lib/rubyneat.rb` at the end
  * the command starts to repeatedly print 1

This means that all of your require's succeed (including Parser's, which you can verify by adding an explicit `require 'parser/ruby24'`, and then are re-required.

**Comment by flajann2** [comment]
Thanks for taking a look at this. Hmmmm... I thought require was only supposed to acquire once and only once. OK, I have some ideas on what may be happening. Thanks again.

**Comment by whitequark** [comment]
> Hmmmm... I thought require was only supposed to acquire once and only once.

That's how it works. However if you clear the `$LOADED_FEATURES` special variable, `require` will think it hasn't loaded anything. One of your gems is doing that.

**Comment by flajann2** [comment]
I see. And it will be a lot of fun tracing this down.

**Comment by whitequark** [comment]
http://nithinbekal.com/posts/ruby-trace-var/

**Comment by flajann2** [comment]
All works now. Thanks for your help.
