### ISSUE TITLE
parser/current is loading parser/ruby24, which recognizes warning: HEAD-compliant syntax

### ISSUE THREAD

**Issue by mindseyeblind** [whitequark/parser#338]
I'm using Atom with a bunch of linters, including linter-haml which is a wrapper for the `haml_lint` gem, and I keep getting the following error (nothing actually breaks, but I keep getting popups whenever I save a HAML page).

````
Error: warning: parser/current is loading parser/ruby24, which recognizes warning: HEAD-compliant syntax, but you are running 2.4.0. warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
````

How did I manage to mess this up? I don't think `warning: HEAD` is a valid ruby version...

**Comment by whitequark** [comment]
Fixed in version 2.4.0.0.
