### ISSUE TITLE
Warning parser/current is loading parser/ruby22

### ISSUE THREAD

**Issue by RatedR92** [whitequark/parser#340]
Hello, 

I'm new to ruby, I'm installing phishing-frenzy but when I execute the command $ rake db:seed
an error shows up saying that I have to install parser, when parser installed (version 2.4.0.0) another error shows up 

warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2-compliant syntax, but you are running 2.3.1.

My Ruby version is 2.3.1 
My parser version is 2.4.0.0.
(I don't know why parser is loading from ruby22 which is not even installed in my computer)

I searched for some similar issues, the recommanded solution was to change some lines in **lib/parser/current.rb**  but didn't find such path in my computer to change current.rb

Any help would be appreciated.

**Comment by whitequark** [comment]
Run `bundle update parser` in phishing-frenzy. If this doesn't help, report a bug against phishing-frenzy.
