### ISSUE TITLE
Parser does not distinguish between attribute assignments and method sends

### ISSUE THREAD

**Issue by charliesome** [whitequark/parser#341]
In Ruby attribute assignments have subtly different semantics to method sends to the same method:

```ruby
>> class A
 |   def []=(_)
 |     456
 |   end
 | end
=> :[]=
>> A.new[] = 123
=> 123
>> A.new.[]=(123)
=> 456
```

Parser does not distinguish between these two cases:

```
λ ruby-parse -e '$a[] = 123'
(send
  (gvar :$a) :[]=
  (int 123))
λ ruby-parse -e '$a.[]=(123)'
(send
  (gvar :$a) :[]=
  (int 123))
```

By comparison, MRI uses `NODE_ATTRASGN` for the first example, and `NODE_CALL` for the second:

<details>

    λ ruby --dump=parsetree -e '$a[] = 123'
    ###########################################################
    ## Do NOT use this node dump for any purpose other than  ##
    ## debug and research.  Compatibility is not guaranteed. ##
    ###########################################################

    # @ NODE_SCOPE (line: 1)
    # +- nd_tbl: (empty)
    # +- nd_args:
    # |   (null node)
    # +- nd_body:
    #     @ NODE_PRELUDE (line: 1)
    #     +- nd_head:
    #     |   (null node)
    #     +- nd_body:
    #     |   @ NODE_ATTRASGN (line: 1)
    #     |   +- nd_recv:
    #     |   |   @ NODE_GVAR (line: 1)
    #     |   |   +- nd_entry: :$a
    #     |   +- nd_mid: :[]=
    #     |   +- nd_args:
    #     |       @ NODE_ARRAY (line: 1)
    #     |       +- nd_alen: 1
    #     |       +- nd_head:
    #     |       |   @ NODE_LIT (line: 1)
    #     |       |   +- nd_lit: 123
    #     |       +- nd_next:
    #     |           (null node)
    #     +- nd_compile_option:
    #         +- coverage_enabled: false

    λ ruby --dump=parsetree -e '$a.[]=(123)'
    ###########################################################
    ## Do NOT use this node dump for any purpose other than  ##
    ## debug and research.  Compatibility is not guaranteed. ##
    ###########################################################

    # @ NODE_SCOPE (line: 1)
    # +- nd_tbl: (empty)
    # +- nd_args:
    # |   (null node)
    # +- nd_body:
    #     @ NODE_PRELUDE (line: 1)
    #     +- nd_head:
    #     |   (null node)
    #     +- nd_body:
    #     |   @ NODE_CALL (line: 1)
    #     |   +- nd_mid: :[]=
    #     |   +- nd_recv:
    #     |   |   @ NODE_GVAR (line: 1)
    #     |   |   +- nd_entry: :$a
    #     |   +- nd_args:
    #     |       @ NODE_ARRAY (line: 1)
    #     |       +- nd_alen: 1
    #     |       +- nd_head:
    #     |       |   @ NODE_LIT (line: 1)
    #     |       |   +- nd_lit: 123
    #     |       +- nd_next:
    #     |           (null node)
    #     +- nd_compile_option:
    #         +- coverage_enabled: false

</details>

**Comment by whitequark** [comment]
D: D:

**Comment by whitequark** [comment]
To outline the work that needs to be done...
  1. [These two nodes](https://github.com/whitequark/parser/blob/master/doc/AST_FORMAT.md#to-attribute) should be changed to `sendasgn` and `csendasgn`.
  2. The change should be gated on an [AST compatibility flag](https://github.com/whitequark/parser/blob/master/lib/parser/builders/default.rb#L25-L41).
  3. The [README intro section](https://github.com/whitequark/parser#usage) should be modified to set the AST compatibility flag to true.
  4. Tests tests tests

I provide no ETA for this. PRs welcome!

**Comment by whitequark** [comment]
So... after further experimentation, looks like this affects *only* this case with `[]=`? Christ. What a horrible language.

**Comment by charliesome** [comment]
🙇

What a gnarly bug :\
