### ISSUE TITLE
Lvar discrepancy / question 

### ISSUE THREAD

**Issue by dancinglightning** [whitequark/parser#343]
In trying to understand the output while using this (for https://github.com/ruby-x/rubyx )

The docs (https://github.com/whitequark/parser/blob/master/doc/AST_FORMAT.md) say about :lvar
(:lvar foo)  -->  "foo"

But (off course) when parsing "foo" i get `s(:send, nil, :foo)`
So in wondering how to generate an :lvar (or when the parser generates one) i read the test.
In test_parser line 2878, "foo.fun" is parsed and tested against `s(:send, s(:lvar, :foo), :fun)`

But when i parse foo.fun with ruby-parse, i get `s(:send,  s(:send, nil, :foo), :fun)` , again sort off "off course". 
Because how can one know if it is a local or a method without a previous assignment (ie method analysis). So i am wondering if i am misunderstanding something here, or is the test wrong. And when does the parser actually generate an :lvar

Great work btw, 
Torsten

**Comment by mbj** [comment]
You need to have an lvar assignment in the same lvar scope visible to the parser.

**Comment by dancinglightning** [comment]
thanks @mbj , good to know the parser does that analysis already.
I guess a note on the ast docs would clear that up.
And since the tests obviously pass, everything seems fine
