### ISSUE TITLE
Ruby 2.3.4 Release

### ISSUE THREAD

**Issue by aselder** [whitequark/parser#344]
Similar to https://github.com/whitequark/parser/issues/326, we're getting a warning when running Ruby 2.3.4.

```
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.3-compliant syntax, but you are running 2.3.4.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

**Comment by ACPK** [comment]
+ 1

**Comment by bbatsov** [comment]
@aselder see https://github.com/whitequark/parser/issues/317#issuecomment-304316789 and #342

**Comment by jamescgibson** [comment]
:+1: 

Given that it appears the recent vulnerability reported in RubyGems [1] will only be fixed on 2.3.4 and 2.4.1 and above, this issue would be more important than before - if nobody is already working on it, happy to take a crack at it, though I'm totally new to the library.

**Comment by segiddins** [comment]
@jamescgibson not entirely true, all the fixes are available in RubyGems 2.6.13

**Comment by jamescgibson** [comment]
@segiddins Thanks!

**Comment by mattyb** [comment]
2.3.5 is now released, including 4 CVE patches
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/

**Comment by Victorcorcos** [comment]
So, how to fix this issue?
