### ISSUE TITLE
Plus(+) becomes an unary operator without white space between operator and parameter

### ISSUE THREAD

**Issue by kandadaboggu** [whitequark/parser#350]
I ran in to bug while trying to parse a simple ruby code string. The parser treats `+` as an unary operator when it is followed by a string literal without whitespace in between.

Setup a variable called `x`

```
2.3.3 :008 > x = "hello"
=> "hello"
```

**With space between operator and parameter:**

```
2.3.3 :009 > code = 'x + "world"'
 => "x + \"world\""
2.3.3 :010 > Parser::Ruby23.parse(code)
 => s(:send,
  s(:send, nil, :x), :+,
  s(:str, "world"))
```

Eval of the `code` string gives the expected answer:
```
2.3.3 :011 > eval(code)
 => "helloworld"
```

**Without space between operator and parameter:**

```
2.3.3 :012 > code = 'x +"world"'
 => "x +\"world\""
2.3.3 :013 > Parser::Ruby23.parse(code)
 => s(:send, nil, :x,
  s(:send,
    s(:str, "world"), :+@))
```

Eval of the `code` string gives the expected answer:
```
2.3.3 :014 > eval(code)
 => "helloworld"
```

_I am using `parser` gem version (2.4.0.0)._

**Comment by whitequark** [comment]
Not a bug. Add the assignment to `x` to parsed code as that charges internal parser state.

**Comment by kandadaboggu** [comment]
@whitequark `x` in my case is a function.

**Comment by whitequark** [comment]
Then Parser's behavior matches Ruby's:
```
[1] pry(main)> def x(y) y end
=> :x
[2] pry(main)> x +"world"
=> "world"
```

**Comment by kandadaboggu** [comment]
@whitequark I agree this is not an issue related to`parser` gem.
