### ISSUE TITLE
Source map of `kwbegin` doesn't contain `keyword` loc

### ISSUE THREAD

**Issue by Drenmi** [whitequark/parser#357]
Currently, `kwbegin` nodes are mapped using `Source::Map::Collection`, which doesn't have a `keyword` loc. It should potentially be mapped using `Source::Map::Keyword` instead. The latter seems to be a superset of the former, so this would most likely not be a breaking change.

For context, in RuboCop, we inspect the indentation of the `end` keyword relative to the opening keyword for nodes where it is applicable, and we'd like to treat all "keyword + end" pairs the same.

**Comment by whitequark** [comment]
Sure. Could you make a PR?

**Comment by Drenmi** [comment]
Sure can! I don't know when I'll have time to dig into it, but I guess I'm the only one waiting for this, anyway. ;-)

**Comment by whitequark** [comment]
On second look I don't think this is necessary, the source map has the `begin` and `end` components, which are sufficient:
```
$ ./bin/ruby-parse -e 'begin 1 end' -L
s(:kwbegin,
  s(:int, 1))
begin 1 end
        ~~~ end
~~~~~ begin
~~~~~~~~~~~ expression
s(:int, 1)
begin 1 end
      ~ expression
```

**Comment by Drenmi** [comment]
It does indeed satisfy it. The problem I was having was that this isn't polymorphic with other keyword nodes that are treated similarly by our indentation cops. I guess I can always patch alias it on our end. 🙂

**Comment by Drenmi** [comment]
We now have a [monkey patch](https://github.com/rubocop-hq/rubocop/pull/7337/files#diff-60af7388d983043183278aa513732f82R8) in `master` for this:

```ruby
Parser::Source::Map::Collection.send(:alias_method, :keyword, :begin)
```

Is it enough to reconsider this?

**Comment by whitequark** [comment]
I'm not sure why a hack being added in Rubocop should justify any changes in Parser. There has never been any reason to add that monkey patch to begin with; all else being equal, if you don't like how any of the nodes are constructed, you can always inherit from `Parser::Builders::Default` and override the appropriate node constructor.
