### ISSUE TITLE
warning: assigned but unused variable

### ISSUE THREAD

**Issue by lloeki** [whitequark/parser#360]
When running tests on a project depending on parser some warnings from parser's code are raised (see below).

This is because with a recent rake (>=11.0), ruby warnings are now on by default.

What do you think about fixing those warnings as well as running the test suite with `ruby -w` / `$VERBOSE = true` / `t.warning = true` ? Also, what is the rationale behind [this line](https://github.com/whitequark/parser/blob/5e30b19b702012f79a1d93e37de1717c2c961ec9/Rakefile#L12)?

```
/Users/lloeki/.gem/ruby/2.3.4/gems/parser-2.4.0.0/lib/parser/lexer.rb:10922: warning: assigned but unused variable - testEof
```

**Comment by whitequark** [comment]
Sure I'll merge a PR fixing that. And I have no recollection of that, feel free to remove.

**Comment by iliabylich** [comment]
@whitequark @lloeki This warning seems to come from the code generated by ragel.

**Comment by mbj** [comment]
We have discussed this warning from the earliest days on. The 2 possible ways forward I recall are:

* Fix ragel to not emit this variable when its not used (AFAIK some currently unused ragel features may trigger its use)
* Rewrite the generated source code to remove the assignment.

**Comment by whitequark** [comment]
Not considered major enough to fix, `-w` is nearly useless anyway. PRs that fix this in non-invasive ways still accepted.
