### ISSUE TITLE
__ENCODING__ parses differently from other constants

### ISSUE THREAD

**Issue by ABaldwinHunter** [whitequark/parser#369]
I'm working on a project that uses the parser and noticed that `__ENCODING__` gets parsed as a constant but has a difference in location type from other constant asts with its shape:

```
# AST looks similar for __ENCODING__ and some constant like Foo::Bar or Encoding::UTF_8
Parser::CurrentRuby.parse("__ENCODING__")
=> s(:const,
  s(:const, nil, :Encoding), :UTF_8)

Parser::CurrentRuby.parse("Encoding::UTF_8")
=> s(:const,
  s(:const, nil, :Encoding), :UTF_8)


# But node location property different
Parser::CurrentRuby.parse("__ENCODING__").location.class
=> Parser::Source::Map

Parser::CurrentRuby.parse("Encoding::UTF_8").location.class
=> Parser::Source::Map::Constant


# And children locations different
Parser::CurrentRuby.parse("__ENCODING__").children.first.location
=> nil

Parser::CurrentRuby.parse("Encoding::UTF_8").children.first.location
=> #<Parser::Source::Map::Constant:0x007f8f3d865af0 @name=#<Parser::Source::Range (string) 0...8>, @double_colon=nil, @expression=#<Parser::Source::Range (string) 0...8>, @node=s(:const, nil, :Encoding)>
```
I'm curious: are those differences intentional? What's the thinking behind not parsing `__ENCODING__` as a constant like `FOO`?

No rush. Thanks for working on this great tool!

For ref see https://github.com/whitequark/parser/pull/368 first opened

**Comment by whitequark** [comment]
You need an AST format opt-in. Please look at how `Parser::Builders::Default.emit_lambda` and `emit_procarg0` are implemented. Then do the same for `__ENCODING__`. Let me know if you have any questions.

**Comment by ABaldwinHunter** [comment]
Thanks for your reply! Taking a look at those examples

**Comment by ABaldwinHunter** [comment]
🎉  thank you
