### ISSUE TITLE
Error parsing "+42"

### ISSUE THREAD

**Issue by marcandre** [whitequark/parser#384]
I believe the parsing of "+42" is erroneous:

```
$ ruby-parse -L -e "+42"
s(:int, 42)
+42
 ~~ expression
```

I believe result should be:
```
+42
~~~ expression
```

There's actually already a test for the lexer that seems wrong. It was added with a bunch of other similar modifications in 85ec5bf9076af3cb, so I expect it wasn't actually intentional.

Here's [a fix for the specs](https://github.com/marcandre/parser/commit/da9d801a3f8afb526bfcdb98dcac1c32e04ce043), I wish I could also provide a fix for the actual issue...

**Comment by marcandre** [comment]
Note that in the case of `-42`, parser also outputs an "operator" map pointing to the `'-'`. I don't have an opinion on if there should be an operator in the case of `+42` and it won't have any impact for me.
The current `expression` has an impact though as I'm attempting to insert code before the `expression` which in this case means I'm inserting code between the `+` and the `42`...

**Comment by whitequark** [comment]
Nice, you even pointed me to another latent bug.
