### ISSUE TITLE
Should Comment::Associator ignore frozen_string_literal?

### ISSUE THREAD

**Issue by ddfreyne** [whitequark/parser#386]
I believe that the `skip_directives` attribute on `Comment::Associator` should also ignore the `frozen_string_literal` directive.

Given

```ruby
require 'parser/current'

ast, comments = Parser::CurrentRuby.parse_with_comments(<<-CODE)
# frozen_string_literal: true

def hi
end
CODE

p Parser::Source::Comment.associate(ast, comments)
```

… then the output is

```
{
  s(:def, :hi, s(:args), nil) =>[
    #<Parser::Source::Comment (string):1:1 "# frozen_string_literal: true">
  ]
}
```

… but _should_ be (I believe) empty.

I couldn’t find any other mention of this in the source code, commits or issues, so I don’t think this has come up before.

**Comment by ddfreyne** [comment]
(Happy to provide a PR if you agree that this should change.)

**Comment by whitequark** [comment]
Looks good to me.
