### ISSUE TITLE
Difference between Parser and Ruby interpreter

### ISSUE THREAD

**Issue by Confusion** [whitequark/parser#418]
Code:
````
puts({
=begin
  x: 1,
=end
  y: 2
})
````
`ruby the_code_above.rb` prints `{:y=>2}`

`Parser::CurrentRuby.parse(File.read('the_code_above.rb'))` results in
````
(string):5:4: error: unexpected token tCOLON
(string):5:   y: 2
(string):5:    ^  
Parser::SyntaxError: unexpected token tCOLON
````

(the `puts` is just for demonstration purposes: without the `puts` and the parentheses the Ruby interpreter still accepts the code, while Parser gives the same error)

(tested using MRI 2.2.5, Parser 2.4.0.2)

**Comment by whitequark** [comment]
Good catch.
