### ISSUE TITLE
unexpected token tLCURLY at 2.5.0.2

### ISSUE THREAD

**Issue by k0uki** [whitequark/parser#454]
- 2.5.0.2 produces unexpected token tLCURLY
- 2.4.0.2 does not

## Reqproduction

```
ruby-parse -e 'm :a {}'
(fragment:0):1:6: error: unexpected token tLCURLY
(fragment:0):1: m :a {}
(fragment:0):1:

ruby -ce "m :a {}"
Syntax OK
```

**Comment by iliabylich** [comment]
@k0uki Which version of Ruby do you use? This syntax is invalid (`m :a {}` is `m(:a {})`):
``` bash
$ ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]
-e:1: syntax error, unexpected '{', expecting end-of-input
m :a {}
      ^

$ ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
-e:1: syntax error, unexpected '{', expecting end-of-input
m :a {}
     ^
```

There was a bug in some version of 2.4.x that allows this syntax, but it's fixed now (and backported to the `parser` gem). 

@whitequark Probably we need to bump 2.4 branch in `parser/current` (it points to `2.4.0` atm)

**Comment by k0uki** [comment]
I use Ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

m :a {} is m(:a) {} in 2.4.1

```
Ripper.sexp('m :a {}')
=> [:program, [[:method_add_block, [:command, [:@ident, "m", [1, 0]], [:args_add_block, [[:symbol_literal, [:symbol, [:@ident, "a", [1, 3]]]]], false]], [:brace_block, nil, [[:void_stmt]]]]]]
```

But  2.4.3  is m :a {} is m(:a {}) and invalid. 

It is not matter of Parser. I think my project code is wrong. so I change my project code.
Thanks for your comments
