### ISSUE TITLE
[2.5.0.4] unexpected token tLCURLY 

### ISSUE THREAD

**Issue by Edouard-chin** [whitequark/parser#470]
Hi 👋 , thanks for this great gem!

I saw an issue opened/closed already on that https://github.com/whitequark/parser/issues/454 but it seems that the associated commit doesn't solve the problem in my case.

```
Edouard-Chins-MacBook-Pro% cat test.rb
before_action only: [:cancel_transfer_out] { check_transfer_out_job_status(:cancel) }

Edouard-Chins-MacBook-Pro% ruby -cv test.rb
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]
Syntax OK

Edouard-Chins-MacBook-Pro% ruby-parse test.rb
(fragment:0):1:46: error: unexpected token tLCURLY
(fragment:0):1: before_action only: [:initiate_transfer_out] { check_transfer_out_job_status(:start) }
(fragment:0):1:

Edouard-Chins-MacBook-Pro% ruby-parse -v
ruby-parse based on parser version 2.5.0.4
```

This used to work fine on `ruby-parse 2.4.0.2`

**Comment by iliabylich** [comment]
That's because this code is invalid for the latest 2.4.x version of MRI (and newer, including 2.5):
``` sh
$ ruby -ve 'before_action only: [:cancel_transfer_out] { check_transfer_out_job_status(:cancel) }'
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
-e:1: syntax error, unexpected '{', expecting end-of-input
... only: [:cancel_transfer_out] { check_transfer_out_job_statu...
...                              ^
```
If you need to parse some code for older version of ruby, pass `--version` option (`--23` for 2.3, for example)

**Comment by Edouard-chin** [comment]
> There was a bug in some version of 2.4.x that allows this syntax, but it's fixed now (and backported to the parser gem).

Ah just saw you explained that in the previous issue. Thanks a lot for your quick answer. Closing this then!
