### ISSUE TITLE
ruby-parse command should not display escape sequences when output is not a tty.

### ISSUE THREAD

**Issue by pocke** [whitequark/parser#474]
Problem
===

Currently ruby-parse displays escape sequences always.

![180320171650](https://user-images.githubusercontent.com/4361134/37642977-7545421c-2c62-11e8-89b8-974b313ea439.png)

It is useful, but the escape sequences are unnecessary when output is not a tty. For example, when I want to copy the output with `pbcopy`, `xsel` and so on, I didn't need coping escape sequences.

```
$ ruby-parse -Ee 'foo' | xsel --input --clipboard
```

The clipboard

```
[4mfoo[0m   
[1;31m^~~[0m [0;32mtIDENTIFIER "foo"[0m                           expr_cmdarg  [0 <= cond] [0 <= cmdarg] [0m
foo[4m[0m   
   [1;31m^[0m [0;32mfalse "$eof"[0m                               expr_cmdarg  [0 <= cond] [0 <= cmdarg] [0m
(send nil :foo)
```

Solution
===

Disable the escape sequences if output is not a tty.

I have a question.
We can implement this feature easily with [rainbow](https://github.com/sickill/rainbow) gem. But we should add the gem to dependencies to use rainbow.
Can we use the gem? Or should we keep the dependencies simple?

I'll work for it if the proposal is acceptable.

**Comment by whitequark** [comment]
No dependencies. I think it's a very important property of Parser that it has no runtime dependencies other than `ast`.
