### ISSUE TITLE
Parse error in Ruby 2.4 & 2.5 parser with dynamically generated constant

### ISSUE THREAD

**Issue by maisumakun** [whitequark/parser#481]
I previously wrote in #480, but I file it as a new issue, for it was a different issue.

## issue

The following code issues a false positive syntax error in `ruby-parse --24` or `ruby-parse --25`.

```ruby
class Test

  private def method(*args)
  end

  SOME_CONST = [].tap do |a|
    a.freeze
  end

end
```

### Expected behavior
(resuly by `ruby-parse --23`)

```
(class
  (const nil :Test) nil
  (begin
    (send nil :private
      (def :method
        (args
          (restarg :args)) nil))
    (casgn nil :SOME_CONST
      (block
        (send
          (array) :tap)
        (args
          (procarg0 :a))
        (send
          (lvar :a) :freeze)))))

```

### Actual behavior

```
parse_bug.rb:6:23: error: unexpected token kDO_BLOCK
parse_bug.rb:6:   SOME_CONST = [].tap do |a|
parse_bug.rb:6:                       ^~
```

## Environment

* `uname -a` ... `Linux j-bit.machine 2.6.32-696.23.1.el6.x86_64 #1 SMP Tue Mar 13 22:44:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* `ruby -v` ... `ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]`
* `ruby-parse --version` ... `ruby-parse based on parser version 2.5.0.5`

**Comment by whitequark** [comment]
Minimized example:
```
private def x()
end

X = [].tap do
end
```
