### ISSUE TITLE
:!@ should be (sym :!), but it is actually (sym :"!@").

### ISSUE THREAD

**Issue by pocke** [whitequark/parser#486]
In MRI
===

`:!@` equals `:!`, but `:"!@"` does not equals `:!`.
`:~@` has the same behaviour.
`:-@` and `:+@` have a different behaviour, `:-@` equals `:"-@"`.

```ruby
# test.rb
p [:!, :!@, :"!@"]
p [:~, :~@, :"~@"]
p [:-, :-@, :"-@"]
p [:+, :+@, :"+@"]
```

```bash
$ ruby test.rb
[:!, :!, :"!@"]
[:~, :~, :"~@"]
[:-, :-@, :-@]
[:+, :+@, :+@]
```

I can confirm this behaviour in Ruby 1.9 ~ 2.6. And `:!` is a syntax error in Ruby 1.8.

Problem
===

Parser gem parses `:!@` to `(sym :"!@")`actually.

```bash
$ ruby-parse -e ':!@'
(sym :"!@")
```

It should be `(sym :!)`.

Probably we should fix `Parser::Builders::Default#symbol` method.
 https://github.com/whitequark/parser/blob/ebcd32c90c8caede85178963005d624ce22bba14/lib/parser/builders/default.rb#L228-L231

**Comment by whitequark** [comment]
> Probably we should fix Parser::Builders::Default#symbol method.

I think this should rather be fixed in the lexer.
