### ISSUE TITLE
parse error: cond ? a + '"': ''

### ISSUE THREAD

**Issue by iliabylich** [whitequark/parser#492]
``` ruby
$ bin/ruby-parse --26 -E -e "a ? b + '': nil"
a ? b + '': nil
^ tIDENTIFIER "a"                               expr_cmdarg  [0 <= cond] [0 <= cmdarg]
a ? b + '': nil
  ^ tEH "?"                                     expr_value   [0 <= cond] [0 <= cmdarg]
a ? b + '': nil
    ^ tIDENTIFIER "b"                           expr_cmdarg  [0 <= cond] [0 <= cmdarg]
a ? b + '': nil
      ^ tPLUS "+"                               expr_beg     [0 <= cond] [0 <= cmdarg]
a ? b + '': nil
        ^ tSTRING_BEG "'"                       expr_labelarg [0 <= cond] [0 <= cmdarg]
a ? b + '': nil
         ^~ tLABEL_END "'"                      expr_labelarg [0 <= cond] [0 <= cmdarg]
(fragment:0):1:10: error: unexpected token tLABEL_END
(fragment:0):1: a ? b + '': nil
(fragment:0):1:          ^~
```

But `a ? '': nil` can be parsed.

**Comment by iliabylich** [comment]
@whitequark In MRI `EXPR_VALUE` is an alias for `EXPR_BEG`:
``` c
enum lex_state_e {
    DEF_EXPR(BEG),
    DEF_EXPR(END),
    DEF_EXPR(ENDARG),
    DEF_EXPR(ENDFN),
    DEF_EXPR(ARG),
    DEF_EXPR(CMDARG),
    DEF_EXPR(MID),
    DEF_EXPR(FNAME),
    DEF_EXPR(DOT),
    DEF_EXPR(CLASS),
    DEF_EXPR(LABEL),
    DEF_EXPR(LABELED),
    DEF_EXPR(FITEM),
    EXPR_VALUE = EXPR_BEG,
    // ...
}
```
 and code constructions like `{ 'a': 'b' }` are handled using a dual state `EXPR_BEG|EXPR_LABEL` after tLBRACE (so if next token is `'` the lexer creates a literal that can become a label). But in the Parser `EXPR_VALUE` is a special state that allows everything that is supported by `EXPR_BEG` except labels and quoted labels. Is it intentional? That's a serious difference in implementation.

If so, is there any common way of replicating such states? It's literally a flag until the next `SET_LEX_STATE` invocation. Theoretically it could be implemented using a flag on the lexer that is automatically removed on every state transition. Like:
```
on every state transition {
  @label_allowed = false
}

e_lbrace {
  @label_allowed = true
}

['"] => {
  fnext push_literal(label_allowed: @label_allowed);
  break;
}
```
... and it allows changing all `fgoto/fnext expr_value` calls to `expr_beg` and completely drop `expr_value` state.

Is it a good idea and does Ragel have anything like this?

**Comment by whitequark** [comment]
> But in the Parser EXPR_VALUE is a special state that allows everything that is supported by EXPR_BEG except labels and quoted labels. Is it intentional? That's a serious difference in implementation.

EXPR_VALUE used to be like that in MRI but it was refactored a long time after Parser's lexer was written.

**Comment by whitequark** [comment]
I don't remember offhand how to do it in Ragel; you'll have to consult its documentation, I'm afraid.
