### ISSUE TITLE
do-end inside {} code block

### ISSUE THREAD

**Issue by jmarianer** [whitequark/parser#501]
parser version 2.5 and up fail on a do-end class definition inside a {} code block. The parse succeeds if the braces are replaced with do-end or vice versa (i.e., the blocks are made consistent). This also succeeds when using parser-2.4.0.2.

```
[rmarianer@iMac ~]$ ruby -e "def let(i) 4 end; p let (:aaa) { Class.new do end }"
4
[rmarianer@iMac ~]$ ruby-parse -e "def let(i) 4 end; p let (:aaa) { Class.new do end }"
(fragment:0):1:44: error: unexpected token kDO_BLOCK
(fragment:0):1: def let(i) 4 end; p let (:aaa) { Class.new do end }
(fragment:0):1:                                            ^~      
```

**Comment by mikegee** [comment]
I think https://github.com/whitequark/parser/pull/500 will resolve this issue.

**Comment by iliabylich** [comment]
No, it will not. Ruby trunk also fails parsing this code, it will be fixed after merging (hopefully) https://bugs.ruby-lang.org/issues/14690 and backporting it to the Parser.

**Comment by mikegee** [comment]
👍 Thanks for the clarification.

**Comment by jmarianer** [comment]
Thanks, everyone. I'll just sit tight, then.
