### ISSUE TITLE
Something's broken in 2.5.1.1

### ISSUE THREAD

**Issue by mvz** [whitequark/parser#518]
Follow-up from https://github.com/rubocop-hq/rubocop/issues/6092#issuecomment-403715689: The following Ruby code is not parsed with parser 2.5.1.1 anymore:

```ruby
class Foo < Bar
end
```

Result:

```
$ ruby-parse --25 foo.rb
foo.rb:2:1: error: unexpected token kEND
foo.rb:2: end
foo.rb:2: ^~~
```

The 1.9 parser works:

```
$ ruby-parse --19 foo.rb
(class
  (const nil :Foo)
  (const nil :Bar) nil)
```

**Comment by whitequark** [comment]
Parser 2.5.1.2 with the fix released.

**Comment by mvz** [comment]
Thanks for the quick response @whitequark and @iliabylich!
