### ISSUE TITLE
JRuby integration

### ISSUE THREAD

**Issue by christophe-zurn-sonarsource** [whitequark/parser#524]
Hello,

I have been experimenting with your parser lately, and I have noticed a big performance difference when using the library with MRI vs. JRuby.

When running the following script in a repository containing ~2000 ruby files (ex: [discourse repository](https://github.com/discourse/discourse)):

```ruby
#!/usr/bin/env ruby
require 'parser/ruby25'

startTime = Time.now
Dir.glob("./**/*.rb").each do |f|
  begin
    Parser::Ruby25.parse_with_comments(File.read(f))
  rescue
    $stderr.print "Parsing failed on file: " + f
  end
end
elapsed =  Time.now.to_i - startTime.to_i
puts "Elapsed time: #{elapsed.to_s}s"
```

It ends up taking around 3 times longer to complete on the JRuby interpreter.

I was wondering if it was something that you were aware of, or that already came up in a discussion before?
I could not find any thread related to your parser running on JRuby.

When looking at the profiles:

###### MRI

```
    self
   seconds     name
--------------------------------------------------
   17.69       Parser::Lexer#advance
    2.51       Array#[]
    1.52       BasicObject#!=
    1.41       Integer#<=
    0.85       Integer#+
    0.83       nil#
    0.72       Integer#==
    0.54       Parser::Source::Buffer#slice
```

###### JRuby
```
    self
   seconds     method
--------------------------------------------------
   56.53       Parser::Lexer#advance
    6.20       Array#[]
    4.68       BasicObject#!=
    4.28       Racc::Parser#_racc_do_parse_c
    2.46       String#encode
    2.12       Parser::Source::Buffer#slice
    1.37       Kernel.send
    1.37       BasicObject#!
```

I can see that the biggest hit in performance comes from the `Parser::Lexer#advance` method, however I can't understand the reason why this takes so much more time with JRuby...
I'd be grateful if you could help me understand the source of this performance drop in JRuby.

Thanks's.

Best,

 Christophe

**Comment by whitequark** [comment]
I'd expect this to be related to the huge `Parser::Lexer#advance` method that cannot be JITted by the JVM because it's too large. @headius, has there been any change in JRuby that could help with this?

**Comment by christophe-zurn-sonarsource** [comment]
@whitequark Oh ok. Thank's for quick response and the precision :)
Indeed, when having a closer look at JIT logs of JRuby, it cannot JIT that method, even with a higher max size for instruction counts. 
I'll have a look at JRuby AOT compilation, to see if something can be done there.
Thank's
