### ISSUE TITLE
procarg0 with parentheses

### ISSUE THREAD

**Issue by saberduck** [whitequark/parser#527]
In the following snippet 

      [[1,2],[3,4]].each do |(a,b)| puts "#{a}:#{b}" end

Block arguments are parsed as 
```
(args
  (procarg0
    (arg :a)
    (arg :b)))
```

However it seems to me that `on_argument` handler in the `Processor` expects argument to have only two children -> [argument and value](https://github.com/whitequark/parser/blob/master/lib/parser/ast/processor.rb#L103) . This means that in this case node `(arg :a)` is never processed as argument because `process_all` is not invoked on it.

Am I right that decomposition in `on_argument` is wrong?

**Comment by saberduck** [comment]
If it's relevant, real world code using this syntax can be found here 
https://github.com/discourse/discourse/blob/master/app/models/permalink.rb#L47

**Comment by whitequark** [comment]
> Am I right that decomposition in `on_argument` is wrong?

Yes. Please add a separate visitor for `on_procarg0`.
