### ISSUE TITLE
incorrect parse of this expression: `Foo()`

### ISSUE THREAD

**Issue by catmando** [whitequark/parser#529]
`Foo {}` is correctly parsed as a method call to the Foo method, but `Foo()` is parsed as `Foo` (i.e. loses track that its a method call.)

This is important to the Hyperstack framework as all HTML tag elements are represented as methods like `DIV`, `SPAN` etc.

I would be happy to help fix, if someone can point me to approx where.

**Comment by iliabylich** [comment]
I can't reproduce it:
```
$ ruby-parse -e 'Foo()'
(send nil :Foo)

$ ruby-parse -e 'DIV()'
(send nil :DIV)
```
(both are getting parsed as method calls)

Which version of `parser` do you use?

**Comment by catmando** [comment]
2.3.3.1

**Comment by iliabylich** [comment]
The issue is not in the parser:

```
$ bin/ruby-parse -v
ruby-parse based on parser version 2.3.3.1

$ bin/ruby-parse --24 -e 'DIV()'
(send nil :DIV)
```

**Comment by catmando** [comment]
huh... okay I will do some more work

**Comment by catmando** [comment]
thanks

**Comment by catmando** [comment]
it was unparser!
