### ISSUE TITLE
useless `begin` in interpolated strings

### ISSUE THREAD

**Issue by akimd** [whitequark/parser#532]
Maybe that's on purpose, but I don't see the point of the `begin` here.

```ruby
$ ruby-parse -e 'def fun bar; "foo#{bar}baz"; end'
(def :fun
  (args
    (arg :bar))
  (dstr
    (str "foo")
    (begin
      (lvar :bar))
    (str "baz")))
```

If this is meant, then the documentation needs to be updated (https://github.com/whitequark/parser/blob/master/doc/AST_FORMAT.md#L105, look for `dstr`).

Cheers!

**Comment by whitequark** [comment]
It carries location info for `#{` and `}`:
```
$ ./bin/ruby-parse -L -e 'x=1; "foo#{x}baz"'
[snip]
s(:begin,
  s(:lvar, :x))
x=1; "foo#{x}baz"
            ~ end
         ~~ begin
         ~~~~ expression
[snip]
```

**Comment by akimd** [comment]
Makes plenty of sense.  But don't you want to update the doc?
