### ISSUE TITLE
TreeRewriter#rewrite is not threadsafe

### ISSUE THREAD

**Issue by mvz** [whitequark/parser#544]
**This is not something I encountered in actual use**, but I just realized that `#rewrite` might not be thread-safe and I decided to check it. The following code confirms that `#rewrite` is not thread-safe. I have added `sleep 0.1` in the rewrites to simulate a rewrite that takes some time. The code fails with `Parser::ClobberingError` errors. If the same code is run sequentially, it simply prints two success messages.

```ruby
require 'parser/current'

class MyRewriter < Parser::TreeRewriter
  def on_int(node)
    sleep 0.1
    replace node.loc.expression, (node.children.last + 1).to_s
  end

  def on_send(node)
    _reciever, method, *_args = *node
    sleep 0.1
    insert_after node.loc.selector, 'zzz' if method.to_s.match?(/[a-z]/)
    super
  end
end

def load_and_rewrite(rewriter, name)
  code = File.read(name)
  ast = Parser::CurrentRuby.parse code
  buffer = Parser::Source::Buffer.new(name)
  buffer.source = code
  rewriter.rewrite(buffer, ast)
end

rewriter = MyRewriter.new
desired_foo = load_and_rewrite(rewriter, 'foo.rb')

threads = 2.times.map do |index|
  Thread.new do
    foo = load_and_rewrite(rewriter, 'foo.rb')
    if foo == desired_foo
      puts "Success foo #{index}"
    else
      puts 'Failed'
    end
  end
end

threads.each(&:join)
```

**Comment by whitequark** [comment]
Indeed, it's not threadsafe, just like any other Ruby object with internal state not protected by a mutex.

**Comment by mvz** [comment]
Using thread-local storage would help in this case, right?

**Comment by whitequark** [comment]
Do you mean in Parser?

**Comment by mbj** [comment]
IMO its a bad idea to make arbitrary interfaces, that are not themselves concurrency primitives, thread safe. In ruby, due its core semantics the caller is responsible to ensure a specific interface is either thread safe, or used in a thread safe manner.

**Comment by mvz** [comment]
@whitequark yes. The reason this particular case struck me is that the parent class *is* thread-safe, and the appearance of internal, mutable state in this particular object is not obvious. I've seen a similar case in Net::HTTP producing issues in a production environment.

**Comment by mbj** [comment]
> @mbj I'm not sure I follow. How does one ensure an interface is thread safe, apart from someone actually making it so?

Wrap your access to the thread safe object into a mutex? Or create one object per thread.
