### ISSUE TITLE
Should we update this to 2.6.2?

### ISSUE THREAD

**Issue by ioquatix** [whitequark/parser#562]
https://github.com/whitequark/parser/blob/2afb33822b10e3f864f06367cb6f00eefadd4471/lib/parser/current.rb#L79

**Comment by iliabylich** [comment]
Fixed in https://github.com/whitequark/parser/pull/563, 2.6.2.0 has been released - https://rubygems.org/gems/parser/versions/2.6.2.0

**Comment by ioquatix** [comment]
Awesome, do you also think it makes sense for the `else` branch to now default to 2.6?

**Comment by ioquatix** [comment]
@Parad0x what exactly are you confused about?

**Comment by ioquatix** [comment]
@iliabylich thanks for your prompt action on this!

**Comment by Parad0X** [comment]
@ioquatix I guess I should've used 👀 emoji ;)
