### ISSUE TITLE
ruby/ruby@9738f96 - pattern matching

### ISSUE THREAD

**Issue by iliabylich** [whitequark/parser#571]
https://github.com/ruby/ruby/commit/9738f96fcfe50b2a605e350bdd40bd7a85665f54

**Comment by iliabylich** [comment]
I'm slowly working on backporting this feature and got a bunch of questions.

Basically pattern matching works via existing `case` construction:
``` ruby
case value
in single_match if condition # conditional is optional
  # no destructuring
  single_match
in single_match,
  # destructuring like in the branch below because of the trailing comma
  single_match
in a, b, c unless condition # conditional is optional
  [a, b]
in ^existing_lvar then result3
in one, *rest
  one
in a:, b: 1
  [a, b]
else
  'no match'
end
```

`^` is a pin operator that prevents assignment and forces usage of existing local variable (just like in Elixir).

Here's the list of questions:
1. Should we emit `case` as `s(:case)`? `in` and `when` inside `case` are mutually exclusive, so it's either a `case` for pattern matching or a regular case that uses `===`. That could be useful to distinguish normal case and pattern matching. Also existing `case` has either `when` or `else` children, so I think adding a new type of child is a breaking change. Is that correct?
2. What should be the name of the node that wraps `in` pattern and its `then` branch? `s(:in)`?
3. What should be the name of the array and hash patterns? `array_pattern`/`hash_pattern`?
4. Should we emit non-pinned variables as `lvasgn`/`masgn` (depending on the amount of items passed to `in`) and pinned variables as `lvar`? Pattern matching technically has two steps: matching and (if matches) mass-assignment. I'm thinking about parsing `in a, ^b, *c` as
```
s(:in,
  s(:array_pattern,
    s(:lvasgn, :a),
    s(:lvar, :b),
    s(:splat, s(:lvasgn, :c))))
```
5. In the last branch you can see an example of matching a hash. Obviously we shouldn't use `kwarg`/`kwoptarg` nodes to represent them. Existing `s(:pair)` doesn't work as well (because sometimes there's no `value`). Maybe it's worth introducing a new node for that?

@whitequark @bbatsov @Drenmi @marcandre @mbj any thoughts?

**Comment by bbatsov** [comment]
Is there some spec we can check about the pattern matching behaviour? I saw the feature doesn't have many tests and I recall reading somewhere that the full spectrum of pattern matching was quite complex. It's hard for me to advise on the node structure without knowing what's possible in general.

**Comment by iliabylich** [comment]
There's no documentation, but there are quite a lot of tests in the commit:
https://github.com/ruby/ruby/commit/9738f96fcfe50b2a605e350bdd40bd7a85665f54#diff-30f49afbb3e44aa9f1fa6a549ab1855fR144
https://github.com/ruby/ruby/commit/9738f96fcfe50b2a605e350bdd40bd7a85665f54#diff-1d2d03bc1e77e55b2e667f6298a0012aR1

**Comment by bbatsov** [comment]
> Should we emit case as s(:case)? in and when inside case are mutually exclusive, so it's either a case for pattern matching or a regular case that uses ===. That could be useful to distinguish normal case and pattern matching. Also existing case has either when or else children, so I think adding a new type of child is a breaking change. Is that correct?

I think we should go with a different name for the node, as this would simplify the client code and not raise compatibility issues.

> What should be the name of the node that wraps in pattern and its then branch? s(:in)?

`in` sound good to me.

> What should be the name of the array and hash patterns? array_pattern/hash_pattern?

I'd be fine with this, but more compact names like `apat` and `hpat` might be more in line with existing names like `lvar`, etc. I guess @whitequark is best qualified to decide on the new names.

> Should we emit non-pinned variables as lvasgn/masgn (depending on the amount of items passed to in) and pinned variables as lvar? 

Sounds reasonable to me. 

> In the last branch you can see an example of matching a hash. Obviously we shouldn't use kwarg/kwoptarg nodes to represent them. Existing s(:pair) doesn't work as well (because sometimes there's no value). Maybe it's worth introducing a new node for that?

I think if there's no value we can just use `nil` there, right?

**Comment by marcandre** [comment]
> > In the last branch you can see an example of matching a hash. Obviously we shouldn't use kwarg/kwoptarg nodes to represent them. Existing s(:pair) doesn't work as well (because sometimes there's no value).

Right, and the left hand side is always a `lvar` name, so `pair` is also overly generic.

>> Maybe it's worth introducing a new node for that?
> 
> I think if there's no value we can just use `nil` there, right?

Matching on `a: nil` is different than `a: `, isn't it?

So probably no choice than new nodes (e.g. `patasgn` and `hrest`).

Note that theres a `1 => a` pattern match too, so that can be using the nodes.

How about `a:, b: 1, **r` being coded as
```
s(:hpat,
  s(:lvasgn, :a),
  s(:patasgn, :b, s(:int, 1)),
  s(:hrest, :r)
```

`1 => a` could also use `patasgn`.

It's not clear to me if we should be using `lvasgn` within an `hpat` or not. It's similar to how there's an `arg` node when `lvasgn` could have been used instead.

**Comment by iliabylich** [comment]
@marcandre 

> Matching on `a: nil` is different than `a: `, isn't it?

Yes, the first is used only for matching, the second is also used in destructuring, so it produces a local variable (the first one doesn't):
``` ruby
case { a: 1 }
in a: 1
  a
else
  'no match'
end
# => NameError (undefined local variable or method `a' for main:Object)

case { a: 1 }
in a:
  a
else
  'no match'
end
# => 1
```

so in the case above `a: 1` doesn't assign anything (`a:` does). I'd say that `a: 1` can be a `s(:pair)`, while `a:` should be `s(:lvasgn)` inside `s(:hpat)`. However, creating a new node would make a client code simpler as it doesn't require it to track the context. Not sure about it.

@bbatsov 
> I think if there's no value we can just use `nil` there, right?

No, `pair` always has a key and a value, that'd be a breaking change.

**Comment by marcandre** [comment]
> Yes, the first is used only for matching, the second is also used in destructuring, so it produces a local variable (the first one doesn't)

Oh, I see, I was confused, thanks.

So I agree that `pair` could work fine, then.

**Comment by iliabylich** [comment]
Also https://github.com/ruby/ruby/commit/94d6ec1d90bb28e5f303867b048e6322d8781cb1

**Comment by iliabylich** [comment]
Also https://github.com/ruby/ruby/commit/3cee99808d629c0ec493955ce8ea019d1f8a637b

**Comment by iliabylich** [comment]
Also https://github.com/ruby/ruby/commit/25100c469758dd3676ec608ed27fd89248980666. @whitequark quick question: we ignore all void-value-expression errors, for parser that's a valid syntax, right?

**Comment by whitequark** [comment]
Yes.

**Comment by iliabylich** [comment]
Also https://github.com/ruby/ruby/commit/b4229c0a90ef902328e09a92fc5c6e884d01c542

**Comment by iliabylich** [comment]
Also https://github.com/ruby/ruby/commit/a396bef8d8b72328d411abe7a275736ad995fbcb

**Comment by iliabylich** [comment]
also https://github.com/ruby/ruby/commit/6e70fa49b111e2a2839297b057a3df354cae265a

**Comment by iliabylich** [comment]
also https://github.com/ruby/ruby/commit/0b8c73aa65add5c57b46b0cfdf4e661508802172

**Comment by iliabylich** [comment]
I have no idea why, but MRI throws syntax errors from `compile.c`:

```
2.1.8 :005 > code = 'case 1; in a|b|c|1; a==0 end'
2.1.8 :006 > Ripper.sexp(code)
 => [:program, [[:case, [:@int, "1", [1, 5]], [:in, [:binary, [:binary, [:binary, [:var_field, [:@ident, "a", [1, 11]]], :|, [:var_field, [:@ident, "b", [1, 13]]]], :|, [:var_field, [:@ident, "c", [1, 15]]]], :|, [:@int, "1", [1, 17]]], [[:binary, [:var_ref, [:@ident, "a", [1, 20]]], :==, [:@int, "0", [1, 23]]]], nil]]]]
2.1.8 :007 > eval(code)
(eval):1: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
Traceback (most recent call last):
        1: from (eval)
SyntaxError ((eval):1: illegal variable in alternative pattern (a))
(eval):1: illegal variable in alternative pattern (b)
(eval):1: illegal variable in alternative pattern (c)
```

Tested on `ruby 2.7.0dev (2019-11-19T15:56:04Z trunk 61131edba7) [x86_64-darwin19]`, also reproducible with `-c` flag

I'm not going to backport it. Technically it's not a part of the grammar.

**Comment by iliabylich** [comment]
also https://github.com/ruby/ruby/commit/26625bc33c32e0945bf727234a3ce6da1eb0ddc4 (no functional changes)

**Comment by iliabylich** [comment]
also https://github.com/ruby/ruby/commit/9e01fcd0cb79a05daa50d99c888cc7eeb9c79426
