### ISSUE TITLE
Question about release

### ISSUE THREAD

**Issue by rderoldan1** [whitequark/parser#602]
First of all thanks for all your great work 

We are about to release ruby 2.6.4 and wondering if you can release this  https://github.com/whitequark/parser/commit/4da18918a70df941769c4200753e48cc4389c323 so we can get rid of `"warning: parser/current is loading parser/ruby26, which recognizes warning: 2.6.3-compliant syntax, but you are running 2.6.4. warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri"`

**Comment by iliabylich** [comment]
https://rubygems.org/gems/parser/versions/2.6.4.0 has been released

**Comment by rderoldan1** [comment]
Great @iliabylich :) Have an amazing day
