### ISSUE TITLE
block attaches to the wrong expr when arg is an expr

### ISSUE THREAD

**Issue by iliabylich** [whitequark/parser#604]
```
$ ruby -ve 'def m(x); p x; end; a = 1; b = 2; m a + b do; end'
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
3
```
as you can see it works as `m(a + b) do end`

```
$ bin/ruby-parse --18 -e 'm a + b do end'
(send nil :m
  (send
    (send nil :a) :+
    (block
      (send nil :b)
      (args) nil)))
$ bin/ruby-parse --26 -e 'm a + b do end'
(send nil :m
  (send
    (send nil :a) :+
    (block
      (send nil :b)
      (args) nil)))
```
not sure if it's a bug that we had from the very beginning or something caused by me (I think it's the latter).

Going to investigate it tomorrow.

**Comment by iliabylich** [comment]
This commit introduced it - https://github.com/whitequark/parser/commit/f0a5c6b5a55ccadc784489d966efc8975b3f4e32

@whitequark I need some help. `expr_value` is used to reject labels (and it jumps to `expr_beg` otherwise), that's why I used it in this commit. However `expr_value` is also used to set `@command_state` flag that is later used for `expr_cmdarg`. As a result, lexer enters `expr_cmdarg` and emits `kDO` instead of `kDO_BLOCK` and so parser does a different sequence of reduce actions.

What would you recommend? In MRI `@command_state` doesn't depend on `expr_value` (they do interact, but overall MRI sets this field manually). Should we do the same thing?

**Comment by whitequark** [comment]
I think so.

**Comment by iliabylich** [comment]
@whitequark a (very) dirty solution would be doing `@command_state = false` before jumping from `expr_value` to `expr_beg` (because we are not in the "command mode" anymore).

In general doing something state-dependant in the beginning of `advance` and doing `fgoto` afterwards is somewhat dangerous, because it produces a wrong state.
