### ISSUE TITLE
When will Parser 2.6.4.1 will be released?

### ISSUE THREAD

**Issue by koic** [whitequark/parser#608]
An error has occurred in RuboCop's Ruby 2.7 matrix. This is solved with #607.

The Parser gem does not bundle the automatically generated `parser/lexer.rb` file. Therefore, even if RuboCop specifies parser in Gemfile, the following error occurs.

```diff
diff --git a/Gemfile b/Gemfile
index fe0e57173..9c8c78413 100644
--- a/Gemfile
+++ b/Gemfile
@@ -2,9 +2,15 @@

 source 'https://rubygems.org'

+git_source(:github) { |repo| "https://github.com/#{repo}.git" }
+
 gemspec

 gem 'bump', require: false
+# Workaround for Ruby 2.7 warning.
+# https://github.com/whitequark/parser/pull/607
+# It can be deleted when Parser 2.6.4.1 or higher will be released.
+gem 'parser', github: 'whitequark/parser', ref: '6aed650'
 gem 'pry'
 gem 'rake', '~> 12.0'
 gem 'rspec', '~> 3.7'
```

```console
% bundle exec rake
rake aborted!
LoadError: cannot load such file -- parser/lexer
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop.rb:3:in `require'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop.rb:3:in `<top (required)>'
```

I'm happy when Parser 2.6.4.1 will be released.

**Comment by iliabylich** [comment]
@whitequark currently I’m on vacation, could you release it please? If not I’ll do it myself on Monday

**Comment by bbatsov** [comment]
Btw, it'd be cool if someone from RuboCop's team could do emergency releases as well, given our dependence on `parser`. I think we're a reasonably reliable bunch of people over at RuboCop HQ and would never abuse such power.

**Comment by whitequark** [comment]
I thought @iliabylich was on RuboCop's team.

**Comment by bbatsov** [comment]
Nope. He's on Opal's team.

**Comment by whitequark** [comment]
Ah OK. I think I'd be fine granting @koic gem upload rights.

**Comment by bbatsov** [comment]
That's be awesome. Thank you! 🙇

**Comment by whitequark** [comment]
But I'd need to know the Rubygems account.

**Comment by bbatsov** [comment]
See https://rubygems.org/profiles/koic_ito

**Comment by koic** [comment]
Thank you everyone!
My RubyGems account is `koic.ito@gmail.com` when using `gem owner`.
https://guides.rubygems.org/command-reference/#gem-owner

I think version.rb and git tag needs to be pushed when releasing.  If you are okay, please grant me permission to this repository together.

I'd like to release Parser 2.6.4.1 if you grand me those permissions.

**Comment by whitequark** [comment]
Both done.

**Comment by koic** [comment]
Thank you for granting me permissions.

I released Parser 2.6.4.1. 
However RuboCop's Ruby 2.7 CI continues to fail, so I'm sorry I didn't release it well...

I was expecting this warning to disappear in this release. But that didn't happen.

```console
/usr/local/bundle/gems/parser-2.6.4.1/lib/parser/source/tree_rewriter.rb:269: warning: The last argument is used as the keyword parameter
```

https://circleci.com/gh/rubocop-hq/rubocop/67829

Could you please tell me release procedure that's convenient for you?

**Comment by whitequark** [comment]
There is nothing special about releasing Parser; `rake release` should be sufficient.

The reason I handed off day-to-day maintenance of this gem is precisely so that I will not have to care about minute changes (such as new warnings) in Ruby, the language I find intensely frustrating to work with. So I will not be able to assist you with this.

**Comment by iliabylich** [comment]
@koic I can help you on Monday. Accidentally closed and reopened, sorry

**Comment by koic** [comment]
I appreciate your prompt reply despite a vacation. 

When running `rake release` (`rake changelog`), the change history was not generated as expected. So I released it by handcraft.

I would be grateful if you could help me on Monday. Thanks again.

**Comment by iliabylich** [comment]
@koic The reason why the changelog was broken for you is that `rake changelog` task iterates over commits and looks into all tags that "include" this commit. It assumes that each tag is a "snapshot" of the master, and that's what usually happens when you do `rake release`:

```
629dbb2 (HEAD -> master, origin/master, origin/HEAD) Cut 2.6.4.1
6aed650 Follow "Separate Keyword Arguments from Positional Arguments"
0b96cf7 Add `kwnilarg` for `**nil` argument (#606)
8cea3dd - lexer.rl: fix parsing of 'm a + b do end' (#605)
a48a76c Update changelog.
e7580e0 (tag: v2.6.4.0) Update changelog.
b6ffe2e Bump version.
dd12f95 + ruby27.y: Revert "pipeline operator" (#601)
11ce44f + ruby27.y: Fix parsing of mutiple assignment with rescue modifier (#600)
7c62fdd Bump racc dependency to 1.4.15
4da1891 Bump maintenance branches to 2.6.3, 2.5.6, and 2.4.7 (#598)
ebed465 + ruby27.y: hoisted out f_rest_marg. (#594)
b5119fc + ruby27.y: added pipeline operator. (#592)
ece7df4 - ruby-parse: print empty string when --emit-json and empty input are given. (#590)
936e669 - AST_FORMAT: fixed documentation of the string with interpolation. (#589)
17a66bd - builder.rb, processor.rb: Changed format of the procarg0 node. (#587)
f15bc33 + ruby27.y: reject safe navigator in LHS of mass-assignment. (#586)
0e9a4b2 + lexer.rl: reject whitespaces in meta and control chars. (#585)
8f0c308 + lexer.rl: Reject numparams as symbol literals. (#582)
3edaf9c * Added specs for heredocs with mixed encoding. (#581)
5d31c61 + ruby27.y: Added numbered parameters support. (#565)
0e613aa + lexer.rl: Reject \n and \r in heredoc identifiers starting from 2.7. (#575)
ae52842 Update changelog.
9bf9550 (tag: v2.6.3.0) Update changelog.629dbb2 (HEAD -> master, origin/master, origin/HEAD) Cut 2.6.4.1
6aed650 Follow "Separate Keyword Arguments from Positional Arguments"
0b96cf7 Add `kwnilarg` for `**nil` argument (#606)
8cea3dd - lexer.rl: fix parsing of 'm a + b do end' (#605)
a48a76c Update changelog.
e7580e0 (tag: v2.6.4.0) Update changelog.
b6ffe2e Bump version.
dd12f95 + ruby27.y: Revert "pipeline operator" (#601)
11ce44f + ruby27.y: Fix parsing of mutiple assignment with rescue modifier (#600)
7c62fdd Bump racc dependency to 1.4.15
4da1891 Bump maintenance branches to 2.6.3, 2.5.6, and 2.4.7 (#598)
ebed465 + ruby27.y: hoisted out f_rest_marg. (#594)
b5119fc + ruby27.y: added pipeline operator. (#592)
ece7df4 - ruby-parse: print empty string when --emit-json and empty input are given. (#590)
936e669 - AST_FORMAT: fixed documentation of the string with interpolation. (#589)
17a66bd - builder.rb, processor.rb: Changed format of the procarg0 node. (#587)
f15bc33 + ruby27.y: reject safe navigator in LHS of mass-assignment. (#586)
0e9a4b2 + lexer.rl: reject whitespaces in meta and control chars. (#585)
8f0c308 + lexer.rl: Reject numparams as symbol literals. (#582)
3edaf9c * Added specs for heredocs with mixed encoding. (#581)
5d31c61 + ruby27.y: Added numbered parameters support. (#565)
0e613aa + lexer.rl: Reject \n and \r in heredoc identifiers starting from 2.7. (#575)
ae52842 Update changelog.
9bf9550 (tag: v2.6.3.0) Update changelog.
```

^ Search for `tag:`, there are tags for 2.6.4.0, 2.6.3.0 etc, but no 2.6.4.1, I guess because you pushed something on top of master's `Update changelog` auto-generated commit (i.e. you switched the ref). I'm pretty sure that it will drop 2.6.4.1 from the changelog on the next release. However, tags are very similar to branches, they are named commit refs, so we can push whatever we want. I'll force-push this tag a bit later today and make sure that `rake changelog` doesn't break what you put manually into `Changelog.md`.

**Comment by iliabylich** [comment]
Done:
``` sh
$ git push origin :refs/tags/v2.6.4.1
To github.com:whitequark/parser.git
 - [deleted]         v2.6.4.1
$ git tag -d v2.6.4.1
Deleted tag 'v2.6.4.1' (was 1b25d34)
$ git tag v2.6.4.1
$ rake changelog
$ git push --tags
Total 0 (delta 0), reused 0 (delta 0)
To github.com:whitequark/parser.git
 * [new tag]         v2.6.4.1 -> v2.6.4.1
$ git push
```

`rake changelog` gives 0 changes now.

@koic `lib/parser/source/tree_rewriter.rb:269` must send `**attributes`, it should fix the warning on 2.7. Is there any way to include ruby 2.7 (i.e. from trunk) to the travis matrix?

**Comment by koic** [comment]
Thank you for your explanation! I understand in your description that I forgot `git pull --tags` before `rake changelog` 💦 `rake changelog` now has the expected behavior.

Also, Ruby 2.7 deprecation warning seems to have been mistaken for #607 (This is a different warning). I will open a PR for `lib/parser/source/tree_rewriter.rb:269`. OTOH, I don't have a good idea about adding to Travis  Ruby 2.7 matrix yet...

Thanks for your kindness again!

**Comment by iliabylich** [comment]
@koic I don't do `git pull --tags`, just bump version -> commit -> `rake release` -> `rake changelog` -> `git push` (because `changelog` task relies on a git tag that gets created only after `rake release`)

**Comment by iliabylich** [comment]
Closing as 2.6.4.1 has been released (thanks to @koic)
