### ISSUE TITLE
2.7: numparams -> implicit params

### ISSUE THREAD

**Issue by iliabylich** [whitequark/parser#616]
https://github.com/ruby/ruby/commit/e73cc3eead75b27eabf93a7163bed511f2bb3b17
https://github.com/ruby/ruby/commit/ea68bb914a3c806a1c5188993b96791a76ab0849
https://github.com/ruby/ruby/commit/0e84eecc1764ec6e2a28654b3e66b8c006f73432

The first commit has 0 tests, so it needs some investigation

**Comment by iliabylich** [comment]
also
https://github.com/ruby/ruby/commit/e663299a5f7a980aae39f3e87cec064ae19a870c
https://github.com/ruby/ruby/commit/55e1e22b2d44a8a1eca0f6ed2b11dc0f564f7192
https://github.com/ruby/ruby/commit/33c5ad3154099769cec7f77b6d95cbf4b8d52bb0

**Comment by iliabylich** [comment]
Alright, this sequence of changes is simply about renaming `@1 - @9` to `_1 - _9`. First change (that I really like by the way, but we don't need to do anything about it, because there's no `procarg0` for `numblock`):
``` ruby
# previously:
proc { @1 }.call([1, 2])
 => 1

# now:
proc { [_1] }.call([1, 2])
 => [[1, 2]]
```
so a single argument is now `|x|` (not `|x,|`)

The next thing is that this `_N` is a local variable:
``` ruby
2.1.8 :027 > -> { _1; local_variables }.call(1)
 => [:_1, :_]
```

And it can be used in assignment:
``` ruby
2.1.8 :047 > proc { _1 = 'a'; _1 }.call('b')
(irb):47: warning: `_1' is used as numbered parameter
 => "a"
```

But in this case it's no longer a parameter:
``` ruby
2.1.8 :049 > ->{ _1 = 'a'; _1 }.call('b')
(irb):49: warning: `_1' is used as numbered parameter
Traceback (most recent call last):
        4: from -e:1:in `<main>'
        3: from <internal:prelude>:206:in `irb'
        2: from (irb):49:in `<main>'
        1: from (irb):49:in `block in <main>'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.1.8 :050 > ->{ _1 = 'a'; _1 }.arity
(irb):50: warning: `_1' is used as numbered parameter
 => 0
```

... which means that "reading" this parameter declares it, simple assignment works as a local variable assignment, here's an example (`_1` is a parameter, but `_2` is not):
``` ruby
2.1.8 :055 > ->{ _2 = 'a'; [_1, _2] }.call(1, 2)
(irb):55: warning: `_2' is used as numbered parameter
Traceback (most recent call last):
        4: from -e:1:in `<main>'
        3: from <internal:prelude>:206:in `irb'
        2: from (irb):55:in `<main>'
        1: from (irb):55:in `block in <main>'
ArgumentError (wrong number of arguments (given 2, expected 1))
```

And of course, it still affects arity:
``` ruby
2.1.8 :029 > ->{_1;_2}.arity
 => 2
```

And what's even worse is that you can't use these implicit parameters in consecutive blocks/lambdas (by saying "worse" I mean "difficult to backport"):
``` ruby
2.1.8 :030 > ->{_1; ->{_2}}
Traceback (most recent call last):
        2: from -e:1:in `<main>'
        1: from <internal:prelude>:206:in `irb'
SyntaxError ((irb):30: numbered parameter is already used in)
(irb):30: outer block here
->{_1; ->{_2}}
   ^~
```

However, opening a class/sclass/method/singleton method "fixes" it:
``` ruby
2.1.8 :033 > ->{def m; ->{_2}; end; _1 }
 => #<Proc:0x00007ff992fb0368 (irb):33 (lambda)>
```
... sometimes (until you swap statements)
``` ruby
2.1.8 :032 > ->{_1; def m; ->{_2}; end }
Traceback (most recent call last):
        2: from -e:1:in `<main>'
        1: from <internal:prelude>:206:in `irb'
SyntaxError ((irb):32: numbered parameter is already used in)
(irb):32: outer block here
->{_1; def m; ->{_2}; end }
   ^~
```

Going to spend more time reading the code

**Comment by iliabylich** [comment]
I've just reported an issue from the last snippet above - https://bugs.ruby-lang.org/issues/16248. I can't understand the logic around this error, let's wait

**Comment by iliabylich** [comment]
Also https://github.com/ruby/ruby/commit/c2065c64cb198d5b53a5ecdf9638d064f6fec2e2 (and now everything is clear)

**Comment by iliabylich** [comment]
I think I have answers:
1. It can be just an `lvar`, there's enough information in the AST
2. There's no need to do anything, the whole `MaxNumparamStack` represents `block` values in the `Context`, so we have enough data to raise an error.
3. We can still use `numblock`, MRI uses it internally and I think people still call it "numbered parameters"

**Comment by whitequark** [comment]
I'm utterly confused as to what's happening upstream here, to be honest. Do we have two kinds of implicit parameters now or something?

**Comment by iliabylich** [comment]
No, there's only 1 kind (before and after this change). Previously it was `@N`, now it's `_N`. They renamed it and slightly changed semantics.
