### ISSUE TITLE
Ruby 2.6.5

### ISSUE THREAD

**Issue by dougo** [whitequark/parser#618]
I have installed MRI 2.6.5 (released yesterday, Oct 1), but with the latest released parser gem (version 2.6.4.1) I get this warning:

warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.4-compliant syntax, but you are running 2.6.5.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

**Comment by iliabylich** [comment]
parser 2.6.5.0 has been released - https://rubygems.org/gems/parser/versions/2.6.5.0
