### ISSUE TITLE
Feature request: option for disabling stderr output in Parser::Base#parse()

### ISSUE THREAD

**Issue by dmlary** [whitequark/parser#644]
I'm using Parser in an environment where stderr output isn't visible to the user, and just fills up the logs.  Is there any way you could add a `quiet: true` option to `Parser::Base#parse()` that doesn't create the diagnostics consumer?  Or perhaps some other option that lets the caller redirect those diagnostics to another IO object?

**Comment by iliabylich** [comment]
You can specify a diagnostic consumer, this how we set it to store warnings in the variable in tests (instead of printing them to stderr) - https://github.com/whitequark/parser/blob/master/test/parse_helper.rb#L35

**Comment by dmlary** [comment]
Admittedly, this feature request is more about syntactical sugar.  I'm coming from:
```
ast = Parser::CurrentRuby.parse(@source)
```

If I could throw a diagnostics consumer right in that call as a parameter, that would work, or an intentional nil.

```
ast = Parser::CurrentRuby.parse(@source, consumer: nil)
ast = Parser::CurrentRuby.parse(@source, diagnostics_consumer: nil)
```

**Comment by iliabylich** [comment]
> Is this what you're talking about?

Yes!

**Comment by dmlary** [comment]
Modified that approach to actually get the parser, but it does not work.  It looks like there's some additional arguments involved.  I'll keep mucking around, but the requested functionality still seems desirable to me (to prevent having to muck).

```
[3] pry(main)> parser = Parser::CurrentRuby.new;1
=> 1
[4] pry(main)> parser.diagnostics.consumer = lambda { }
=> #<Proc:0x00007fc12aff0760@(pry):4 (lambda)>
[5] pry(main)> parser.parse("3 = 4")
NoMethodError: undefined method `source' for "3 = 4":String
from /Users/dmlary/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/parser-2.7.0.0/lib/parser/lexer.rb:10871:in `source_buffer=
```

**Comment by iliabylich** [comment]
Sorry, I always forget that there's also a source buffer:
``` ruby
require 'parser/current'

parser = Parser::CurrentRuby.new
parser.diagnostics.consumer = ->(message) { p message }
source_buffer = Parser::Source::Buffer.new('test.rb')
source_buffer.source = "3 = 4"
pp parser.parse(source_buffer)
```

``` sh
$ ruby -rbundler/setup test.rb
#<Parser::Diagnostic:0x00007f7f1f856948 @level=:error, @reason=:unexpected_token, @arguments={:token=>"tEQL"}, @location=#<Parser::Source::Range test.rb 2...3>, @highlights=[]>
s(:int, 4)
```
(I guess `s(:int, 4)` comes from the error recovery, since the original error gets swallowed by a dummy consumer, so be careful with it)

**Comment by dmlary** [comment]
Understood, and thanks.

If you don't feel there's a need for exposing this capability to that top-level `parse()` method, feel free to close this issue.
