### ISSUE TITLE
Parser fails to parse lamda with curly braces, when a default argument is a hash literal.

### ISSUE THREAD

**Issue by ushi-as** [whitequark/parser#645]
Parser 2.7 fails with `unexpected token tLCURLY`, when parsing a lambda literal with a hash literal as default argument like `-> (arg={}) {}`

```shell
$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
```
```
$ ruby-parse --version
ruby-parse based on parser version 2.7.0.1
```
```
$ ruby-parse -e "-> (arg={}) {}"
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.5-compliant syntax, but you are running 2.6.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(fragment:0):1:13: error: unexpected token tLCURLY
(fragment:0):1: -> (arg={}) {}
(fragment:0):1:   
```

**Comment by iliabylich** [comment]
Most probably caused by https://github.com/whitequark/parser/commit/5b1d53cff884585611761723e2dd1db347d2df79.

Thanks for reporting, I'll take a look later today

**Comment by rafaelfranca** [comment]
This is causing rubocop 0.79 to fail in our application given it requires parser 2.7.0.1 that has this bug.

**Comment by iliabylich** [comment]
I wonder what we can do to avoid errors like this in the future. We do run rubocop test suite on each PR, here's the current master - https://travis-ci.org/whitequark/parser/builds/631073716, so both parser and Rubocop don't have any tests for the snippet posted above.

I was thinking about parsing `rubyspec/language`, but it uses `eval` in many places to test new syntax, so it's not that good. Thoughts?

**Comment by mbj** [comment]
@iliabylich I think you could generate "random AST" (with some constraints like only plugging literals and certain expressions into default arguments) unparse it and parse it again. Asserting the parsed generated source produces the same AST originally generated.

Making the constraint rules on which AST node class can appear at what child position is the hard part.

**Comment by iliabylich** [comment]
`2.7.0.2` has been released - https://rubygems.org/gems/parser/versions/2.7.0.2, could you check it please?
