### ISSUE TITLE
Inconsistent / misleading warning messages

### ISSUE THREAD

**Issue by jmromer** [whitequark/parser#648]
Working on two different branches, one with Ruby 2.5.5 and another with 2.5.7, I'm seeing parser emit warnings indicating that `parser/ruby25`

- recognizes 2.5.5-compliant syntax but not `2.5.7`, and that it
- recognizes 2.5.7-compliant syntax but not `2.5.5` 

```shell
ruby-2.5.7 % asdf current ruby
# 2.5.7 

ruby-2.5.7 % bin/rspec 
# warning: parser/current is loading parser/ruby25, which recognizes
# warning: 2.5.5-compliant syntax, but you are running 2.5.7.
# warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

```shell
ruby-2.5.5 % asdf current ruby
# 2.5.5

ruby-2.5.5 % bin/rspec 
# warning: parser/current is loading parser/ruby25, which recognizes
# warning: 2.5.7-compliant syntax, but you are running 2.5.5.
# warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

It is this intentional?

**Comment by iliabylich** [comment]
What's the version of parser? Could you do `gem list | grep parser` after switching to ruby `2.5.5` and `2.5.7`?

The version that is included in the warning is static - https://github.com/whitequark/parser/blob/master/lib/parser/current.rb#L60, so I think you two different versions installed in your gemsets.

**Comment by jmromer** [comment]
Much obliged!

```shell
ruby-2.5.5 % cat Gemfile.lock | grep '\bparser\b'
# 414:    parser (2.6.5.0)

ruby-2.5.7 % cat Gemfile.lock | grep '\bparser\b'
# 382:    parser (2.6.3.0)
```
