### ISSUE TITLE
Using the lexer

### ISSUE THREAD

**Issue by mckaz** [whitequark/parser#649]
I'm interested in only tokenizing some Ruby programs, not producing an AST. Is there documentation or a straightforward way to access only the lexer output? I'm sure I could dig in more to the code, but I figured I'd ask first. Thanks!

**Comment by iliabylich** [comment]
Ruby grammar is complicated and parser tells lexer what to do in a few places. So short answer: you can't lex without parsing. However (as a very dirty solution) you could patch `Lexer#advance` to also collect tokens in some external storage (but you'll have to call `Parser.parse` anyway to fill this storage)

**Comment by mckaz** [comment]
Thanks, that makes sense. I'll look into `Lexer#advance`. 

I noticed this `Lexer::Explanation#advance` method too, which seems to do something very similar: print tokens to stdout. Is there a way to trigger the use of this  `advance` method while lexing?

**Comment by iliabylich** [comment]
`ruby-parse -E file.rb` triggers it. It's used by `parser`'s CLI executables internally so it's better to not use it anywhere outside `parser`'s source code

**Comment by mckaz** [comment]
Got it, thanks!

**Comment by iliabylich** [comment]
```sh
$ /bin/cat print_tokens.rb
module PrintTokens
  def advance(*)
    token = super
    p token
    token
  end
end

Parser::Lexer.prepend(PrintTokens)

$ ruby -Ilib -I. -rparser/current -rprint_tokens.rb -e "Parser::CurrentRuby.parse('1 + 1')"
[:tINTEGER, [1, #<Parser::Source::Range (string) 0...1>]]
[:tPLUS, ["+", #<Parser::Source::Range (string) 2...3>]]
[:tINTEGER, [1, #<Parser::Source::Range (string) 4...5>]]
[false, ["$eof", #<Parser::Source::Range (string) 5...5>]]
```

^ change `p` to something like `$tokens << token`

**Comment by mckaz** [comment]
Perfect!

**Comment by iliabylich** [comment]
I'm really sorry (don't know how I forgot about this method) but there's also `Parser#tokenize`:

```
require 'parser/current'

parser = Parser::CurrentRuby.new
source_buffer = Parser::Source::Buffer.new('test.rb')
source_buffer.source = "3 = 4"
ast, comments, tokens = parser.tokenize(source_buffer)
p tokens
```

And please ignore everything I posted above 😄

**Comment by mckaz** [comment]
Even better.
