### ISSUE TITLE
ruby/ruby@7a288df - `yield` inside class/module/sclass gives a SyntaxError

### ISSUE THREAD

**Issue by iliabylich** [whitequark/parser#650]
https://github.com/ruby/ruby/commit/7a288df7b85d3565f369b305f225c2cd5baa5905

2.7.0:

```
>ruby -vwe 'class X; yield; end'
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
-e:1:in `<class:X>': no block given (yield) (LocalJumpError)

>ruby -vwe 'module X; yield; end'
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
-e:1:in `<module:X>': no block given (yield) (LocalJumpError)

>ruby -vwe 'class << self; yield; end'
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
-e:1:in `singleton class': no block given (yield) (LocalJumpError)
```

trunk:

```
>./local/bin/ruby -ve 'class X; yield; end'
ruby 2.8.0dev (2020-02-12T15:15:22Z master bc1dbed16c) [x86_64-darwin19]
-e: -e:1: Invalid yield (SyntaxError)

>./local/bin/ruby -ve 'module X; yield; end'
ruby 2.8.0dev (2020-02-12T15:15:22Z master bc1dbed16c) [x86_64-darwin19]
-e: -e:1: Invalid yield (SyntaxError)

>./local/bin/ruby -ve 'class << self; yield; end'
ruby 2.8.0dev (2020-02-12T15:15:22Z master bc1dbed16c) [x86_64-darwin19]
-e: -e:1: Invalid yield (SyntaxError)
```

what's strange is that it's not in `parse.y`, and so if you pass `-c` option you get `Syntax OK` message:

```sh
>./local/bin/ruby -vce 'class << self; yield; end'
ruby 2.8.0dev (2020-02-12T15:15:22Z master bc1dbed16c) [x86_64-darwin19]
Syntax OK
```

@whitequark this is the first time I see a syntax error thrown from `compile.c`. Have you ever seen it? If it's not going to change should it be backported? Technically it's a runtime error. I'm totally confused

**Comment by iliabylich** [comment]
https://github.com/ruby/ruby/commit/7a288df7b85d3565f369b305f225c2cd5baa5905#commitcomment-37256447, seems like this is not the only "runtime" `SyntaxError`:
```
>ruby -ve 'retry'
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
-e:1: Invalid retry
Traceback (most recent call last):
-e: compile error (SyntaxError)

>ruby -vce 'retry'
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
Syntax OK
```

Closing as it's not a part of the Ruby grammar.

**Comment by whitequark** [comment]
This is a bit of a grey area. I would argue that any `SyntaxError` is *in principle* in the domain of Parser, especially cases like this that are clearly lexical, but I don't have a strong opinion on whether we should actually implement them (and follow `compile.c`) or not (and follow `ruby -c`). Either option works so long as it's consistent.
