### ISSUE TITLE
2 questions on parser

### ISSUE THREAD

**Issue by ljulliar** [whitequark/parser#651]
Hi there,

First of all congratulation for this great Ruby parser. I have two questions for you:

1) Is it possible to catch Ruby comments while parsing Ruby code

2) When an error is detected in parsing is it possible to display where the error occured in the originla source code ?

Thank you!

**Comment by mbj** [comment]
> 1. it possible to catch Ruby comments while parsing Ruby code

See: https://www.rubydoc.info/github/whitequark/parser/Parser/Base#parse_with_comments-instance_method

> 2. When an error is detected in parsing is it possible to display where the error occured in the originla source code ?

See: https://www.rubydoc.info/github/whitequark/parser/Parser/Diagnostic

**Comment by iliabylich** [comment]
@ljulliar Closing. Feel free to reopen if you still have any questions

**Comment by ljulliar** [comment]
Hi guys,

I tried the parse_with_comment approach but I wasn't too sure how to use
the output. I was expecting the comments to appear as 'comment' type nodes
in the flow of the AST tree but it seems like they are grouped in an array
with line and column references from the original source code which makes
it almost impossible to reconcile with their position in the AST.

Am I missing something here?

Laurent

**Comment by iliabylich** [comment]
@ljulliar It is possible to associate AST nodes with comments: https://www.rubydoc.info/gems/parser/2.7.0.2/Parser/Source/Comment/Associator
