### ISSUE TITLE
Behavior of `defined?`

### ISSUE THREAD

**Issue by chino** [whitequark/parser#667]
From reading this link: https://github.com/whitequark/parser/blob/master/doc/AST_FORMAT.md

I believe that `defined? x` should expand to something like `(defined? (lvar :x))` even if `x` was never previously set to a variable?  I mean, we're trying to determine if it's defined so there is possibility that it's never been right?  It seems to instead believe that it's a method name by sending me `(defined?   (send nil :x))`.

I'm thinking that it should perhaps instead simply produce something like `(defined?   (str :x))` since the argument is something the runtime is supposed to handle?

**Comment by iliabylich** [comment]
If `x` is a local variable parser returns `lvar x`:
``` sh
> bin/ruby-parse --27 -e 'x = 1; defined?(x)'
(begin
  (lvasgn :x
    (int 1))
  (defined?
    (lvar :x)))
```

> I believe that defined? x should expand to something like (defined? (lvar :x)) even if x was never previously set to a variable?

If there's no assignment in the current scope then it's 100% a method:
```sh
> bin/ruby-parse --27 -e 'defined?(x)'
(defined?
  (send nil :x))
```

Ripper follows the same rule (and I'm sure `RubyVM::AST` too):
```rb
2.6.5 :003 > Ripper.sexp('defined?(x)')
 => [:program, [[:defined, [:vcall, [:@ident, "x", [1, 9]]]]]]
2.6.5 :004 > Ripper.sexp('x = 1; defined?(x)')
 => [:program, [[:assign, [:var_field, [:@ident, "x", [1, 0]]], [:@int, "1", [1, 4]]], [:defined, [:var_ref, [:@ident, "x", [1, 16]]]]]]
```

> the argument is something the runtime is supposed to handle?

For variables we know it for sure during parse time. You can substitute `(defined? (lvar x))` with `"local-variable"` in all cases. There's no API to unset local variable in runtime.

For methods - yes, it's context-specific.

> it should perhaps instead simply produce something like `(defined? (str :x))`

you can pass random garbage (that is valid Ruby) to `defined?`:
```rb
2.6.5 :001 > defined?(
2.6.5 :002 >       a.b.c.d +
2.6.5 :003 >       MissingConstant +
2.6.5 :004 >       yield +
2.6.5 :005 >       super +
2.6.5 :006 >       nil * 2 +
2.6.5 :007 >       eval("!@#$%^") +
2.6.5 :008 >       require('missing_file')
2.6.5 :009?>   )
 => nil
```
do you want it to be parsed as `(defined? "<code>")`? Then you'd have to parse this code again, but in the right context. You'd have to give it a set of locals, information about current scope (inside a class/method/singleton class/top-level scope) and many other things. Parser automatically does it for you, why would you want it to return a raw string?

**Comment by iliabylich** [comment]
Closing. Feel free to reopen if you still have questions,
