### ISSUE TITLE
No Parser::Source::Range#eql?

### ISSUE THREAD

**Issue by marcandre** [whitequark/parser#670]
I hesitated opening this as it's super minor, but is it intentional that there is no `Parser::Source::Range#eql?` (and `#hash`)?

This prevents using `Range`s as meaningful hash keys or `when` conditions.

I noticed this when wondering if [RuboCop should optimize this `O(n^2)` algorithm](https://github.com/rubocop-hq/rubocop/blob/9c3f904e77b3c3786eaface4fdb545764136beca/lib/rubocop/cop/cop.rb#L146) although it would probably be completely negligible in that case compared to the actual policing...

I'd gladly provide a PR if desired.

**Comment by iliabylich** [comment]
Sorry, I missed this issue initially. Yes, it makes sense to me. Feel free to send a RP if you still need it.

**Comment by iliabylich** [comment]
implemented in https://github.com/whitequark/parser/pull/675
