### ISSUE TITLE
"Auto-expanding proc argument" section in the documentation

### ISSUE THREAD

**Issue by andrykonchin** [whitequark/parser#719]
There is an "Auto-expanding proc argument (1.9)" section in the `doc/AST_FORMAT.md` file:

> In Ruby 1.9 and later, when a proc-like closure (i.e. a closure created by capturing a block or with the proc method, but not with the ->{} syntax or the lambda method) has exactly one argument, and it is called with more than one argument, the behavior is as if the array of all arguments was instead passed as the sole argument. This behavior can be prevented by adding a comma after the sole argument (e.g. |foo,|).

> Format:
```
(procarg0 (arg :foo))
"|foo|"
  ~~~ expression

(procarg0 (arg :foo) (arg :bar))
"|(foo, bar)|"
  ~ begin
           ~ end
  ~~~~~~~~~~ expression
```

The statement `when a proc-like closure ... has exactly one argument, and it is called with more than one argument, the behavior is as if the array of all arguments was instead passed as the sole argument` seems not clear enough.

If I understand it correctly and it could be illustrated by the following example:

```
block = proc { |a| puts "=> #{a}" }; block.call(1, 2)
```

result will be different - only first argument (`1`) is passed to a block but not an array of both arguments (using Ruby 2.7):

```
=> 1
```

And consequently it isn't clear enough the purpose of `procarg0` node in the first example with only one regular argument

```
(procarg0 (arg :foo))
"|foo|"
  ~~~ expression
```

Could you please clarify this issue?

**Comment by iliabylich** [comment]
The purpose is to emit `|foo|` and `|foo,|` differently:

```
$ bin/ruby-parse -e 'm { |foo| }'
(block
  (send nil :m)
  (args
    (procarg0
      (arg :foo))) nil)

$ bin/ruby-parse -e 'm { |foo,| }'
(block
  (send nil :m)
  (args
    (arg :foo)) nil)
```

And the difference is exactly in expanding a single array argument:

```
$ irb
2.7.1 :001 > proc { |foo| foo }.call([1])
 => [1]
2.7.1 :002 > proc { |foo,| foo }.call([1])
 => 1
2.7.1 :003 >
```

**Comment by andrykonchin** [comment]
Ah, I see. Thank you.

But nevertheless I find the description (quoted above)... confusing.
