### ISSUE TITLE
Support special characters?

### ISSUE THREAD

**Issue by ghbren** [whitequark/parser#740]
When I try to parse special strings like "ab-cd-ef\x81", I get "literal contains escape sequences incompatible with UTF-8"

Would you be able to support that?

**Comment by iliabylich** [comment]
This string is invalid in UTF-8:
``` ruby
> "ab-cd-ef\x81".force_encoding('utf-8').valid_encoding?
 => false
```

So it's not even a string, it's more like a byte array. It's valid in `ascii-8bit` and you can enforce it by using a magic comment:
```ruby
# encoding: ascii-8bit

"ab-cd-ef\x81"
```

```sh
$ bin/ruby-parse --27 test.rb
(str "ab-cd-ef\x81")
```

IIRC you can also manually pass encoded source directly to `Parser` and force it use original encoding of the source input (`ascii-8bit` in your case)

The reason why such string literals are rejected is that MRI raises various errors when you work with them:
```
"ab-cd-ef\x81".encode('ascii-8bit') rescue $!
 => #<Encoding::InvalidByteSequenceError: "\x81" on UTF-8>
```

So the default strategy is to reject them. However if you don't care about these errors you can use a custom AST builder like rubocop does - https://github.com/rubocop-hq/rubocop-ast/blob/master/lib/rubocop/ast/builder.rb#L79-L83.

It's been reported multiple times, for more context you can check https://github.com/whitequark/parser/issues/283.
