### ISSUE TITLE
NoMethodError in parsing numparams with ruby 2.6 parser.

### ISSUE THREAD

**Issue by mbj** [whitequark/parser#742]
Tested with `parser-2.7.1.4` the following crashes the parser with a `NoMethodError`. I'd expect a `Parser::SyntaxError` instead.

```ruby
require 'parser/ruby26'

Parser::Ruby26.parse(<<~'RUBY')
  proc do
    _1 = nil
  end
RUBY
```

Exception backtrace:

```
NoMethodError: undefined method `>' for nil:NilClass
  /home/mutant-dev/.gem/ruby/2.6.6/gems/parser-2.7.1.4/lib/parser/max_numparam_stack.rb:21:in `has_numparams?'
  /home/mutant-dev/.gem/ruby/2.6.6/gems/parser-2.7.1.4/lib/parser/builders/default.rb:1569:in `check_assignment_to_numparam'
  /home/mutant-dev/.gem/ruby/2.6.6/gems/parser-2.7.1.4/lib/parser/builders/default.rb:592:in `assignable'
  /home/mutant-dev/.gem/ruby/2.6.6/gems/parser-2.7.1.4/lib/parser/ruby26.rb:3960:in `_reduce_102'
  /home/mutant-dev/.rubies/ruby-2.6.6/lib/ruby/2.6.0/racc/parser.rb:259:in `_racc_do_parse_c'
  /home/mutant-dev/.rubies/ruby-2.6.6/lib/ruby/2.6.0/racc/parser.rb:259:in `do_parse'
  /home/mutant-dev/.gem/ruby/2.6.6/gems/parser-2.7.1.4/lib/parser/base.rb:189:in `parse'
[snip callstack from unparser tests]
```

Note that this 2.7 syntax example is actually in the test corpus of parser itself. But as an 2.7 example. I wounder if tests for Ruby version N should be run by testsfor >N as "expect syntax error" examples.

So this issue proposes 2 things:

A) Fix the `NoMethodError` and raise a `SyntaxError` instead.
B) Re-use examples for newer syntax as expect syntax error examples for older parsers.

I'll take a stab ad A) later. But B) is open for discussion. IMO its a very useful property to re-use the test corpus this way.

**Comment by iliabylich** [comment]
Interesting. I can't reproduce it on the latest master, looks like I (accidentally) fixed it here https://github.com/whitequark/parser/pull/725/files#diff-0a90f5f53d48f851460a59d188b639c1R21.

I'll cut a release in a few hours, thanks for report.

> I wounder if tests for Ruby version N should be run by testsfor >N as "expect syntax error" examples

I agree, tests for `assert_parses(..., SINCE_X_Y)` can run the same code for `assert_raises(ALL_VERSIONS - SINCE_X_Y)`. The thing is that *technically* new versions can inherit code constructions from previous versions of Ruby, but with a different meaning. I can't remember anything like that, but I feel that such approach can be error-prone. EDIT: numparams is a good example, `proc { _1 }` is valid for all versions of Ruby, but starting from 2.7 `_1` is a block parameter.

Maybe it's enough to assert that either `SyntaxError` is raised or some AST is returned, aka `assert_not_raised(ErrorX) { ... }` that doesn't exist in minitest for a good reason. I like the idea, but I need to check if it can be applied to the whole test suite first.

**Comment by mbj** [comment]
> can inherit code constructions from previous versions of Ruby, but with a different meaning.

Yeah. These are actually breaking changes Ruby tries to avoid "deperately" via being biased to syntax additions. Where we actually get (silent) semantic changes in new ruby verisons. And most projects do not have the semantic coverage to verify these.

I suspect this kind of "inverse testing" I'm proposing may need some explicit whitelist per case. But I suspect that we can still catch "backwards incompatible forward changes being implemented wrong in parser" this way.

**Comment by iliabylich** [comment]
2.7.1.5 has been released https://rubygems.org/gems/parser/versions/2.7.1.5 /cc @marcandre 

> But I suspect that we can still catch "backwards incompatible forward changes being implemented wrong in parser" this way.

Agree. I'll play with it later today

**Comment by mbj** [comment]
> Agree. I'll play with it later today

Thanks for taking that one from me. Still working on major unparser improvements / 2.7 support. Cheers.

**Comment by mbj** [comment]
@iliabylich I think you can close this bug (and retroactively add it to the changelog).

**Comment by iliabylich** [comment]
nope, unfortunately changelog is still auto-generated from `git log`
