### ISSUE TITLE
Ship grammar files

### ISSUE THREAD

**Issue by kddeisz** [whitequark/parser#749]
Hi! 👋 

First of all, I'm sorry about this issue. I am very much reminded of

![XKCD](https://imgs.xkcd.com/comics/workflow.png)

A recent PR (https://github.com/whitequark/parser/pull/745) changed the files that get shipped with this gem. Believe it or not, I was actually relying on the `.y` files shipped with this gem for my own project (https://github.com/kddeisz/vernacular-ast). You can see the failure here (https://github.com/kddeisz/vernacular-ast/pull/83/checks?check_run_id=1218675563#step:8:6) because the `.y` files are no longer shipped.

Any chance I could get them back?

**Comment by mbj** [comment]
@kddeisz I think that, given the `parser` gem is widely used, it should by default NOT ship the grammar files.

Instead we should make a 2nd gem `parser-extra` or similar that ships all the "support stuff" that only some users need?

I'm not authoritative here, if the maintainer (@iliabylich) thinks its too much work to have a split gem. I'd support to bring the `.y` back, they are not "that much" in terms of byte weight.

**Comment by iliabylich** [comment]
Oof, looks like you rewrite grammar rules on the fly. Are you able to use git repo? You'll need to have ragel too, `lexer.rb` is under `.gitignore`.

I'm not super opinionated on adding these files back, but it just feels awkward to rely on private API. It sounds similar to re-using gem's test suite "because you can".

**Comment by kddeisz** [comment]
Yeah it's not widely used and I'm mostly maintaining it for posterity/interest. Honestly I think I'm cool just retiring it. I was thinking if you maybe wanted to ship them then that would be fine but if it's going to cause extra effort I'd rather just archive the project. 

Thanks for your work!
