### ISSUE TITLE
Warning of regular expression without escape

### ISSUE THREAD

**Issue by fidalgo** [whitequark/parser#752]
```
.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/parser-2.7.2.0/lib/parser/builders/default.rb:2057: warning: regular expression has ']' without escape: /([\w.%+\-]+)@([\w\-]+\.)+(\w]{2,)/
```

Found this after updating rubocop and parser to this version `2.7.2.0`

**Comment by marcandre** [comment]
That regexp looks pretty odd. Is it possible that this Regexp is somewhere in your code being inspected by `RuboCop`?

If you find a way run this code, the warning would raise an error and we'd get a full stack trace:
```ruby
module Warning
  def warn(msg)
    raise msg
  end
end
```

**Comment by iliabylich** [comment]
No, it comes from a regex that is a part of the source code. We build it to
1. make sure that it's valid (and emit syntax error if not)
2. extract named captures and (if it's used in matching) define local variables.

I don't know if it's correct to re-emit MRI warning. It's definitely doable, but we need to make sure that we only emit warnings/errors that come from parsing (i.e. from `ruby -c file.rb`) and not from runtime. Thoughts?

**Comment by marcandre** [comment]
Not too sure I understand "re-" in "re-emit" and "It's definitely doable", but it makes sense that this warning is emitted (assuming that strange regexp is present in the ruby code being inspected)

**Comment by iliabylich** [comment]
I mean, we can catch this warning and turn it into a diagnostic message. The question is should we do it? Currently there are two types of warnings that parser emits: diagnostic messages and warnings that come from MRI (because we use it to validate literals)

**Comment by marcandre** [comment]
Oh, right. I imagine it would make sense to turn it into a diagnostic message 👍

**Comment by marcandre** [comment]
FWIW, the strange Regexp is produced by a [bad auto-correction in RuboCop](https://github.com/rubocop-hq/rubocop/pull/8913) 😅

**Comment by iliabylich** [comment]
I was able to get warnings with the following code:

```ruby
require 'stringio'

def validate_re(source)
  stderr = $stderr
  $stderr = StringIO.new
  begin
    file = __FILE__; line = __LINE__; Regexp.new(source)
    $stderr.rewind
    prefix = "#{file}:#{line}: warning: "
    p $stderr.read.lines.map { |line| line[prefix] = ""; line }
  rescue RegexpError => e
    p e
  end
ensure
  $stderr = stderr
end

validate_re("([\w.%+\-]+)@([\w\-]+\.)+(\w]{2,)")
```

However, it
1. depends on the Ruby warning message format (that can change anytime and I'm not even sure if it's consistent across older Rubies and alternative Ruby implementations)
2. breaks on reformatting (i.e. on replacing `;` with newline)

I'm going to close it and keep MRI warning. If someone has thoughts on implementing it without these scary hacks please post it and reopen the issue.
