### ISSUE TITLE
do not emit empty method arguments

### ISSUE THREAD

**Issue by iliabylich** [whitequark/parser#766]
Currently the rule "all nodes have at least `expression_l`" works for all nodes except `args`:

```
bin/ruby-parse --30 -L -e 'def m; end'
s(:def, :m,
  s(:args), nil)
def m; end
~~~ keyword
    ~ name
       ~~~ end
~~~~~~~~~~ expression
s(:args)
```

We should emit `nil` in this case. Also, we should add some checks to the test suite to make sure that no other nodes act as dummy placeholders.

**Comment by marcandre** [comment]
What do you propose for `def m(); end`?

**Comment by iliabylich** [comment]
`s(:args)` with
+ `begin = pos of (`
+ `end = pos = )`
+ `expr = ( to )`
+ `children = []`

That's what we have right now

**Comment by marcandre** [comment]
I am strongly against producing a different AST (irrespective of locations) for the "same" ruby code.

**Comment by iliabylich** [comment]
Another example that is somewhat similar (and hopefully can convince you 😄 ) is a class definition without specifying explicit superclass (i.e. implicit `< Object` for `class Foo; end`). We also turn it into `nil`, but it's kinda obvious that all classes are implicitly inherited from `Object`.

I'm not super opinionated about it, you definitely know better how to *use* parser and thus which format is easier to consume and process.

The only argument I have is that this node has no source maps, and so it exists as a hacky placeholder for existing AST format

**Comment by marcandre** [comment]
You are right that they are usually the same, but not always:

```ruby
module Foo
  class Object
  end
  class Bar
  end
  class Baz < Object  # not the same as `Bar`
  end
end
```

In theory, even with `< ::Object`, you could still redefine the global constant `Object` (talk about shooting yourself in the foot though 😆).

So they are not 100% semantically equivalent.

There are other examples like this, e.g. `lambda { ... }` vs `-> { }`. They typically mean the same thing, but aren't 100% the same so we (now) produce a different AST.

OTOH, there is no difference between `def foo` and `def foo()`, like there is no difference between `obj.foo()` and `obj.foo`.

The "same Ruby code" <=> "same AST" can be important to reduce the burden on `unparser`, but in this particular case a client with a better claim is NodePattern. To search for a method `foo` with no arguments, I want to search for `(def :foo (args) _)`, (or if you want to change it to nil with `(def :foo nil? _)`) , but not both; it can be done (with `(def :foo {nil? (args)} _)`), but given the rarity of `def foo()` people are bound to forget that case.

**Comment by mbj** [comment]
> I am strongly against producing a different AST (disregarding locations) for the "same" ruby code (semantically, i.e. what it does).

I agree on that grounds. Different AST should ideally imply different execution semantics.

**Comment by marcandre** [comment]
If I'm not mistaken, by the same argument `%()` should have the same AST as `''`, which is another case requested by @mbj. I agree that the resulting AST should be `(str '')` (and not `(dstr)`).

**Comment by mbj** [comment]
Another way to say it: Lets avoid turning the AST into the source map. Which means that we possibly want to improve source maps to get a rid of dstr on multi line strings?

**Comment by iliabylich** [comment]
ok ok, I agree. I guess I just overestimated the rule of having source maps on all nodes over usability. Closing, thanks for convincing me.
