### ISSUE TITLE
Always emit body of a method as `begin` (but nil for empty body)

### ISSUE THREAD

**Issue by iliabylich** [whitequark/parser#767]
Currently we emit empty method as

```
bin/ruby-parse --30 -e 'def foo; end'
(def :foo
  (args) nil)
```

Method with a single statement as

```
bin/ruby-parse --30 -e 'def foo; bar; end'
(def :foo
  (args)
  (send nil :bar))
```

Method with multiple statements as

```
bin/ruby-parse --30 -e 'def foo; bar; baz; end'
(def :foo
  (args)
  (begin
    (send nil :bar)
    (send nil :baz)))
```

Ideally we should stick to the first and the last formats. If the body is empty we can't emit empty `begin` because there are no source maps to put in.

@marcandre It should also affect `class/module/sclass/if/case` and others, right? And in general all nodes that may contain multiple statements.

**Comment by marcandre** [comment]
> Ideally we should stick to the first and the second formats

You mean first and last formats I hope 😅

> If the body is empty we can't emit empty `begin` because there are no source maps to put in.

I think we could have a `begin` without source map, but `nil` is ok too.

> It should also affect `class/module/sclass/if/case` and others, right? And in general all nodes that may contain multiple statements.

Yes, in theory it should be all nodes with "bodies". I have second thoughts though. It doesn't work well at all for `if` in particular. Having `cnd ? 0 : 1` generate `(if (lvar :cnd) (int 0) (int 1)` is way nicer than `(if (lvar :cnd) (begin (int 0)) (begin (int 1))`.

We probably would not turn that switch on in `RuboCop`, too incompatible of a change.

**Comment by iliabylich** [comment]
> You mean first and last formats I hope 😅

Correct 🤦 

> It doesn't work well at all for `if` in particular

Uh oh, you are right. So only `def/defs/class/module/sclass` - these guys seem to be obvious. But then should the rule be something like "we need to wrap if *usually* there are multiple statements"? Are we able to define what's usual and what's not?

Eh, that's a great counter-example, now I'm not that positive about it as it feels way to fragile. Someone can have different expectations based on different understanding of "usual"

**Comment by marcandre** [comment]
> now I'm not that positive about it

Yep, probably best to let it rest.
