### ISSUE TITLE
Reduce dstr complexity on equivalent semantics but different AST.

### ISSUE THREAD

**Issue by mbj** [whitequark/parser#772]
As discussed in other issues here, I'd like to make `parser` emit less "noise" on dynamic strings.

Lets discuss some of the cases that make it hard for me to maintain unparser. The first case is a class of strings that express the same semantics but the AST is unique for squiggly heredocs:

```ruby
<<~HEREDOC.
  #{}
  #{}
HEREDOC

"#{}
#{}
"
```

Both dynamic strings express the same runtime behavior. But the AST structure returned by `parser` is uniquely bound to the concrete syntax:

```
s(:begin,
  s(:dstr,
    s(:str, ""),
    s(:begin),
    s(:str, "\n"),
    s(:str, ""),
    s(:begin),
    s(:str, "\n")),
  s(:dstr,
    s(:begin),
    s(:str, "\n"),
    s(:begin),
    s(:str, "\n")))
<<~HEREDOC
~~~~~~~~~~... expression
s(:dstr,
  s(:str, ""),
  s(:begin),
  s(:str, "\n"),
  s(:str, ""),
  s(:begin),
  s(:str, "\n"))
<<~HEREDOC
~~~~~~~~~~ expression
  #{}
~~~~~... heredoc_body
HEREDOC
~~~~~~~ heredoc_end
s(:str, "")
  #{}
~~ expression
s(:begin)
  #{}
    ~ end
  ~~ begin
  ~~~ expression
s(:str, "\n")
  #{}
     ... expression
s(:str, "")
  #{}
~~ expression
s(:begin)
  #{}
    ~ end
  ~~ begin
  ~~~ expression
s(:str, "\n")
  #{}
     ... expression
s(:dstr,
  s(:begin),
  s(:str, "\n"),
  s(:begin),
  s(:str, "\n"))
"#{}
~ begin
~~~~... expression
"
~ end
s(:begin)
"#{}
   ~ end
 ~~ begin
 ~~~ expression
s(:str, "\n")
"#{}
    ... expression
s(:begin)
#{}
  ~ end
~~ begin
~~~ expression
s(:str, "\n")
#{}
   ... expression
```

Proposed change: Eliminate all `s(:str, "")` nodes inside `dstr` from the squiggly heredoc case. Note I do NOT want to change this case:

```
bundle exec ruby-parse --locate -e '"" ""'
s(:dstr,
  s(:str, ""),
  s(:str, ""))
"" ""
~~~~~ expression
s(:str, "")
"" ""
 ~ end
~ begin
~~ expression
s(:str, "")
"" ""
    ~ end
   ~ begin
   ~~ expression
```

Removing these empty nodes would increase unparsers freedom to choose concrete syntax, removing one decision layer.

I'd even consider removing these empty nodes to not be a breaking change, they are not part of the documented AST format for squiggly heredocs.

**Comment by mbj** [comment]
@marcandre, @iliabylich what do you think about this proposal. I'd be happy to PR if you agreed that `s(:str, "")` nodes inside `dstr` have no real value unless they actually point to literal strings.

**Comment by iliabylich** [comment]
So to sum up: the ticket is about removing dummy `s(:str, "")` nodes that are implicitly removed from the source on heredoc dedenting, right?

👍  I agree, they have no source maps and no values. Feel free to send a PR, if not I'll do it in a few days

**Comment by marcandre** [comment]
Sounds good to me too 👍

**Comment by mbj** [comment]
@iliabylich thanks, sorry I couldn't get to it by myself.
