### ISSUE TITLE
Using assoc pattern matching as expr

### ISSUE THREAD

**Issue by palkan** [whitequark/parser#780]
Found an incompatibility between MRI and Parser:

```sh
$ ruby -v
ruby 3.0.0dev (2020-11-16T13:14:59Z master 0f37f384d4) [x86_64-linux]

$ ruby -e 'if {} => {a:}; end'
-e:1: warning: One-line pattern matching is experimental, and the behavior may change in future versions of Ruby!
-e:1: void value expression
if {} => {a:}; end
```

While Parser allows this (using master):

```ruby
$ bin/parse 'if {} => {a:}; end'

(if
  (match-pattern
    (hash)
    (hash-pattern
      (match-var :a))) nil nil)
```

**Comment by iliabylich** [comment]
Parser doesn't handle void value expressions - https://github.com/whitequark/parser#void-value-expressions. Or are you talking about the warning about experimental feature?

**Comment by palkan** [comment]
> Parser doesn't handle void value expressions

Oh, got it. I think, I will ignore them, too 🙂

> are you talking about the warning about experimental feature

Nope, I was referring to the void expression error.
