### ISSUE TITLE
recovering from parse errors when running under Opal

### ISSUE THREAD

**Issue by rubys** [whitequark/parser#784]
Preface: I don't know if this is a use case that parser is interested in supporting, or if it will accept pull requests to enable running under Opal, but it can't hurt to ask.  Here's a test case, including the first monkey patch.

```
require 'corelib/string/unpack'
require 'parser/current'

module Parser
  module Source
    class Buffer
      def source_lines
        @lines ||= begin
          lines = @source.lines.to_a
          lines << ''.dup if @source.end_with?("\n".freeze)

          lines = lines.map do |line|
            line.chomp("\n".freeze).freeze
          end

          lines.freeze
        end
      end
    end
  end
end

begin
  p Parser::CurrentRuby.parse('foo++')
rescue => e
  p e
end
```

To reproduce, place the above in a file named `test.opal`, and run `opal test.opal`.

The first problem, for which the workaround is included above, happens when the following line is executed: https://github.com/whitequark/parser/blob/7ea7f10b9577e209a66c5903bff56205d933a8f8/lib/parser/source/buffer.rb#L249

With Opal, all strings are immutable, so `chomp!` is not supported.  The workaround above replaces the `each` with a `map`.  It seems to me that replacing `@source.lines.to_a` with `@sourcelines.split("\n".freeze).map(&:freeze)` would enable the loop to be removed entirely.  I'm also curious if the `lines.freeze` line is necessary as it causes Opal to produce a warning.

All this workaround does is allow execution to proceed to the next error, which is in this code:  https://github.com/whitequark/parser/blob/6337d7bf676f66d80e43bd9d33dc17659f8af7f3/lib/parser/diagnostic.rb#L110-L135

The exception is as follows:

```
String#[]= not supported. Mutable String methods are not supported in Opal.
```

In this case, it looks like if highlight line were initialized as follows, the use of range indexing could be replaced by `+=`:

```ruby
highlight_line = ' ' * highlight.column_range.first
```

I can proceed further down this path, but first I would appreciate feedback on whether pull requests along these lines would be of interest to the project.

For background, what I am trying to do: https://github.com/ruby2js/ruby2js/issues/88

**Comment by marcandre** [comment]
> I don't know if this is a use case that parser is interested in supporting, or if it will accept pull requests to enable running under Opal, but it can't hurt to ask

This is going to be @iliabylich's and @whitequark's call. I did briefly entertain the thought of making my [node pattern debugger](http://nodepattern.heroku.com/) client-side only 😅

> I'm also curious if the lines.freeze line is necessary as it causes Opal to produce a warning.

I don't know what warning Opal is producing, but Opal should be changed, not the semantics of the code. Freezing data is important in general (e.g. so that `buffer.lines << 'extra line'` is not allowed) and mandatory for Ractor shareability.

**Comment by iliabylich** [comment]
> With Opal, all strings are immutable, so chomp! is not supported

Correct, and this is why Opal has the following patch - https://github.com/opal/opal/blob/master/lib/opal/parser/patch.rb#L32-L40

> With Opal, all strings are immutable, so `chomp!` is not supported. It seems to me that replacing @source.lines.to_a with @sourcelines.split("\n".freeze).map(&:freeze) would enable the loop to be removed entirely

Right, this code was changed in `parser-3.0.0.0`, but I guess Opal doesn't need to apply any additional changes.

> I'm also curious if the `lines.freeze` line is necessary as it causes Opal to produce a warning.

This `.freeze` call was added to make instances of `Buffer` share-able across multiple ractors. AST nodes contain `Source::Range`s, ranges refer to buffer. Without making buffer frozen we can't make nodes shareable.

On the warning: IIRC Opal produces this warning only on the JS side, i.e. when you compile ruby->js locally this warning doesn't appear, but if you use `opal-parser` (i.e. `whitequark/parser` compiled to JS + a few opal-specific patches) **on the JS side** - yes, you get the warning. As I remember it was very slow a few years ago, I'm not sure if it's a good idea to use it this way, better compile things locally/on CI and upload them to CDN/your web server.

> I can proceed further down this path, but first I would appreciate feedback on whether pull requests along these lines would be of interest to the project.

`opal-parser` is the only (?) library that needs it, right?

It doesn't make much sense for `parser` to work in "isolated" environment. Other Ruby -> <anything> transpilers can have their own limitations, but it doesn't mean that `parser` should handle all of them.

The first issue with source buffer shouldn't be changed here. `String#chomp` produces a new string and does a copy of all bytes behind a ruby string. It will make things slower for all rubies (including opal). Only `opal-parser` would benefit from it.

The second issue seems to be a bug in Opal (or just an incomplete set of patches). There's a patch for diagnostic messages here - https://github.com/opal/opal/blob/53593f7a82377deedd2d8082a92efd9b6848f1e0/lib/opal/parser/default_config.rb#L21 - but looks like it doesn't cover your case. Also, I like how it looks in the mutable style, and I'm not sure if it's gonna look OK once it's rewritten in immutable way.

**Comment by iliabylich** [comment]
> I did briefly entertain the thought of making my node pattern debugger client-side only 😅

Oh, I believe it's very doable with Opal, it can compile racc- and ragel-generated code (it can even compile `parser`). Only immutable strings and probably the lack of some new Ruby APIs that you use could cause troubles, but overall `Opal.use_gem` and `require 'rubocop/node-compiler'` should work out of the box.

**Comment by marcandre** [comment]
Cool, I'll add checking `rubocop-ast` Opal compatibilty on my ever-growing to-do list :-)

FWIW, `split("\n")` seems faster than `lines.map(&:chomp!)` (which is what was suggested here, not calling `chomp`)

```ruby
require 'benchmark/ips'

TEXT = (10...100).map { |i| "x" * i }.join("\n")

Benchmark.ips do |x|
  x.report('lines chomp') { TEXT.lines.map(&:chomp!) }
  x.report('split') { TEXT.split("\n") }
end
```

**Comment by iliabylich** [comment]
Right, but `split` doesn't handle `\r\n` (I believe that's the reason):

``` ruby
2.7.1 :001 > "a\r\nb".lines.map { |l| l.chomp("\n") }
 => ["a", "b"]
2.7.1 :002 > "a\r\nb".split("\n")
 => ["a\r", "b"]
```

**Comment by marcandre** [comment]
Oh, right...

**Comment by rubys** [comment]
`"a\r\nb".split(/\r?\n/)` produces the right answer, but may not be performant.

**Comment by marcandre** [comment]
> `"a\r\nb".split(/\r?\n/)` produces the right answer, but may not be performant.

Yeah, I double checked but it isn't

**Comment by rubys** [comment]
>  Also, I like how it looks in the mutable style, and I'm not sure if it's gonna look OK once it's rewritten in immutable way.

Here is what I was suggesting:

```ruby
    def render_line(range, ellipsis=false, range_end=false)
      source_line    = range.source_line
      highlight_line = ' ' * highlight.column_range.first

      @highlights.each do |highlight|
       line_range = range.source_buffer.line_range(range.line)
        if highlight = highlight.intersect(line_range)
          highlight_line += '~' * highlight.size
        end
      end

      if range.is?("\n")
        highlight_line += "^"
      else
        if !range_end && range.size >= 1
          highlight_line += '^' + '~' * (range.size - 1)
        else
          highlight_line += '~' * range.size
        end
      end

      highlight_line += '...' if ellipsis

      [source_line, highlight_line].
        map { |line| "#{range.source_buffer.name}:#{range.line}: #{line}" }
    end
```

I actually think the result is *more* readable, and probably even performs better, though I doubt that performance is critical on an error path like this one.

There is one difference in behavior, however.  The current code will have extra spaces after the highlighting, my proposed version does not.  That's probably an improvement, but if the spaces are necessary they can be added on at the end of the method.

**Comment by iliabylich** [comment]
Yes, I like it too. It does mutate strings, but error rendering is not a part of the default path.

Could you send a PR please?

**Comment by rubys** [comment]
It is prettier but buggy.  I'll work on a version that works, and submit a pull request.

By the way, it doesn't mutate strings, which is why Opal should be able to handle the modified version.

```
$ irb
irb(main):001:0> a = 'x'; b = a; a += a; puts b
x
```

**Comment by iliabylich** [comment]
Oh, that was I typo, I literally missed the word "not" 😄 . Right, it doesn't mutate strings.

**Comment by rubys** [comment]
Update: I found an unrelated issue (https://github.com/whitequark/parser/issues/785) and am pursuing a different patch for the use of mutable strings in `render_line`.  With the patch described below along with [patch.rb](https://github.com/opal/opal/blob/master/lib/opal/parser/patch.rb), I am able to recover from parse errors.

While it is rather straightforward to convert a single range into a highlight line without mutable strings, this code is expected to handle an arbitrary set of ranges.  Accordingly, I decided to take another approach.  Opal doesn't support mutable strings, but does support mutable arrays, and it is relatively straightforward to convert between the two using `split` and `join`.  Additionally, this code isn't performance sensitive, so I'm opting for a patch that very closely mirrors the current code.  As this is clearly being done specifically for Opal, and isn't an improvement for readability or performance, it doesn't make sense for me to submit a pull request.

The patch:

```ruby
    def render_line(range, ellipsis=false, range_end=false)
      source_line    = range.source_line
      highlight_line = [' '] * source_line.length

      @highlights.each do |highlight|
        line_range = range.source_buffer.line_range(range.line)
        if highlight = highlight.intersect(line_range)
          highlight_line[highlight.column_range] = ['~'] * highlight.size
        end
      end

      if range.is?("\n")
        highlight_line << "^"
      else
        if !range_end && range.size >= 1
          highlight_line[range.column_range] = ['^'] + ['~'] * (range.size - 1)
        else
          highlight_line[range.column_range] = ['~'] * range.size
        end
      end

      highlight_line += %w(. . .) if ellipsis
      highlight_line = highlight_line.join

      [source_line, highlight_line].
        map { |line| "#{range.source_buffer.name}:#{range.line}: #{line}" }
    end
```
