### ISSUE TITLE
Escaped backslash at end of line causes newline to be removed in heredocs

### ISSUE THREAD

**Issue by eugeneotto** [whitequark/parser#789]
Here is a small script that demonstrates the behavior:

```
$ cat foo.rb
puts <<~TXT
i am line one
i am line two \\
i am line \
three
i am line four \\
TXT
```

This is the script's output:

```
$ ruby foo.rb
i am line one
i am line two \
i am line three
i am line four \
```

This is ruby-parse's output:

```
$ ruby-parse foo.rb
(send nil :puts
  (dstr
    (str "i am line one\n")
    (str "i am line two ") # this line does not have a newline
    (str "i am line three\n")
    (str "i am line four \\ \n"))) # if there is another character after the escaped backslash, we get a newline

$ ruby-parse -v
ruby-parse based on parser version 3.0.0.0
```

**Comment by eugeneotto** [comment]
This does not appear to be an issue with stabby heredocs (`<<-TXT`).

**Comment by iliabylich** [comment]
@eugeneotto Thanks for reporting it.

The bug is definitely somewhere in https://github.com/whitequark/parser/blob/master/lib/parser/lexer/dedenter.rb. Looks like blindly splitting by `"\\\n"` is a wrong strategy, because `"\\"` part can go after another `"\\"` and so then it's just a single `"\"` character in the output.

I'll try to find some time to fix it. Or feel free to send a PR if you have time.

**Comment by mvz** [comment]
I'm working on a pull request for a related problem that seems to fix this issue as well.

**Comment by iliabylich** [comment]
Fixed in https://github.com/whitequark/parser/pull/819:

```
$ /bin/cat test.rb
puts <<~TXT
i am line one
i am line two \\
i am line \
three
i am line four \\
TXT

$ bin/ruby-parse test.rb
(send nil :puts
  (dstr
    (str "i am line one\n")
    (str "i am line two \\\n")
    (str "i am line three\n")
    (str "i am line four \\\n")))
```

@eugeneotto Do you need a release? If not it will be released with the next version of Ruby (or once someone asks for release)

**Comment by eugeneotto** [comment]
Thank you @iliabylich and @mvz! I can wait for the next version of Ruby, but do appreciate the offer 👍
