### ISSUE TITLE
Receiving unexpected token kIF_MOD

### ISSUE THREAD

**Issue by poloka** [whitequark/parser#802]
I will need to do some more investigating but going from the latest 2.7.x to this 3.0.x I am running into an error noting `unexpected token kIF_MOD`.  I will do more digging to reproduce and supply an example but figured I throw this out here in case someone else has seen it and had a suggestion before I spent a lot of time.
```
  1) FlattenJbuilder::Flattening::flattened_content returns the flattened content of Jbuilder file specified by file_path
     Failure/Error: ast, comments = ::Parser::CurrentRuby.parse_with_comments(code)

     Parser::SyntaxError:
       unexpected token kIF_MOD
     # /Users/GH/.rvm/gems/ruby-2.6.6@flatten_jbuilder/gems/parser-3.0.1.1/lib/parser/diagnostic/engine.rb:72:in `process'
     # /Users/GH/.rvm/gems/ruby-2.6.6@flatten_jbuilder/gems/parser-3.0.1.1/lib/parser/base.rb:286:in `on_error'
     # (eval):3:in `_racc_do_parse_c'
     # (eval):3:in `do_parse'
     # /Users/GH/.rvm/gems/ruby-2.6.6@flatten_jbuilder/gems/parser-3.0.1.1/lib/parser/base.rb:190:in `parse'
     # /Users/GH/.rvm/gems/ruby-2.6.6@flatten_jbuilder/gems/parser-3.0.1.1/lib/parser/base.rb:207:in `parse_with_comments'
     # /Users/GH/.rvm/gems/ruby-2.6.6@flatten_jbuilder/gems/parser-3.0.1.1/lib/parser/base.rb:52:in `parse_with_comments'
     # ./lib/flatten_jbuilder/normalizer.rb:62:in `reparsed_code'
     # ./lib/flatten_jbuilder/normalizer.rb:48:in `reformatted_code'
     # ./lib/flatten_jbuilder/flattening.rb:36:in `flattened_content'
     # ./lib/flatten_jbuilder/partial.rb:44:in `block in inlined_content'
     # ./lib/flatten_jbuilder/partial.rb:32:in `tap'
     # ./lib/flatten_jbuilder/partial.rb:32:in `inlined_content'
     # ./lib/flatten_jbuilder/flattening.rb:31:in `block in flattened_content'
     # ./lib/flatten_jbuilder/flattening.rb:22:in `each_line'
     # ./lib/flatten_jbuilder/flattening.rb:22:in `flattened_content'
     # ./spec/flatten_jbuilder/flattening_spec.rb:10:in `block (3 levels) in <top (required)>'
```

**Comment by iliabylich** [comment]
Could you post some example that gives this error? I think you can get it somewhere in `lib/flatten_jbuilder/normalizer.rb:62` 😄 

`kIF_MOD` token is what is emitted for the `if` keyword in code constructions like `foo if bar`. There were no changes to this logic for years, so I suppose you pass invalid Ruby code to `parser`

**Comment by poloka** [comment]
@iliabylich Interesting, if this code hasn't changed for years something in the sequencing has.  Like I mentioned, the 2.x version of the parser works without any issues but once update to the 3.x it fails with the noted error.  And thanks for the direction.  I am going to find a way to reproduce today and post my findings.

**Comment by poloka** [comment]
Since my issue looks most likely to be un related to parser, I'm going to close this for now.  I've got to do some more research into unparser to see how its logic in combination with using this project has caused me issues.

**Comment by mbj** [comment]
@poloka you also should only pass  the "modern ast format" to unparser, unparser is incompatible with the backwards compatible parser defaults.
