### ISSUE TITLE
Regression: Squiggly heredoc Unicode difference

### ISSUE THREAD

**Issue by hmdne** [whitequark/parser#835]
Caught this one with an Opal test failure

```ruby
[user@localhost parser]# ruby-parse _3.0.2.0_ -e $'<<~END\nŋ\nEND'
(str "ŋ\n")
[user@localhost parser]# ruby-parse _3.0.3.0_ -e $'<<~END\nŋ\nEND'
(str "\xC5\x8B\n")
[user@localhost parser]# ruby-parse _3.0.2.0_ -e $'<<~END\n🫄\nEND'
(str "\u{1FAC4}\n")
[user@localhost parser]# ruby-parse _3.0.3.0_ -e $'<<~END\n🫄\nEND'
(str "\xF0\x9F\xAB\x84\n")
[user@localhost parser]# 
```

I bisected this issue and it's caused by 61bf873c6194aef53e8cfdda85eb20d1283fa717

**Comment by iliabylich** [comment]
Thanks for reporting. Yes, that's definitely a bug.

From the first glance it looks like the bug comes from the missing `.force_encoding(original_encoding)` call on a single-line string. Would like you like to send a PR? If not it's absolutely ok, I'll fix it myself in a few hours.

**Comment by hmdne** [comment]
PR sent
