### ISSUE TITLE
parser/current is loading parser/ruby25, which recognizes2.5.9-compliant syntax, but you are running 2.5.8.

### ISSUE THREAD

**Issue by lacostenycoder** [whitequark/parser#870]
This type of issue seems to be recurring. Can this be fixed?

**Comment by iliabylich** [comment]
It's not a recurring issue, this warning is there on purpose. The warning also includes a link to [this section](https://github.com/whitequark/parser#compatibility-with-ruby-mri) which describes it.

Basically Ruby doesn't follow semantic versioning in it's grammar, there can be changes in a patch version.

However `parser` maintains only latest major versions, i.e. for 2.5 that is `2.5.9`, which makes it potentially incompatible with 2.5.8. I don't remember if there was an actual change in `2.5.9`, but that's the rule this library follows.

One solution for you is to downgrade `parser` to the latest version that **doesn't** know about 2.5.9 which I suppose is [`3.1.2.1`](https://github.com/whitequark/parser/commit/bbba39722450a808137cd69ddf516199f0dbec6e). IIRC rubocop doesn't have a strict requirement on a `parser` version, so you can choose almost any version you want.

Another way of course is to upgrade Ruby.

And the simplest and probably the worst solution is to swallow this warning programmatically.
