### ISSUE TITLE
F0 patch is slower on JRuby

### ISSUE THREAD

**Issue by headius** [whitequark/parser#897]
The F0 patch by @eregon in #894 does not seem to have been tested on JRuby. It results on slower overall performance (nearly 40% increase in iteration time on JRuby 9.4 on Java 19).

Before:
```
$ jruby -Xcompile.invokedynamic -Ilib -rparser/current -rbenchmark -e 'code=File.read("test/test_lexer.rb"); 300.times { p Benchmark.realtime { Parser::CurrentRuby.parse(code) } }'
warning: parser/current is loading parser/ruby31, which recognizes 3.1.3-compliant syntax, but you are running 3.1.0.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
3.0481747920000544
1.5487732079998295
1.3303452920001746
1.1635182499999246
1.1078780420000385
0.7642719590000979
0.8223455840000042
0.817049291000103
0.7946061669999835
0.5488661669999146
0.744005541999968
0.5867343749998781
0.6310182910001458
0.7006851670000742
0.5467942499999481
0.5257001249999576
0.5197279159999653
0.522568500000034
0.5697215420000248
0.47803762500006997
0.4702293330001339
0.4710854999998446
0.46676300000012816
0.46596324999995886
0.4652691670000877
```

After:
```
$ jruby -Xcompile.invokedynamic -Ilib -rparser/current -rbenchmark -e 'code=File.read("test/test_lexer.rb"); 300.times { p Benchmark.realtime { Parser::CurrentRuby.parse(code) } }' 
warning: parser/current is loading parser/ruby31, which recognizes 3.1.3-compliant syntax, but you are running 3.1.0.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
2.8906463329999497
1.6850116250000156
1.5632339579999552
1.5400360000001
1.2257214169999315
1.0129636250001113
0.9742802089999714
1.123100875000091
1.0968725000000177
0.78463366699998
1.0146426660000998
0.7126173750000362
0.8567333749999761
1.0378650420000213
0.8088761249998697
0.784552500000018
0.6859665000001769
0.7213790419998531
0.6974446249998891
0.6872767090001162
0.6648976250000942
0.6468434999999317
0.6522059999999783
0.6441516249999495
0.6461500840000554
```

In addition, it still does not JIT on TruffleRuby with default settings and performs only marginally better than the original code (about 3% reduction in the lowest iteration time, testing on 22.3 JVM CE version of TR):

Before:
```
$ PATH=~/graalvm-ce-java17-22.3.0/Contents/Home/bin/:$PATH ruby --jvm -v -Ilib -rparser/current -rbenchmark -e 'code=File.read("test/test_lexer.rb"); 300.times { p Benchmark.realtime { Parser::CurrentRuby.parse(code) } }'
truffleruby 22.3.0, like ruby 3.0.3, GraalVM CE JVM [aarch64-darwin]
warning: parser/current is loading parser/ruby30, which recognizes 3.0.5-compliant syntax, but you are running 3.0.3.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
15.119973541999798
9.894936125000186
7.052045416000055
5.923097999999982
6.112111916999993
5.653445791999957
5.768789833000028
5.661180042000069
5.675744749999922
5.672366792000048
5.648508958000093
5.814248375000034
5.620205166999995
5.654232042000103
5.684002416000112
5.691265707999946
5.653866999999991
5.655830250000008
```

After:
```
$ PATH=~/graalvm-ce-java17-22.3.0/Contents/Home/bin/:$PATH ruby --jvm -v -Ilib -rparser/current -rbenchmark -e 'code=File.read("test/test_lexer.rb"); 300.times { p Benchmark.realtime { Parser::CurrentRuby.parse(code) } }'
truffleruby 22.3.0, like ruby 3.0.3, GraalVM CE JVM [aarch64-darwin]
warning: parser/current is loading parser/ruby30, which recognizes 3.0.5-compliant syntax, but you are running 3.0.3.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
14.365774749999673
10.462339291999797
6.713167792000149
5.88699729200016
6.778854749999937
6.177687459000026
5.948219582999627
5.891877625000234
5.884802291000142
5.865142417000243
5.9028462919995945
6.02511474999983
5.868471041999783
5.848402124999666
5.882907499999874
6.001362624999729
5.829006667000158
5.923669291999886
5.9004028749996
6.063391792000402
5.862350458000037
5.850816166000186
```

I'm not sure the change in #894 should be merged since it only helps one Ruby implementation—only when passing experimental options—and it penalizes a different implementation.

**Comment by headius** [comment]
Outlining **just** that current_literal munging code drops the F1 `advance` instruction count on JRuby from 25005 to 19389.

I believe some judicious cleanup of the inlined code blocks throughout the grammar would greatly reduce the size of the `advance` method without changing the Ragel flags.

**Comment by headius** [comment]
Patch for the current_literal escape munging outlining: https://gist.github.com/headius/ed9d105e5dce8d29d5894f8e052eb791

**Comment by headius** [comment]
`extend_interp_code` is inlined four times. `e_lbrace` is inlined four times. `e_rbrace` is only inlined once but could be outlined. `extend_interp_digit_var` is inlined four times and only sets one local variable. `extend_interp_var` is inlined eight times. `extend_string_eol` is inlined 17 times.

There's lots and lots of these cases that could simply be made methods and keep the original Ragel options.

**Comment by eregon** [comment]
I meant to test JRuby but I got distracted and forgot, I'm sorry.

I can reproduce the slowdown on JDK17 with jruby-head:
```jruby 9.4.1.0-SNAPSHOT (3.1.0) 2022-12-19 6416265092 OpenJDK 64-Bit Server VM 17.0.6+2-jvmci-23.0-b04 on 17.0.6+2-jvmci-23.0-b04 +indy +jit [x86_64-linux]```
No indy:
```
$ ruby -Ilib -rparser/current -rbenchmark -e 'code=File.read("test/test_lexer.rb"); 300.times { p Benchmark.realtime { Parser::CurrentRuby.parse(code) } }'                        
before:
...
0.6749009689999639
0.6741202890000295
0.6748186979999673
0.6732500469998968
0.6712048389999836
after:
0.7672718629999054
0.7699705300000232
0.7670785799999749
0.7690608280000788
0.7675258970000414
```
~14% slower for non-indy

Indy:
```
before:
0.5589820909999617
0.558166998000047
0.5585064839999632
0.5590573230000473
0.5583587710000302
after:
0.7348502350000672
0.7333213650000516
0.7334011259999897
0.7343283679999786
0.7356647469999871
```
~31.7% slower for indy
Surprising that it penalizes indy much more than non-indy but it is what it is.

> In addition, it still does not JIT on TruffleRuby with default settings and performs only marginally better than the original code (about 3% reduction in the lowest iteration time, testing on 22.3 JVM CE version of TR):
> I'm not sure the change in https://github.com/whitequark/parser/pull/894 should be merged since it only helps one Ruby implementation—only when passing experimental options—and it penalizes a different implementation.

It's a 3-lines change to not use it on JRuby, I made a PR: #898.
That change is valuable for TruffleRuby and to make progress, it literally halves the method size (in number of line).
More changes are indeed needed so it can be compiled.
Going back to F0 for JRuby is IMHO a step backward in terms of method size, but I understand given the perf impact on JRuby. I guess it'll be useful to try F0 again on JRuby once `advance` is small enough in F0 for JRuby to compile.

> I believe some judicious cleanup of the inlined code blocks throughout the grammar would greatly reduce the size of the `advance` method without changing the Ragel flags.

I believe we need both. Also I think we need more PRs and concrete improvements rather than "what ifs" here, we've had a lot of ideas, we know we need to make it smaller, and every step helps. Could you make a PR for that `if current_literal.munge_escape? escaped_char`? (and benchmark it on CRuby, YJIT, JRuby & TruffleRuby)

**Comment by eregon** [comment]
BTW the TruffleRuby numbers above are significantly slower than for me locally on linux-amd64 (while the JRuby numbers are fairly close), where I get around `2.981`s per iteration (I used 22.3 JVM CE as well).
That's likely due to string intrinsics for aarch64 being added only recently, the easiest to avoid that issue on aarch64 is to use `ruby-build truffleruby+graalvm-dev ~/.rubies/truffleruby+graalvm-head`.

**Comment by eregon** [comment]
> There are a number of things that could be done to reduce the size of the parser without using F0, like outlining some of these large code blocks that get inlined by the Ragel generator. For example, the `if current_literal.munge_escape? escaped_char` code modifies no local variables and yet it is inlined **52 times** into the original `advance` method.

This has already been done, see https://github.com/whitequark/parser/pull/893.
Maybe your Ragel files are outdated? (`bundle exec rake generate`)

**Comment by headius** [comment]
> This has already been done

You're right, my files were out of date.

I will start putting together some PRs to outline more of these utility blocks of code. Thanks for patching F1 back for JRuby.
