### ISSUE TITLE
Changelog missing for 3.2.2.0?

### ISSUE THREAD

**Issue by tisba** [whitequark/parser#922]
Thank you for the super quick [release of 3.2.2.0](https://rubygems.org/gems/parser/versions/3.2.2.0) 💕 🎉 

One question though: A change log entry was added and then removed again (https://github.com/whitequark/parser/commit/2f50eaafffba640d1a5e23db102fbb03df809325)? I'm confused :) Looks like a unintentional removal.

**Comment by iliabylich** [comment]
Thanks, fixed in https://github.com/whitequark/parser/commit/f1da317a8b070d62161c9e243cb94327f1d3a35b

**Comment by tisba** [comment]
Awesome, thank you! 👏
