### ISSUE TITLE
warning: parser/current is loading parser/ruby33, which recognizes 3.3.0-dev-compliant syntax, but you are running 3.3.0.

### ISSUE THREAD

**Issue by dorianmarie** [whitequark/parser#982]
I get:

```
warning: parser/current is loading parser/ruby33, which recognizes 3.3.0-dev-compliant syntax, but you are running 3.3.0.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

So I was wondering if there is anything I need to do to have 3.3.0-compliant syntax (not 3.3.0-dev), or just wait?

In case I need to wait I think myself and others would like to know when the 3.3.0 parser is out so I felt like an issue tracking this would be helpful

Thanks,
Dorian

**Comment by iliabylich** [comment]
There's [only one change](https://github.com/whitequark/parser/issues/961) that has left but it's also the most tricky one out of all changes in 3.3, it requires quite a massive change to internal state management.

> if there is anything I need to do to have 3.3.0-compliant syntax (not 3.3.0-dev), or just wait

Just wait, I'm still getting back from holidays 🎉

**Comment by iliabylich** [comment]
`parser 3.3.0.0` [has been released](https://rubygems.org/gems/parser/versions/3.3.0.0)

**Comment by dorianmarie** [comment]
@iliabylich you dat best ❤️
